/*
 *  ChemSat+.global.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_ChemSat__global_h
#define h_ChemSat__global_h

/*********************************************************************
 *                   CHEMSAT+.E GLOBAL SECTION                       *
 *                                                                   *
 * Common code shared between the Host and IPG PSD processes.  This  *
 * section contains all the #define's, global variables and function *
 * declarations (prototypes).                                        *
 *********************************************************************/

/* Define possible pulseType list */
#define SINC_PULSE 0	         /* sinc pulse is used for chem sat */
#define CSM_PULSE 1	         /* csm pulse is used for chem sat */
#define CSMIN8_PULSE 2           /* 8 ms min phase chemsat pulse */
#define CSMAX8_PULSE 3           /* 8 ms max phase chemsat pulse */

/* The overdrive factors to account for RF decay between sat pulse and 
   excitation pulse */
#define	OVERDRIVE_FA_0_5T   99   /* overdrive flip angle factor for 0.5T */
#define	OVERDRIVE_FA_1_0T   95   /* overdrive flip angle factor for 1.0T */
#define	OVERDRIVE_FA_1_5T   94   /* overdrive flip angle factor for 1.5T */

/* Other defines for use in chem sat pulses */
#define FWCHEMSHIFT                  (220*cffield/15000)
#define FWCHEMSHIFT_HALF_TESLA_FAST  93.0
#define CHEM_SSP_FREQ_TIME           RFFREQ_LENGTH


#endif /* h_ChemSat__global_h */

