/*
 *  ChemSat+.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_ChemSat__runtime_h
#define h_ChemSat__runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 953056223;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_GXKCS_SLOT},
	{GE_INT, (char *)&_GYKCS_SLOT},
	{GE_INT, (char *)&_GZKCS_SLOT},
	{GE_INT, (char *)&_RFCSSAT_SLOT},
	{GE_INT, (char *)&_RFCSSAT_CFH_SLOT},
	{GE_INT, (char *)&_cs_sat},
	{GE_INT, (char *)&_cs_satstart},
	{GE_INT, (char *)&_cs_sattime},
	{GE_FLOAT, (char *)&_a_rfcssatcfh},
	{GE_FLOAT, (char *)&_flip_rfcssatcfh},
	{GE_INT, (char *)&_pw_rfcssatcfh},
	{GE_INT, (char *)&_ia_rfcssatcfh},
	{GE_INT, (char *)&_ChemSatPulse},
	{GE_FLOAT, (char *)&_area_gxkcs},
	{GE_FLOAT, (char *)&_area_gykcs},
	{GE_FLOAT, (char *)&_area_gyakcs},
	{GE_FLOAT, (char *)&_area_gzkcs},
	{GE_INT, (char *)&_ia_rfcssat},
	{GE_FLOAT, (char *)&_cyc_rfcssat},
	{GE_FLOAT, (char *)&_a_rfcssat},
	{GE_FLOAT, (char *)&_alpha_rfcssat},
	{GE_FLOAT, (char *)&_gscale_rfcssat},
	{GE_FLOAT, (char *)&_flip_rfcssat},
	{GE_INT, (char *)&_csat_rfupa},
	{GE_INT, (char *)&_csat_sys_type},
	{GE_INT, (char *)&_csat_crush_cycle},
	{GE_INT, (char *)&_csat_phase_random},
	{GE_INT, (char *)&_csat_same_phase},
	{GE_INT, (char *)&_pw_rfcssat},
	{GE_INT, (char *)&_off_rfcssat},
	{GE_INT, (char *)&_res_rfcssat},
	{GE_FLOAT, (char *)&_a_gykcs},
	{GE_INT, (char *)&_ia_gykcs},
	{GE_INT, (char *)&_pw_gykcsa},
	{GE_INT, (char *)&_pw_gykcsd},
	{GE_INT, (char *)&_pw_gykcs},
	{GE_FLOAT, (char *)&_a_gxkcs},
	{GE_INT, (char *)&_ia_gxkcs},
	{GE_INT, (char *)&_pw_gxkcsa},
	{GE_INT, (char *)&_pw_gxkcsd},
	{GE_INT, (char *)&_pw_gxkcs},
	{GE_FLOAT, (char *)&_a_gzkcs},
	{GE_INT, (char *)&_ia_gzkcs},
	{GE_INT, (char *)&_pw_gzkcsa},
	{GE_INT, (char *)&_pw_gzkcsd},
	{GE_INT, (char *)&_pw_gzkcs},
};
_cvname _namearray[] = {
	{"ChemSatPulse",12},
	{"GXKCS_SLOT",0},
	{"GYKCS_SLOT",1},
	{"GZKCS_SLOT",2},
	{"RFCSSAT_CFH_SLOT",4},
	{"RFCSSAT_SLOT",3},
	{"a_gxkcs",36},
	{"a_gykcs",31},
	{"a_gzkcs",41},
	{"a_rfcssat",19},
	{"a_rfcssatcfh",8},
	{"alpha_rfcssat",20},
	{"area_gxkcs",13},
	{"area_gyakcs",15},
	{"area_gykcs",14},
	{"area_gzkcs",16},
	{"cs_sat",5},
	{"cs_satstart",6},
	{"cs_sattime",7},
	{"csat_crush_cycle",25},
	{"csat_phase_random",26},
	{"csat_rfupa",23},
	{"csat_same_phase",27},
	{"csat_sys_type",24},
	{"cyc_rfcssat",18},
	{"flip_rfcssat",22},
	{"flip_rfcssatcfh",9},
	{"gscale_rfcssat",21},
	{"ia_gxkcs",37},
	{"ia_gykcs",32},
	{"ia_gzkcs",42},
	{"ia_rfcssat",17},
	{"ia_rfcssatcfh",11},
	{"off_rfcssat",29},
	{"pw_gxkcs",40},
	{"pw_gxkcsa",38},
	{"pw_gxkcsd",39},
	{"pw_gykcs",35},
	{"pw_gykcsa",33},
	{"pw_gykcsd",34},
	{"pw_gzkcs",45},
	{"pw_gzkcsa",43},
	{"pw_gzkcsd",44},
	{"pw_rfcssat",28},
	{"pw_rfcssatcfh",10},
	{"res_rfcssat",30},
};
_rspdataptr _rsparray[] = {
	{"CStun",GE_INT,0},
	{"amp_gxkcs",GE_INT,0},
	{"amp_gykcs",GE_INT,0},
	{"amp_gzkcs",GE_INT,0},
	{"csa",GE_FLOAT,0},
	{"cscfh_satindex",GE_INT,0},
	{"csf",GE_INT,0},
	{"csflip",GE_FLOAT,0},
	{"cstun",GE_INT,0},
};
int _ncvs = 46;
int _nrsps = 9;

#endif /* h_ChemSat__runtime_h */

