/*
 *  ChemSatFastcard.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_ChemSatFastcard_runtime_h
#define h_ChemSatFastcard_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 932749798;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_GXKCS2_SLOT},
	{GE_INT, (char *)&_GYKCS2_SLOT},
	{GE_INT, (char *)&_GZKCS2_SLOT},
	{GE_INT, (char *)&_RFCSSAT1_SLOT},
	{GE_INT, (char *)&_RFCSSAT2_SLOT},
	{GE_INT, (char *)&_bw_rfcssat1},
	{GE_INT, (char *)&_pw_rfcssat1},
	{GE_INT, (char *)&_pw_rfcssat2},
	{GE_INT, (char *)&_off_rfcssat1},
	{GE_INT, (char *)&_ia_rfcssat1},
	{GE_FLOAT, (char *)&_a_rfcssat1},
	{GE_FLOAT, (char *)&_cyc_rfcssat1},
	{GE_INT, (char *)&_ia_rfcssat2},
	{GE_FLOAT, (char *)&_a_rfcssat2},
	{GE_FLOAT, (char *)&_flip_rfcssat1},
	{GE_FLOAT, (char *)&_flip_rfcssat2},
	{GE_FLOAT, (char *)&_gscale_rfcssat1},
	{GE_INT, (char *)&_min_cssat_ti},
	{GE_INT, (char *)&_min_cssat_ti_rnd},
	{GE_INT, (char *)&_cssat_ti},
	{GE_INT, (char *)&_cssat_ti_def},
	{GE_INT, (char *)&_chemsat_type},
	{GE_INT, (char *)&_dospecir_flag},
	{GE_INT, (char *)&_specir_flag},
	{GE_INT, (char *)&_fccs_flag},
	{GE_INT, (char *)&_time_ssi_cssat},
	{GE_FLOAT, (char *)&_area_gxkcs2},
	{GE_FLOAT, (char *)&_area_gykcs2},
	{GE_FLOAT, (char *)&_area_gzkcs2},
	{GE_INT, (char *)&_res_rfcssat2},
	{GE_INT, (char *)&_res_rfcssat1},
	{GE_FLOAT, (char *)&_a_gxkcs2},
	{GE_INT, (char *)&_ia_gxkcs2},
	{GE_INT, (char *)&_pw_gxkcs2a},
	{GE_INT, (char *)&_pw_gxkcs2d},
	{GE_INT, (char *)&_pw_gxkcs2},
	{GE_FLOAT, (char *)&_a_gykcs2},
	{GE_INT, (char *)&_ia_gykcs2},
	{GE_INT, (char *)&_pw_gykcs2a},
	{GE_INT, (char *)&_pw_gykcs2d},
	{GE_INT, (char *)&_pw_gykcs2},
	{GE_FLOAT, (char *)&_a_gzkcs2},
	{GE_INT, (char *)&_ia_gzkcs2},
	{GE_INT, (char *)&_pw_gzkcs2a},
	{GE_INT, (char *)&_pw_gzkcs2d},
	{GE_INT, (char *)&_pw_gzkcs2},
};
_cvname _namearray[] = {
	{"GXKCS2_SLOT",0},
	{"GYKCS2_SLOT",1},
	{"GZKCS2_SLOT",2},
	{"RFCSSAT1_SLOT",3},
	{"RFCSSAT2_SLOT",4},
	{"a_gxkcs2",31},
	{"a_gykcs2",36},
	{"a_gzkcs2",41},
	{"a_rfcssat1",10},
	{"a_rfcssat2",13},
	{"area_gxkcs2",26},
	{"area_gykcs2",27},
	{"area_gzkcs2",28},
	{"bw_rfcssat1",5},
	{"chemsat_type",21},
	{"cssat_ti",19},
	{"cssat_ti_def",20},
	{"cyc_rfcssat1",11},
	{"dospecir_flag",22},
	{"fccs_flag",24},
	{"flip_rfcssat1",14},
	{"flip_rfcssat2",15},
	{"gscale_rfcssat1",16},
	{"ia_gxkcs2",32},
	{"ia_gykcs2",37},
	{"ia_gzkcs2",42},
	{"ia_rfcssat1",9},
	{"ia_rfcssat2",12},
	{"min_cssat_ti",17},
	{"min_cssat_ti_rnd",18},
	{"off_rfcssat1",8},
	{"pw_gxkcs2",35},
	{"pw_gxkcs2a",33},
	{"pw_gxkcs2d",34},
	{"pw_gykcs2",40},
	{"pw_gykcs2a",38},
	{"pw_gykcs2d",39},
	{"pw_gzkcs2",45},
	{"pw_gzkcs2a",43},
	{"pw_gzkcs2d",44},
	{"pw_rfcssat1",6},
	{"pw_rfcssat2",7},
	{"res_rfcssat1",30},
	{"res_rfcssat2",29},
	{"specir_flag",23},
	{"time_ssi_cssat",25},
};
_rspdataptr _rsparray[] = {
{0,0,0}};
int _ncvs = 46;
int _nrsps = 0;

#endif /* h_ChemSatFastcard_runtime_h */

