/*
 *  cv_const.exportstr.h
 *
 *  Do not edit this file. It is automatically generated by EPIC+.
 *
 *  Date : May 19 2000
 *  Time : 11:31:19
 */

#ifndef h_cv_const_exportstr_h
#define h_cv_const_exportstr_h

#ifdef INC4CPP
#include "epic_struct.h"
#include "em_psd_ermes.in"
#include "cv_const.global.h"
#endif

EXTERN _export  _scan_info
#ifdef INIT
= {(char *) scan_info,sizeof(scan_info),GE_STRUCT} 
#endif
;

EXTERN _export  _data_acq_order
#ifdef INIT
= {(char *) data_acq_order,sizeof(data_acq_order),GE_STRUCT} 
#endif
;

EXTERN _export  _entry_point_table
#ifdef INIT
= {(char *) entry_point_table,sizeof(entry_point_table),GE_STRUCT} 
#endif
;

EXTERN _export  _ihtdeltab
#ifdef INIT
= {(char *) &ihtdeltab,sizeof(ihtdeltab),GE_STRUCT} 
#endif
;

EXTERN _export  _ihtrtab
#ifdef INIT
= {(char *) &ihtrtab,sizeof(ihtrtab),GE_STRUCT} 
#endif
;

EXTERN _export  _avminnecho
#ifdef INIT
= {(char *) &avminnecho,sizeof(avminnecho),GE_INT} 
#endif
;

EXTERN _export  _avmaxnecho
#ifdef INIT
= {(char *) &avmaxnecho,sizeof(avmaxnecho),GE_INT} 
#endif
;

EXTERN _export  _avminte
#ifdef INIT
= {(char *) &avminte,sizeof(avminte),GE_INT} 
#endif
;

EXTERN _export  _avmaxte
#ifdef INIT
= {(char *) &avmaxte,sizeof(avmaxte),GE_INT} 
#endif
;

EXTERN _export  _avminte2
#ifdef INIT
= {(char *) &avminte2,sizeof(avminte2),GE_INT} 
#endif
;

EXTERN _export  _avmaxte2
#ifdef INIT
= {(char *) &avmaxte2,sizeof(avmaxte2),GE_INT} 
#endif
;

EXTERN _export  _avminti
#ifdef INIT
= {(char *) &avminti,sizeof(avminti),GE_INT} 
#endif
;

EXTERN _export  _avmaxti
#ifdef INIT
= {(char *) &avmaxti,sizeof(avmaxti),GE_INT} 
#endif
;

EXTERN _export  _avminbspti
#ifdef INIT
= {(char *) &avminbspti,sizeof(avminbspti),GE_INT} 
#endif
;

EXTERN _export  _avmaxbspti
#ifdef INIT
= {(char *) &avmaxbspti,sizeof(avmaxbspti),GE_INT} 
#endif
;

EXTERN _export  _avmintr
#ifdef INIT
= {(char *) &avmintr,sizeof(avmintr),GE_INT} 
#endif
;

EXTERN _export  _avmaxtr
#ifdef INIT
= {(char *) &avmaxtr,sizeof(avmaxtr),GE_INT} 
#endif
;

EXTERN _export  _avmaxphases
#ifdef INIT
= {(char *) &avmaxphases,sizeof(avmaxphases),GE_INT} 
#endif
;

EXTERN _export  _avmintseq
#ifdef INIT
= {(char *) &avmintseq,sizeof(avmintseq),GE_INT} 
#endif
;

EXTERN _export  _avmintdel1
#ifdef INIT
= {(char *) &avmintdel1,sizeof(avmintdel1),GE_INT} 
#endif
;

EXTERN _export  _pitdel1
#ifdef INIT
= {(char *) &pitdel1,sizeof(pitdel1),GE_INT} 
#endif
;

EXTERN _export  _avminfov
#ifdef INIT
= {(char *) &avminfov,sizeof(avminfov),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxfov
#ifdef INIT
= {(char *) &avmaxfov,sizeof(avmaxfov),GE_FLOAT} 
#endif
;

EXTERN _export  _avminslquant
#ifdef INIT
= {(char *) &avminslquant,sizeof(avminslquant),GE_INT} 
#endif
;

EXTERN _export  _avmaxslquant
#ifdef INIT
= {(char *) &avmaxslquant,sizeof(avmaxslquant),GE_INT} 
#endif
;

EXTERN _export  _avmaxacqs
#ifdef INIT
= {(char *) &avmaxacqs,sizeof(avmaxacqs),GE_INT} 
#endif
;

EXTERN _export  _avmaxyres
#ifdef INIT
= {(char *) &avmaxyres,sizeof(avmaxyres),GE_INT} 
#endif
;

EXTERN _export  _avmaxxres
#ifdef INIT
= {(char *) &avmaxxres,sizeof(avmaxxres),GE_INT} 
#endif
;

EXTERN _export  _avminrbw
#ifdef INIT
= {(char *) &avminrbw,sizeof(avminrbw),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxrbw
#ifdef INIT
= {(char *) &avmaxrbw,sizeof(avmaxrbw),GE_FLOAT} 
#endif
;

EXTERN _export  _avminrbw2
#ifdef INIT
= {(char *) &avminrbw2,sizeof(avminrbw2),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxrbw2
#ifdef INIT
= {(char *) &avmaxrbw2,sizeof(avmaxrbw2),GE_FLOAT} 
#endif
;

EXTERN _export  _avminvenc
#ifdef INIT
= {(char *) &avminvenc,sizeof(avminvenc),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxvenc
#ifdef INIT
= {(char *) &avmaxvenc,sizeof(avmaxvenc),GE_FLOAT} 
#endif
;

EXTERN _export  _avminsldelay
#ifdef INIT
= {(char *) &avminsldelay,sizeof(avminsldelay),GE_INT} 
#endif
;

EXTERN _export  _avmaxsldelay
#ifdef INIT
= {(char *) &avmaxsldelay,sizeof(avmaxsldelay),GE_INT} 
#endif
;

EXTERN _export  _avminfphases
#ifdef INIT
= {(char *) &avminfphases,sizeof(avminfphases),GE_INT} 
#endif
;

EXTERN _export  _avmaxfphases
#ifdef INIT
= {(char *) &avmaxfphases,sizeof(avmaxfphases),GE_INT} 
#endif
;

EXTERN _export  _avmaxovl
#ifdef INIT
= {(char *) &avmaxovl,sizeof(avmaxovl),GE_INT} 
#endif
;

EXTERN _export  _piimages
#ifdef INIT
= {(char *) &piimages,sizeof(piimages),GE_INT} 
#endif
;

EXTERN _export  _pisatthick
#ifdef INIT
= {(char *) &pisatthick,sizeof(pisatthick),GE_INT} 
#endif
;

EXTERN _export  _pisatthickx
#ifdef INIT
= {(char *) &pisatthickx,sizeof(pisatthickx),GE_INT} 
#endif
;

EXTERN _export  _pisatthicky
#ifdef INIT
= {(char *) &pisatthicky,sizeof(pisatthicky),GE_INT} 
#endif
;

EXTERN _export  _pisatthickz
#ifdef INIT
= {(char *) &pisatthickz,sizeof(pisatthickz),GE_INT} 
#endif
;

EXTERN _export  _piautopause
#ifdef INIT
= {(char *) &piautopause,sizeof(piautopause),GE_INT} 
#endif
;

EXTERN _export  _pislblank
#ifdef INIT
= {(char *) &pislblank,sizeof(pislblank),GE_INT} 
#endif
;

EXTERN _export  _pitseq
#ifdef INIT
= {(char *) &pitseq,sizeof(pitseq),GE_INT} 
#endif
;

EXTERN _export  _piait
#ifdef INIT
= {(char *) &piait,sizeof(piait),GE_INT} 
#endif
;

EXTERN _export  _pietr
#ifdef INIT
= {(char *) &pietr,sizeof(pietr),GE_INT} 
#endif
;

EXTERN _export  _picsifov
#ifdef INIT
= {(char *) &picsifov,sizeof(picsifov),GE_INT} 
#endif
;

EXTERN _export  _pirlcsi
#ifdef INIT
= {(char *) &pirlcsi,sizeof(pirlcsi),GE_INT} 
#endif
;

EXTERN _export  _piapcsi
#ifdef INIT
= {(char *) &piapcsi,sizeof(piapcsi),GE_INT} 
#endif
;

EXTERN _export  _pisicsi
#ifdef INIT
= {(char *) &pisicsi,sizeof(pisicsi),GE_INT} 
#endif
;

EXTERN _export  _piroigrx
#ifdef INIT
= {(char *) &piroigrx,sizeof(piroigrx),GE_INT} 
#endif
;

EXTERN _export  _piadvise
#ifdef INIT
= {(char *) &piadvise,sizeof(piadvise),GE_INT} 
#endif
;

EXTERN _export  _piadvmin
#ifdef INIT
= {(char *) &piadvmin,sizeof(piadvmin),GE_INT} 
#endif
;

EXTERN _export  _piadvmax
#ifdef INIT
= {(char *) &piadvmax,sizeof(piadvmax),GE_INT} 
#endif
;

EXTERN _export  _piadvtime
#ifdef INIT
= {(char *) &piadvtime,sizeof(piadvtime),GE_INT} 
#endif
;

EXTERN _export  _piadvcard
#ifdef INIT
= {(char *) &piadvcard,sizeof(piadvcard),GE_INT} 
#endif
;

EXTERN _export  _pifilt4
#ifdef INIT
= {(char *) &pifilt4,sizeof(pifilt4),GE_INT} 
#endif
;

EXTERN _export  _pifilt5
#ifdef INIT
= {(char *) &pifilt5,sizeof(pifilt5),GE_INT} 
#endif
;

EXTERN _export  _pifilt6
#ifdef INIT
= {(char *) &pifilt6,sizeof(pifilt6),GE_INT} 
#endif
;

EXTERN _export  _pifilt7
#ifdef INIT
= {(char *) &pifilt7,sizeof(pifilt7),GE_INT} 
#endif
;

EXTERN _export  _pitfeextra
#ifdef INIT
= {(char *) &pitfeextra,sizeof(pitfeextra),GE_INT} 
#endif
;

EXTERN _export  _pipsar
#ifdef INIT
= {(char *) &pipsar,sizeof(pipsar),GE_FLOAT} 
#endif
;

EXTERN _export  _piasar
#ifdef INIT
= {(char *) &piasar,sizeof(piasar),GE_FLOAT} 
#endif
;

EXTERN _export  _pitr
#ifdef INIT
= {(char *) &pitr,sizeof(pitr),GE_INT} 
#endif
;

EXTERN _export  _pichop
#ifdef INIT
= {(char *) &pichop,sizeof(pichop),GE_INT} 
#endif
;

EXTERN _export  _pitsp1
#ifdef INIT
= {(char *) &pitsp1,sizeof(pitsp1),GE_INT} 
#endif
;

EXTERN _export  _pitsp2
#ifdef INIT
= {(char *) &pitsp2,sizeof(pitsp2),GE_INT} 
#endif
;

EXTERN _export  _picalmode
#ifdef INIT
= {(char *) &picalmode,sizeof(picalmode),GE_INT} 
#endif
;

EXTERN _export  _pislquant
#ifdef INIT
= {(char *) &pislquant,sizeof(pislquant),GE_INT} 
#endif
;

EXTERN _export  _pinex
#ifdef INIT
= {(char *) &pinex,sizeof(pinex),GE_INT} 
#endif
;

EXTERN _export  _piuset
#ifdef INIT
= {(char *) &piuset,sizeof(piuset),GE_INT} 
#endif
;

EXTERN _export  _pimphscrn
#ifdef INIT
= {(char *) &pimphscrn,sizeof(pimphscrn),GE_INT} 
#endif
;

EXTERN _export  _pifphasenub
#ifdef INIT
= {(char *) &pifphasenub,sizeof(pifphasenub),GE_INT} 
#endif
;

EXTERN _export  _pifphaseval2
#ifdef INIT
= {(char *) &pifphaseval2,sizeof(pifphaseval2),GE_INT} 
#endif
;

EXTERN _export  _pifphaseval3
#ifdef INIT
= {(char *) &pifphaseval3,sizeof(pifphaseval3),GE_INT} 
#endif
;

EXTERN _export  _pifphaseval4
#ifdef INIT
= {(char *) &pifphaseval4,sizeof(pifphaseval4),GE_INT} 
#endif
;

EXTERN _export  _pifphaseval5
#ifdef INIT
= {(char *) &pifphaseval5,sizeof(pifphaseval5),GE_INT} 
#endif
;

EXTERN _export  _pifphaseval6
#ifdef INIT
= {(char *) &pifphaseval6,sizeof(pifphaseval6),GE_INT} 
#endif
;

EXTERN _export  _pisldelnub
#ifdef INIT
= {(char *) &pisldelnub,sizeof(pisldelnub),GE_INT} 
#endif
;

EXTERN _export  _pisldelval3
#ifdef INIT
= {(char *) &pisldelval3,sizeof(pisldelval3),GE_INT} 
#endif
;

EXTERN _export  _pisldelval4
#ifdef INIT
= {(char *) &pisldelval4,sizeof(pisldelval4),GE_INT} 
#endif
;

EXTERN _export  _pisldelval5
#ifdef INIT
= {(char *) &pisldelval5,sizeof(pisldelval5),GE_INT} 
#endif
;

EXTERN _export  _pisldelval6
#ifdef INIT
= {(char *) &pisldelval6,sizeof(pisldelval6),GE_INT} 
#endif
;

EXTERN _export  _piacqnub
#ifdef INIT
= {(char *) &piacqnub,sizeof(piacqnub),GE_INT} 
#endif
;

EXTERN _export  _pisctim
#ifdef INIT
= {(char *) &pisctim,sizeof(pisctim),GE_INT} 
#endif
;

EXTERN _export  _pifanub
#ifdef INIT
= {(char *) &pifanub,sizeof(pifanub),GE_INT} 
#endif
;

EXTERN _export  _pifaval2
#ifdef INIT
= {(char *) &pifaval2,sizeof(pifaval2),GE_INT} 
#endif
;

EXTERN _export  _pifaval3
#ifdef INIT
= {(char *) &pifaval3,sizeof(pifaval3),GE_INT} 
#endif
;

EXTERN _export  _pifaval4
#ifdef INIT
= {(char *) &pifaval4,sizeof(pifaval4),GE_INT} 
#endif
;

EXTERN _export  _pifaval5
#ifdef INIT
= {(char *) &pifaval5,sizeof(pifaval5),GE_INT} 
#endif
;

EXTERN _export  _pifaval6
#ifdef INIT
= {(char *) &pifaval6,sizeof(pifaval6),GE_INT} 
#endif
;

EXTERN _export  _pisatnub
#ifdef INIT
= {(char *) &pisatnub,sizeof(pisatnub),GE_INT} 
#endif
;

EXTERN _export  _piccsatnub
#ifdef INIT
= {(char *) &piccsatnub,sizeof(piccsatnub),GE_INT} 
#endif
;

EXTERN _export  _pisupnub
#ifdef INIT
= {(char *) &pisupnub,sizeof(pisupnub),GE_INT} 
#endif
;

EXTERN _export  _pietlnub
#ifdef INIT
= {(char *) &pietlnub,sizeof(pietlnub),GE_INT} 
#endif
;

EXTERN _export  _pietlval2
#ifdef INIT
= {(char *) &pietlval2,sizeof(pietlval2),GE_INT} 
#endif
;

EXTERN _export  _pietlval3
#ifdef INIT
= {(char *) &pietlval3,sizeof(pietlval3),GE_INT} 
#endif
;

EXTERN _export  _pietlval4
#ifdef INIT
= {(char *) &pietlval4,sizeof(pietlval4),GE_INT} 
#endif
;

EXTERN _export  _pietlval5
#ifdef INIT
= {(char *) &pietlval5,sizeof(pietlval5),GE_INT} 
#endif
;

EXTERN _export  _pietlval6
#ifdef INIT
= {(char *) &pietlval6,sizeof(pietlval6),GE_INT} 
#endif
;

EXTERN _export  _piechnub
#ifdef INIT
= {(char *) &piechnub,sizeof(piechnub),GE_INT} 
#endif
;

EXTERN _export  _piechval1
#ifdef INIT
= {(char *) &piechval1,sizeof(piechval1),GE_INT} 
#endif
;

EXTERN _export  _piechval2
#ifdef INIT
= {(char *) &piechval2,sizeof(piechval2),GE_INT} 
#endif
;

EXTERN _export  _piechval3
#ifdef INIT
= {(char *) &piechval3,sizeof(piechval3),GE_INT} 
#endif
;

EXTERN _export  _piechval4
#ifdef INIT
= {(char *) &piechval4,sizeof(piechval4),GE_INT} 
#endif
;

EXTERN _export  _piechval5
#ifdef INIT
= {(char *) &piechval5,sizeof(piechval5),GE_INT} 
#endif
;

EXTERN _export  _pitetype
#ifdef INIT
= {(char *) &pitetype,sizeof(pitetype),GE_INT} 
#endif
;

EXTERN _export  _pite1nub
#ifdef INIT
= {(char *) &pite1nub,sizeof(pite1nub),GE_INT} 
#endif
;

EXTERN _export  _pite1val2
#ifdef INIT
= {(char *) &pite1val2,sizeof(pite1val2),GE_INT} 
#endif
;

EXTERN _export  _pite1val3
#ifdef INIT
= {(char *) &pite1val3,sizeof(pite1val3),GE_INT} 
#endif
;

EXTERN _export  _pite1val4
#ifdef INIT
= {(char *) &pite1val4,sizeof(pite1val4),GE_INT} 
#endif
;

EXTERN _export  _pite1val5
#ifdef INIT
= {(char *) &pite1val5,sizeof(pite1val5),GE_INT} 
#endif
;

EXTERN _export  _pite1val6
#ifdef INIT
= {(char *) &pite1val6,sizeof(pite1val6),GE_INT} 
#endif
;

EXTERN _export  _pite2nub
#ifdef INIT
= {(char *) &pite2nub,sizeof(pite2nub),GE_INT} 
#endif
;

EXTERN _export  _pite2val2
#ifdef INIT
= {(char *) &pite2val2,sizeof(pite2val2),GE_INT} 
#endif
;

EXTERN _export  _pite2val3
#ifdef INIT
= {(char *) &pite2val3,sizeof(pite2val3),GE_INT} 
#endif
;

EXTERN _export  _pite2val4
#ifdef INIT
= {(char *) &pite2val4,sizeof(pite2val4),GE_INT} 
#endif
;

EXTERN _export  _pite2val5
#ifdef INIT
= {(char *) &pite2val5,sizeof(pite2val5),GE_INT} 
#endif
;

EXTERN _export  _pite2val6
#ifdef INIT
= {(char *) &pite2val6,sizeof(pite2val6),GE_INT} 
#endif
;

EXTERN _export  _pitrnub
#ifdef INIT
= {(char *) &pitrnub,sizeof(pitrnub),GE_INT} 
#endif
;

EXTERN _export  _pitrval2
#ifdef INIT
= {(char *) &pitrval2,sizeof(pitrval2),GE_INT} 
#endif
;

EXTERN _export  _pitrval3
#ifdef INIT
= {(char *) &pitrval3,sizeof(pitrval3),GE_INT} 
#endif
;

EXTERN _export  _pitrval4
#ifdef INIT
= {(char *) &pitrval4,sizeof(pitrval4),GE_INT} 
#endif
;

EXTERN _export  _pitrval5
#ifdef INIT
= {(char *) &pitrval5,sizeof(pitrval5),GE_INT} 
#endif
;

EXTERN _export  _pitrval6
#ifdef INIT
= {(char *) &pitrval6,sizeof(pitrval6),GE_INT} 
#endif
;

EXTERN _export  _pititype
#ifdef INIT
= {(char *) &pititype,sizeof(pititype),GE_INT} 
#endif
;

EXTERN _export  _pitinub
#ifdef INIT
= {(char *) &pitinub,sizeof(pitinub),GE_INT} 
#endif
;

EXTERN _export  _pitidefval
#ifdef INIT
= {(char *) &pitidefval,sizeof(pitidefval),GE_INT} 
#endif
;

EXTERN _export  _pitival2
#ifdef INIT
= {(char *) &pitival2,sizeof(pitival2),GE_INT} 
#endif
;

EXTERN _export  _pitival3
#ifdef INIT
= {(char *) &pitival3,sizeof(pitival3),GE_INT} 
#endif
;

EXTERN _export  _pitival4
#ifdef INIT
= {(char *) &pitival4,sizeof(pitival4),GE_INT} 
#endif
;

EXTERN _export  _pitival5
#ifdef INIT
= {(char *) &pitival5,sizeof(pitival5),GE_INT} 
#endif
;

EXTERN _export  _pitival6
#ifdef INIT
= {(char *) &pitival6,sizeof(pitival6),GE_INT} 
#endif
;

EXTERN _export  _pirbwpage
#ifdef INIT
= {(char *) &pirbwpage,sizeof(pirbwpage),GE_INT} 
#endif
;

EXTERN _export  _pircbnub
#ifdef INIT
= {(char *) &pircbnub,sizeof(pircbnub),GE_INT} 
#endif
;

EXTERN _export  _pircbval2
#ifdef INIT
= {(char *) &pircbval2,sizeof(pircbval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pircbval3
#ifdef INIT
= {(char *) &pircbval3,sizeof(pircbval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pircbval4
#ifdef INIT
= {(char *) &pircbval4,sizeof(pircbval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pircbval5
#ifdef INIT
= {(char *) &pircbval5,sizeof(pircbval5),GE_FLOAT} 
#endif
;

EXTERN _export  _pircbval6
#ifdef INIT
= {(char *) &pircbval6,sizeof(pircbval6),GE_FLOAT} 
#endif
;

EXTERN _export  _pipscoptnub
#ifdef INIT
= {(char *) &pipscoptnub,sizeof(pipscoptnub),GE_INT} 
#endif
;

EXTERN _export  _piflosup
#ifdef INIT
= {(char *) &piflosup,sizeof(piflosup),GE_INT} 
#endif
;

EXTERN _export  _piflanub
#ifdef INIT
= {(char *) &piflanub,sizeof(piflanub),GE_INT} 
#endif
;

EXTERN _export  _pivelnub
#ifdef INIT
= {(char *) &pivelnub,sizeof(pivelnub),GE_INT} 
#endif
;

EXTERN _export  _piprojnub
#ifdef INIT
= {(char *) &piprojnub,sizeof(piprojnub),GE_INT} 
#endif
;

EXTERN _export  _piaddinub
#ifdef INIT
= {(char *) &piaddinub,sizeof(piaddinub),GE_INT} 
#endif
;

EXTERN _export  _piflrcnub
#ifdef INIT
= {(char *) &piflrcnub,sizeof(piflrcnub),GE_INT} 
#endif
;

EXTERN _export  _piscran
#ifdef INIT
= {(char *) &piscran,sizeof(piscran),GE_INT} 
#endif
;

EXTERN _export  _pifovnub
#ifdef INIT
= {(char *) &pifovnub,sizeof(pifovnub),GE_INT} 
#endif
;

EXTERN _export  _pifovval2
#ifdef INIT
= {(char *) &pifovval2,sizeof(pifovval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pifovval3
#ifdef INIT
= {(char *) &pifovval3,sizeof(pifovval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pifovval4
#ifdef INIT
= {(char *) &pifovval4,sizeof(pifovval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pifovval5
#ifdef INIT
= {(char *) &pifovval5,sizeof(pifovval5),GE_FLOAT} 
#endif
;

EXTERN _export  _pifovval6
#ifdef INIT
= {(char *) &pifovval6,sizeof(pifovval6),GE_FLOAT} 
#endif
;

EXTERN _export  _piphasfovnub
#ifdef INIT
= {(char *) &piphasfovnub,sizeof(piphasfovnub),GE_INT} 
#endif
;

EXTERN _export  _pifreqfovnub
#ifdef INIT
= {(char *) &pifreqfovnub,sizeof(pifreqfovnub),GE_INT} 
#endif
;

EXTERN _export  _pistnub
#ifdef INIT
= {(char *) &pistnub,sizeof(pistnub),GE_INT} 
#endif
;

EXTERN _export  _pistval2
#ifdef INIT
= {(char *) &pistval2,sizeof(pistval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pistval3
#ifdef INIT
= {(char *) &pistval3,sizeof(pistval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pistval4
#ifdef INIT
= {(char *) &pistval4,sizeof(pistval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pistval5
#ifdef INIT
= {(char *) &pistval5,sizeof(pistval5),GE_FLOAT} 
#endif
;

EXTERN _export  _pistval6
#ifdef INIT
= {(char *) &pistval6,sizeof(pistval6),GE_FLOAT} 
#endif
;

EXTERN _export  _piisnub
#ifdef INIT
= {(char *) &piisnub,sizeof(piisnub),GE_INT} 
#endif
;

EXTERN _export  _piisil
#ifdef INIT
= {(char *) &piisil,sizeof(piisil),GE_INT} 
#endif
;

EXTERN _export  _piisval2
#ifdef INIT
= {(char *) &piisval2,sizeof(piisval2),GE_FLOAT} 
#endif
;

EXTERN _export  _piisval3
#ifdef INIT
= {(char *) &piisval3,sizeof(piisval3),GE_FLOAT} 
#endif
;

EXTERN _export  _piisval4
#ifdef INIT
= {(char *) &piisval4,sizeof(piisval4),GE_FLOAT} 
#endif
;

EXTERN _export  _piisval5
#ifdef INIT
= {(char *) &piisval5,sizeof(piisval5),GE_FLOAT} 
#endif
;

EXTERN _export  _piisval6
#ifdef INIT
= {(char *) &piisval6,sizeof(piisval6),GE_FLOAT} 
#endif
;

EXTERN _export  _pilocnub
#ifdef INIT
= {(char *) &pilocnub,sizeof(pilocnub),GE_INT} 
#endif
;

EXTERN _export  _pilocval2
#ifdef INIT
= {(char *) &pilocval2,sizeof(pilocval2),GE_INT} 
#endif
;

EXTERN _export  _pilocval3
#ifdef INIT
= {(char *) &pilocval3,sizeof(pilocval3),GE_INT} 
#endif
;

EXTERN _export  _pilocval4
#ifdef INIT
= {(char *) &pilocval4,sizeof(pilocval4),GE_INT} 
#endif
;

EXTERN _export  _pilocval5
#ifdef INIT
= {(char *) &pilocval5,sizeof(pilocval5),GE_INT} 
#endif
;

EXTERN _export  _pilocval6
#ifdef INIT
= {(char *) &pilocval6,sizeof(pilocval6),GE_INT} 
#endif
;

EXTERN _export  _piactim
#ifdef INIT
= {(char *) &piactim,sizeof(piactim),GE_INT} 
#endif
;

EXTERN _export  _piamnub
#ifdef INIT
= {(char *) &piamnub,sizeof(piamnub),GE_INT} 
#endif
;

EXTERN _export  _piamval1
#ifdef INIT
= {(char *) piamval1,sizeof(piamval1),GE_STRUCT} 
#endif
;

EXTERN _export  _piamval2
#ifdef INIT
= {(char *) piamval2,sizeof(piamval2),GE_STRUCT} 
#endif
;

EXTERN _export  _piamval3
#ifdef INIT
= {(char *) piamval3,sizeof(piamval3),GE_STRUCT} 
#endif
;

EXTERN _export  _piamval4
#ifdef INIT
= {(char *) piamval4,sizeof(piamval4),GE_STRUCT} 
#endif
;

EXTERN _export  _piamval5
#ifdef INIT
= {(char *) piamval5,sizeof(piamval5),GE_STRUCT} 
#endif
;

EXTERN _export  _piamval6
#ifdef INIT
= {(char *) piamval6,sizeof(piamval6),GE_STRUCT} 
#endif
;

EXTERN _export  _piyresnub
#ifdef INIT
= {(char *) &piyresnub,sizeof(piyresnub),GE_INT} 
#endif
;

EXTERN _export  _piyresval2
#ifdef INIT
= {(char *) &piyresval2,sizeof(piyresval2),GE_INT} 
#endif
;

EXTERN _export  _piyresval3
#ifdef INIT
= {(char *) &piyresval3,sizeof(piyresval3),GE_INT} 
#endif
;

EXTERN _export  _piyresval4
#ifdef INIT
= {(char *) &piyresval4,sizeof(piyresval4),GE_INT} 
#endif
;

EXTERN _export  _piyresval5
#ifdef INIT
= {(char *) &piyresval5,sizeof(piyresval5),GE_INT} 
#endif
;

EXTERN _export  _piyresval6
#ifdef INIT
= {(char *) &piyresval6,sizeof(piyresval6),GE_INT} 
#endif
;

EXTERN _export  _pixresnub
#ifdef INIT
= {(char *) &pixresnub,sizeof(pixresnub),GE_INT} 
#endif
;

EXTERN _export  _pixresval2
#ifdef INIT
= {(char *) &pixresval2,sizeof(pixresval2),GE_INT} 
#endif
;

EXTERN _export  _pixresval3
#ifdef INIT
= {(char *) &pixresval3,sizeof(pixresval3),GE_INT} 
#endif
;

EXTERN _export  _pixresval4
#ifdef INIT
= {(char *) &pixresval4,sizeof(pixresval4),GE_INT} 
#endif
;

EXTERN _export  _pixresval5
#ifdef INIT
= {(char *) &pixresval5,sizeof(pixresval5),GE_INT} 
#endif
;

EXTERN _export  _pixresval6
#ifdef INIT
= {(char *) &pixresval6,sizeof(pixresval6),GE_INT} 
#endif
;

EXTERN _export  _pinexnub
#ifdef INIT
= {(char *) &pinexnub,sizeof(pinexnub),GE_INT} 
#endif
;

EXTERN _export  _pinexval2
#ifdef INIT
= {(char *) &pinexval2,sizeof(pinexval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pinexval3
#ifdef INIT
= {(char *) &pinexval3,sizeof(pinexval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pinexval4
#ifdef INIT
= {(char *) &pinexval4,sizeof(pinexval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pinexval5
#ifdef INIT
= {(char *) &pinexval5,sizeof(pinexval5),GE_FLOAT} 
#endif
;

EXTERN _export  _pinexval6
#ifdef INIT
= {(char *) &pinexval6,sizeof(pinexval6),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim1
#ifdef INIT
= {(char *) &pisctim1,sizeof(pisctim1),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim2
#ifdef INIT
= {(char *) &pisctim2,sizeof(pisctim2),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim3
#ifdef INIT
= {(char *) &pisctim3,sizeof(pisctim3),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim4
#ifdef INIT
= {(char *) &pisctim4,sizeof(pisctim4),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim5
#ifdef INIT
= {(char *) &pisctim5,sizeof(pisctim5),GE_FLOAT} 
#endif
;

EXTERN _export  _pisctim6
#ifdef INIT
= {(char *) &pisctim6,sizeof(pisctim6),GE_FLOAT} 
#endif
;

EXTERN _export  _pipautype
#ifdef INIT
= {(char *) &pipautype,sizeof(pipautype),GE_INT} 
#endif
;

EXTERN _export  _pipaunub
#ifdef INIT
= {(char *) &pipaunub,sizeof(pipaunub),GE_INT} 
#endif
;

EXTERN _export  _pipauval2
#ifdef INIT
= {(char *) &pipauval2,sizeof(pipauval2),GE_INT} 
#endif
;

EXTERN _export  _pipauval3
#ifdef INIT
= {(char *) &pipauval3,sizeof(pipauval3),GE_INT} 
#endif
;

EXTERN _export  _pipauval4
#ifdef INIT
= {(char *) &pipauval4,sizeof(pipauval4),GE_INT} 
#endif
;

EXTERN _export  _pipauval5
#ifdef INIT
= {(char *) &pipauval5,sizeof(pipauval5),GE_INT} 
#endif
;

EXTERN _export  _pipauval6
#ifdef INIT
= {(char *) &pipauval6,sizeof(pipauval6),GE_INT} 
#endif
;

EXTERN _export  _pircb2nub
#ifdef INIT
= {(char *) &pircb2nub,sizeof(pircb2nub),GE_INT} 
#endif
;

EXTERN _export  _pircb2val2
#ifdef INIT
= {(char *) &pircb2val2,sizeof(pircb2val2),GE_FLOAT} 
#endif
;

EXTERN _export  _pircb2val3
#ifdef INIT
= {(char *) &pircb2val3,sizeof(pircb2val3),GE_FLOAT} 
#endif
;

EXTERN _export  _pircb2val4
#ifdef INIT
= {(char *) &pircb2val4,sizeof(pircb2val4),GE_FLOAT} 
#endif
;

EXTERN _export  _pircb2val5
#ifdef INIT
= {(char *) &pircb2val5,sizeof(pircb2val5),GE_FLOAT} 
#endif
;

EXTERN _export  _pircb2val6
#ifdef INIT
= {(char *) &pircb2val6,sizeof(pircb2val6),GE_FLOAT} 
#endif
;

EXTERN _export  _pisetup
#ifdef INIT
= {(char *) &pisetup,sizeof(pisetup),GE_INT} 
#endif
;

EXTERN _export  _pihrepnub
#ifdef INIT
= {(char *) &pihrepnub,sizeof(pihrepnub),GE_INT} 
#endif
;

EXTERN _export  _pihrepval2
#ifdef INIT
= {(char *) &pihrepval2,sizeof(pihrepval2),GE_INT} 
#endif
;

EXTERN _export  _pihrepval3
#ifdef INIT
= {(char *) &pihrepval3,sizeof(pihrepval3),GE_INT} 
#endif
;

EXTERN _export  _pihrepval4
#ifdef INIT
= {(char *) &pihrepval4,sizeof(pihrepval4),GE_INT} 
#endif
;

EXTERN _export  _pihrepval5
#ifdef INIT
= {(char *) &pihrepval5,sizeof(pihrepval5),GE_INT} 
#endif
;

EXTERN _export  _pihrepval6
#ifdef INIT
= {(char *) &pihrepval6,sizeof(pihrepval6),GE_INT} 
#endif
;

EXTERN _export  _pite2type
#ifdef INIT
= {(char *) &pite2type,sizeof(pite2type),GE_INT} 
#endif
;

EXTERN _export  _pifsefcnub
#ifdef INIT
= {(char *) &pifsefcnub,sizeof(pifsefcnub),GE_INT} 
#endif
;

EXTERN _export  _pideffcaxis
#ifdef INIT
= {(char *) &pideffcaxis,sizeof(pideffcaxis),GE_INT} 
#endif
;

EXTERN _export  _pislqnub
#ifdef INIT
= {(char *) &pislqnub,sizeof(pislqnub),GE_INT} 
#endif
;

EXTERN _export  _pislqval2
#ifdef INIT
= {(char *) &pislqval2,sizeof(pislqval2),GE_INT} 
#endif
;

EXTERN _export  _pislqval3
#ifdef INIT
= {(char *) &pislqval3,sizeof(pislqval3),GE_INT} 
#endif
;

EXTERN _export  _pislqval4
#ifdef INIT
= {(char *) &pislqval4,sizeof(pislqval4),GE_INT} 
#endif
;

EXTERN _export  _pidefslq
#ifdef INIT
= {(char *) &pidefslq,sizeof(pidefslq),GE_INT} 
#endif
;

EXTERN _export  _pislqval5
#ifdef INIT
= {(char *) &pislqval5,sizeof(pislqval5),GE_INT} 
#endif
;

EXTERN _export  _pirampnub
#ifdef INIT
= {(char *) &pirampnub,sizeof(pirampnub),GE_INT} 
#endif
;

EXTERN _export  _pideframp
#ifdef INIT
= {(char *) &pideframp,sizeof(pideframp),GE_INT} 
#endif
;

EXTERN _export  _pipctovl
#ifdef INIT
= {(char *) &pipctovl,sizeof(pipctovl),GE_INT} 
#endif
;

EXTERN _export  _pidefovl
#ifdef INIT
= {(char *) &pidefovl,sizeof(pidefovl),GE_INT} 
#endif
;

EXTERN _export  _piovlnub
#ifdef INIT
= {(char *) &piovlnub,sizeof(piovlnub),GE_INT} 
#endif
;

EXTERN _export  _pitdel1nub
#ifdef INIT
= {(char *) &pitdel1nub,sizeof(pitdel1nub),GE_INT} 
#endif
;

EXTERN _export  _pitrigwinnub
#ifdef INIT
= {(char *) &pitrigwinnub,sizeof(pitrigwinnub),GE_INT} 
#endif
;

EXTERN _export  _pitseqnub
#ifdef INIT
= {(char *) &pitseqnub,sizeof(pitseqnub),GE_INT} 
#endif
;

EXTERN _export  _piphasenub
#ifdef INIT
= {(char *) &piphasenub,sizeof(piphasenub),GE_INT} 
#endif
;

EXTERN _export  _piphslnub
#ifdef INIT
= {(char *) &piphslnub,sizeof(piphslnub),GE_INT} 
#endif
;

EXTERN _export  _piviewseg
#ifdef INIT
= {(char *) &piviewseg,sizeof(piviewseg),GE_INT} 
#endif
;

EXTERN _export  _psd_filt_spec
#ifdef INIT
= {(char *) psd_filt_spec,sizeof(psd_filt_spec),GE_STRUCT} 
#endif
;

EXTERN _export  _pivascop
#ifdef INIT
= {(char *) &pivascop,sizeof(pivascop),GE_INT} 
#endif
;

EXTERN _export  _pimultigroup
#ifdef INIT
= {(char *) &pimultigroup,sizeof(pimultigroup),GE_INT} 
#endif
;

EXTERN _export  _pimultislab
#ifdef INIT
= {(char *) &pimultislab,sizeof(pimultislab),GE_INT} 
#endif
;

EXTERN _export  _pidefproj
#ifdef INIT
= {(char *) &pidefproj,sizeof(pidefproj),GE_INT} 
#endif
;

EXTERN _export  _pidefflax
#ifdef INIT
= {(char *) &pidefflax,sizeof(pidefflax),GE_INT} 
#endif
;

EXTERN _export  _pidefaddimg
#ifdef INIT
= {(char *) &pidefaddimg,sizeof(pidefaddimg),GE_INT} 
#endif
;

EXTERN _export  _pidefflrc
#ifdef INIT
= {(char *) &pidefflrc,sizeof(pidefflrc),GE_INT} 
#endif
;

EXTERN _export  _eg_sat_rot
#ifdef INIT
= {(char *) eg_sat_rot,sizeof(eg_sat_rot),GE_STRUCT} 
#endif
;

EXTERN _export  _pivpsdef
#ifdef INIT
= {(char *) &pivpsdef,sizeof(pivpsdef),GE_INT} 
#endif
;

EXTERN _export  _pidefrbw
#ifdef INIT
= {(char *) &pidefrbw,sizeof(pidefrbw),GE_INT} 
#endif
;

EXTERN _export  _pigradcoil
#ifdef INIT
= {(char *) &pigradcoil,sizeof(pigradcoil),GE_INT} 
#endif
;

EXTERN _export  _dfscale
#ifdef INIT
= {(char *) &dfscale,sizeof(dfscale),GE_FLOAT} 
#endif
;

EXTERN _export  _pipscdef
#ifdef INIT
= {(char *) &pipscdef,sizeof(pipscdef),GE_INT} 
#endif
;

EXTERN _export  _avminrttseq
#ifdef INIT
= {(char *) &avminrttseq,sizeof(avminrttseq),GE_INT} 
#endif
;

EXTERN _export  _pitetr
#ifdef INIT
= {(char *) &pitetr,sizeof(pitetr),GE_INT} 
#endif
;

EXTERN _export  _pirtrigwinnub
#ifdef INIT
= {(char *) &pirtrigwinnub,sizeof(pirtrigwinnub),GE_INT} 
#endif
;

EXTERN _export  _pirtwindefval
#ifdef INIT
= {(char *) &pirtwindefval,sizeof(pirtwindefval),GE_INT} 
#endif
;

EXTERN _export  _pirtwinval2
#ifdef INIT
= {(char *) &pirtwinval2,sizeof(pirtwinval2),GE_INT} 
#endif
;

EXTERN _export  _pirtwinval3
#ifdef INIT
= {(char *) &pirtwinval3,sizeof(pirtwinval3),GE_INT} 
#endif
;

EXTERN _export  _pirtwinval4
#ifdef INIT
= {(char *) &pirtwinval4,sizeof(pirtwinval4),GE_INT} 
#endif
;

EXTERN _export  _pirtwinval5
#ifdef INIT
= {(char *) &pirtwinval5,sizeof(pirtwinval5),GE_INT} 
#endif
;

EXTERN _export  _pirtwinval6
#ifdef INIT
= {(char *) &pirtwinval6,sizeof(pirtwinval6),GE_INT} 
#endif
;

EXTERN _export  _pirtseqnub
#ifdef INIT
= {(char *) &pirtseqnub,sizeof(pirtseqnub),GE_INT} 
#endif
;

EXTERN _export  _pirttseq
#ifdef INIT
= {(char *) &pirttseq,sizeof(pirttseq),GE_INT} 
#endif
;

EXTERN _export  _pirtait
#ifdef INIT
= {(char *) &pirtait,sizeof(pirtait),GE_INT} 
#endif
;

EXTERN _export  _pirtetr
#ifdef INIT
= {(char *) &pirtetr,sizeof(pirtetr),GE_INT} 
#endif
;

EXTERN _export  _pirtrepnub
#ifdef INIT
= {(char *) &pirtrepnub,sizeof(pirtrepnub),GE_INT} 
#endif
;

EXTERN _export  _pirtrepval2
#ifdef INIT
= {(char *) &pirtrepval2,sizeof(pirtrepval2),GE_INT} 
#endif
;

EXTERN _export  _pirtrepval3
#ifdef INIT
= {(char *) &pirtrepval3,sizeof(pirtrepval3),GE_INT} 
#endif
;

EXTERN _export  _pirtrepval4
#ifdef INIT
= {(char *) &pirtrepval4,sizeof(pirtrepval4),GE_INT} 
#endif
;

EXTERN _export  _pirtrepval5
#ifdef INIT
= {(char *) &pirtrepval5,sizeof(pirtrepval5),GE_INT} 
#endif
;

EXTERN _export  _pirtrepval6
#ifdef INIT
= {(char *) &pirtrepval6,sizeof(pirtrepval6),GE_INT} 
#endif
;

EXTERN _export  _pirtpointnub
#ifdef INIT
= {(char *) &pirtpointnub,sizeof(pirtpointnub),GE_INT} 
#endif
;

EXTERN _export  _pirtpointval2
#ifdef INIT
= {(char *) &pirtpointval2,sizeof(pirtpointval2),GE_INT} 
#endif
;

EXTERN _export  _pirtpointval3
#ifdef INIT
= {(char *) &pirtpointval3,sizeof(pirtpointval3),GE_INT} 
#endif
;

EXTERN _export  _pirtpointval4
#ifdef INIT
= {(char *) &pirtpointval4,sizeof(pirtpointval4),GE_INT} 
#endif
;

EXTERN _export  _pirtpointval5
#ifdef INIT
= {(char *) &pirtpointval5,sizeof(pirtpointval5),GE_INT} 
#endif
;

EXTERN _export  _pirtpointval6
#ifdef INIT
= {(char *) &pirtpointval6,sizeof(pirtpointval6),GE_INT} 
#endif
;

EXTERN _export  _pishotnub
#ifdef INIT
= {(char *) &pishotnub,sizeof(pishotnub),GE_INT} 
#endif
;

EXTERN _export  _pishotval2
#ifdef INIT
= {(char *) &pishotval2,sizeof(pishotval2),GE_INT} 
#endif
;

EXTERN _export  _pishotval3
#ifdef INIT
= {(char *) &pishotval3,sizeof(pishotval3),GE_INT} 
#endif
;

EXTERN _export  _pishotval4
#ifdef INIT
= {(char *) &pishotval4,sizeof(pishotval4),GE_INT} 
#endif
;

EXTERN _export  _pishotval5
#ifdef INIT
= {(char *) &pishotval5,sizeof(pishotval5),GE_INT} 
#endif
;

EXTERN _export  _pishotval6
#ifdef INIT
= {(char *) &pishotval6,sizeof(pishotval6),GE_INT} 
#endif
;

EXTERN _export  _piphasfovval2
#ifdef INIT
= {(char *) &piphasfovval2,sizeof(piphasfovval2),GE_FLOAT} 
#endif
;

EXTERN _export  _piphasfovval3
#ifdef INIT
= {(char *) &piphasfovval3,sizeof(piphasfovval3),GE_FLOAT} 
#endif
;

EXTERN _export  _piphasfovval4
#ifdef INIT
= {(char *) &piphasfovval4,sizeof(piphasfovval4),GE_FLOAT} 
#endif
;

EXTERN _export  _piphasfovval5
#ifdef INIT
= {(char *) &piphasfovval5,sizeof(piphasfovval5),GE_FLOAT} 
#endif
;

EXTERN _export  _piphasfovval6
#ifdef INIT
= {(char *) &piphasfovval6,sizeof(piphasfovval6),GE_FLOAT} 
#endif
;

EXTERN _export  _rec_mode
#ifdef INIT
= {(char *) &rec_mode,sizeof(rec_mode),GE_INT} 
#endif
;

EXTERN _export  _opnewgeo
#ifdef INIT
= {(char *) &opnewgeo,sizeof(opnewgeo),GE_INT} 
#endif
;

EXTERN _export  _simulation
#ifdef INIT
= {(char *) &simulation,sizeof(simulation),GE_INT} 
#endif
;

EXTERN _export  _cflinfrq
#ifdef INIT
= {(char *) &cflinfrq,sizeof(cflinfrq),GE_FLOAT} 
#endif
;

EXTERN _export  _cffield
#ifdef INIT
= {(char *) &cffield,sizeof(cffield),GE_FLOAT} 
#endif
;

EXTERN _export  _cfhpdl
#ifdef INIT
= {(char *) &cfhpdl,sizeof(cfhpdl),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbpdl
#ifdef INIT
= {(char *) &cfbpdl,sizeof(cfbpdl),GE_FLOAT} 
#endif
;

EXTERN _export  _cfhpsl
#ifdef INIT
= {(char *) &cfhpsl,sizeof(cfhpsl),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbpsl
#ifdef INIT
= {(char *) &cfbpsl,sizeof(cfbpsl),GE_FLOAT} 
#endif
;

EXTERN _export  _cfhpv
#ifdef INIT
= {(char *) &cfhpv,sizeof(cfhpv),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbpv
#ifdef INIT
= {(char *) &cfbpv,sizeof(cfbpv),GE_FLOAT} 
#endif
;

EXTERN _export  _cfhqpc
#ifdef INIT
= {(char *) &cfhqpc,sizeof(cfhqpc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbqpc
#ifdef INIT
= {(char *) &cfbqpc,sizeof(cfbqpc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfhllr
#ifdef INIT
= {(char *) &cfhllr,sizeof(cfhllr),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbllr
#ifdef INIT
= {(char *) &cfbllr,sizeof(cfbllr),GE_FLOAT} 
#endif
;

EXTERN _export  _cfloss
#ifdef INIT
= {(char *) &cfloss,sizeof(cfloss),GE_FLOAT} 
#endif
;

EXTERN _export  _cfbwmin
#ifdef INIT
= {(char *) &cfbwmin,sizeof(cfbwmin),GE_INT} 
#endif
;

EXTERN _export  _cfbwmin1
#ifdef INIT
= {(char *) &cfbwmin1,sizeof(cfbwmin1),GE_INT} 
#endif
;

EXTERN _export  _cfmaxave
#ifdef INIT
= {(char *) &cfmaxave,sizeof(cfmaxave),GE_FLOAT} 
#endif
;

EXTERN _export  _cfmaxpeak
#ifdef INIT
= {(char *) &cfmaxpeak,sizeof(cfmaxpeak),GE_FLOAT} 
#endif
;

EXTERN _export  _cftpssize
#ifdef INIT
= {(char *) &cftpssize,sizeof(cftpssize),GE_INT} 
#endif
;

EXTERN _export  _cccal
#ifdef INIT
= {(char *) &cccal,sizeof(cccal),GE_FLOAT} 
#endif
;

EXTERN _export  _ccjcoil
#ifdef INIT
= {(char *) &ccjcoil,sizeof(ccjcoil),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxfull
#ifdef INIT
= {(char *) &cfxfull,sizeof(cfxfull),GE_INT} 
#endif
;

EXTERN _export  _cfyfull
#ifdef INIT
= {(char *) &cfyfull,sizeof(cfyfull),GE_INT} 
#endif
;

EXTERN _export  _cfzfull
#ifdef INIT
= {(char *) &cfzfull,sizeof(cfzfull),GE_INT} 
#endif
;

EXTERN _export  _cfdbmax
#ifdef INIT
= {(char *) &cfdbmax,sizeof(cfdbmax),GE_INT} 
#endif
;

EXTERN _export  _cfbbmod
#ifdef INIT
= {(char *) &cfbbmod,sizeof(cfbbmod),GE_INT} 
#endif
;

EXTERN _export  _cftrnew
#ifdef INIT
= {(char *) &cftrnew,sizeof(cftrnew),GE_INT} 
#endif
;

EXTERN _export  _cfrecvst
#ifdef INIT
= {(char *) &cfrecvst,sizeof(cfrecvst),GE_INT} 
#endif
;

EXTERN _export  _cfrecvend
#ifdef INIT
= {(char *) &cfrecvend,sizeof(cfrecvend),GE_INT} 
#endif
;

EXTERN _export  _cfgradamp
#ifdef INIT
= {(char *) &cfgradamp,sizeof(cfgradamp),GE_INT} 
#endif
;

EXTERN _export  _cfhtdel
#ifdef INIT
= {(char *) &cfhtdel,sizeof(cfhtdel),GE_INT} 
#endif
;

EXTERN _export  _cfcftdel
#ifdef INIT
= {(char *) &cfcftdel,sizeof(cfcftdel),GE_INT} 
#endif
;

EXTERN _export  _cfcgain
#ifdef INIT
= {(char *) &cfcgain,sizeof(cfcgain),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcoilatten
#ifdef INIT
= {(char *) &cfcoilatten,sizeof(cfcoilatten),GE_INT} 
#endif
;

EXTERN _export  _cfrfrapb
#ifdef INIT
= {(char *) &cfrfrapb,sizeof(cfrfrapb),GE_INT} 
#endif
;

EXTERN _export  _cfrfraph
#ifdef INIT
= {(char *) &cfrfraph,sizeof(cfrfraph),GE_INT} 
#endif
;

EXTERN _export  _cfrfmapb
#ifdef INIT
= {(char *) &cfrfmapb,sizeof(cfrfmapb),GE_INT} 
#endif
;

EXTERN _export  _cfrfmaph
#ifdef INIT
= {(char *) &cfrfmaph,sizeof(cfrfmaph),GE_INT} 
#endif
;

EXTERN _export  _cfrfmpeb
#ifdef INIT
= {(char *) &cfrfmpeb,sizeof(cfrfmpeb),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrfmpeh
#ifdef INIT
= {(char *) &cfrfmpeh,sizeof(cfrfmpeh),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrfmpwb
#ifdef INIT
= {(char *) &cfrfmpwb,sizeof(cfrfmpwb),GE_INT} 
#endif
;

EXTERN _export  _cfrfmpwh
#ifdef INIT
= {(char *) &cfrfmpwh,sizeof(cfrfmpwh),GE_INT} 
#endif
;

EXTERN _export  _cfrfmdcb
#ifdef INIT
= {(char *) &cfrfmdcb,sizeof(cfrfmdcb),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrfmdch
#ifdef INIT
= {(char *) &cfrfmdch,sizeof(cfrfmdch),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrfamptyp
#ifdef INIT
= {(char *) &cfrfamptyp,sizeof(cfrfamptyp),GE_INT} 
#endif
;

EXTERN _export  _cfpwrmontyp
#ifdef INIT
= {(char *) &cfpwrmontyp,sizeof(cfpwrmontyp),GE_INT} 
#endif
;

EXTERN _export  _cfpsdgraddly
#ifdef INIT
= {(char *) &cfpsdgraddly,sizeof(cfpsdgraddly),GE_INT} 
#endif
;

EXTERN _export  _cfpsdrfdly
#ifdef INIT
= {(char *) &cfpsdrfdly,sizeof(cfpsdrfdly),GE_INT} 
#endif
;

EXTERN _export  _cfxrdelay
#ifdef INIT
= {(char *) &cfxrdelay,sizeof(cfxrdelay),GE_INT} 
#endif
;

EXTERN _export  _cfyrdelay
#ifdef INIT
= {(char *) &cfyrdelay,sizeof(cfyrdelay),GE_INT} 
#endif
;

EXTERN _export  _cfzrdelay
#ifdef INIT
= {(char *) &cfzrdelay,sizeof(cfzrdelay),GE_INT} 
#endif
;

EXTERN _export  _piphasfovnub2
#ifdef INIT
= {(char *) &piphasfovnub2,sizeof(piphasfovnub2),GE_INT} 
#endif
;

EXTERN _export  _piswapfc
#ifdef INIT
= {(char *) &piswapfc,sizeof(piswapfc),GE_INT} 
#endif
;

EXTERN _export  _pidltime
#ifdef INIT
= {(char *) &pidltime,sizeof(pidltime),GE_INT} 
#endif
;

EXTERN _export  _piphasfovval1
#ifdef INIT
= {(char *) &piphasfovval1,sizeof(piphasfovval1),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcoilshld
#ifdef INIT
= {(char *) &cfcoilshld,sizeof(cfcoilshld),GE_INT} 
#endif
;

EXTERN _export  _cfrfunblank
#ifdef INIT
= {(char *) &cfrfunblank,sizeof(cfrfunblank),GE_INT} 
#endif
;

EXTERN _export  _cfrmp2xfs
#ifdef INIT
= {(char *) &cfrmp2xfs,sizeof(cfrmp2xfs),GE_INT} 
#endif
;

EXTERN _export  _cffall2x0
#ifdef INIT
= {(char *) &cffall2x0,sizeof(cffall2x0),GE_INT} 
#endif
;

EXTERN _export  _cfxfs
#ifdef INIT
= {(char *) &cfxfs,sizeof(cfxfs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxfa
#ifdef INIT
= {(char *) &cfxfa,sizeof(cfxfa),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxcc
#ifdef INIT
= {(char *) &cfxcc,sizeof(cfxcc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxbeta
#ifdef INIT
= {(char *) &cfxbeta,sizeof(cfxbeta),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrmp2yfs
#ifdef INIT
= {(char *) &cfrmp2yfs,sizeof(cfrmp2yfs),GE_INT} 
#endif
;

EXTERN _export  _cffall2y0
#ifdef INIT
= {(char *) &cffall2y0,sizeof(cffall2y0),GE_INT} 
#endif
;

EXTERN _export  _cfyfs
#ifdef INIT
= {(char *) &cfyfs,sizeof(cfyfs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyfa
#ifdef INIT
= {(char *) &cfyfa,sizeof(cfyfa),GE_FLOAT} 
#endif
;

EXTERN _export  _cfycc
#ifdef INIT
= {(char *) &cfycc,sizeof(cfycc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfybeta
#ifdef INIT
= {(char *) &cfybeta,sizeof(cfybeta),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrmp2zfs
#ifdef INIT
= {(char *) &cfrmp2zfs,sizeof(cfrmp2zfs),GE_INT} 
#endif
;

EXTERN _export  _cffall2z0
#ifdef INIT
= {(char *) &cffall2z0,sizeof(cffall2z0),GE_INT} 
#endif
;

EXTERN _export  _cfzfs
#ifdef INIT
= {(char *) &cfzfs,sizeof(cfzfs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzfa
#ifdef INIT
= {(char *) &cfzfa,sizeof(cfzfa),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzcc
#ifdef INIT
= {(char *) &cfzcc,sizeof(cfzcc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzbeta
#ifdef INIT
= {(char *) &cfzbeta,sizeof(cfzbeta),GE_FLOAT} 
#endif
;

EXTERN _export  _cffrecvst
#ifdef INIT
= {(char *) &cffrecvst,sizeof(cffrecvst),GE_INT} 
#endif
;

EXTERN _export  _cffrecvend
#ifdef INIT
= {(char *) &cffrecvend,sizeof(cffrecvend),GE_INT} 
#endif
;

EXTERN _export  _cffrecvnum
#ifdef INIT
= {(char *) &cffrecvnum,sizeof(cffrecvnum),GE_INT} 
#endif
;

EXTERN _export  _cfxgram
#ifdef INIT
= {(char *) &cfxgram,sizeof(cfxgram),GE_INT} 
#endif
;

EXTERN _export  _cfygram
#ifdef INIT
= {(char *) &cfygram,sizeof(cfygram),GE_INT} 
#endif
;

EXTERN _export  _cfzgram
#ifdef INIT
= {(char *) &cfzgram,sizeof(cfzgram),GE_INT} 
#endif
;

EXTERN _export  _cfxasm
#ifdef INIT
= {(char *) &cfxasm,sizeof(cfxasm),GE_INT} 
#endif
;

EXTERN _export  _cfyasm
#ifdef INIT
= {(char *) &cfyasm,sizeof(cfyasm),GE_INT} 
#endif
;

EXTERN _export  _cfzasm
#ifdef INIT
= {(char *) &cfzasm,sizeof(cfzasm),GE_INT} 
#endif
;

EXTERN _export  _cfxgasm
#ifdef INIT
= {(char *) &cfxgasm,sizeof(cfxgasm),GE_INT} 
#endif
;

EXTERN _export  _cfygasm
#ifdef INIT
= {(char *) &cfygasm,sizeof(cfygasm),GE_INT} 
#endif
;

EXTERN _export  _cfzgasm
#ifdef INIT
= {(char *) &cfzgasm,sizeof(cfzgasm),GE_INT} 
#endif
;

EXTERN _export  _cfxseries
#ifdef INIT
= {(char *) &cfxseries,sizeof(cfxseries),GE_INT} 
#endif
;

EXTERN _export  _cfyseries
#ifdef INIT
= {(char *) &cfyseries,sizeof(cfyseries),GE_INT} 
#endif
;

EXTERN _export  _cfzseries
#ifdef INIT
= {(char *) &cfzseries,sizeof(cfzseries),GE_INT} 
#endif
;

EXTERN _export  _cfxnumpower
#ifdef INIT
= {(char *) &cfxnumpower,sizeof(cfxnumpower),GE_INT} 
#endif
;

EXTERN _export  _cfynumpower
#ifdef INIT
= {(char *) &cfynumpower,sizeof(cfynumpower),GE_INT} 
#endif
;

EXTERN _export  _cfznumpower
#ifdef INIT
= {(char *) &cfznumpower,sizeof(cfznumpower),GE_INT} 
#endif
;

EXTERN _export  _cftuning
#ifdef INIT
= {(char *) &cftuning,sizeof(cftuning),GE_INT} 
#endif
;

EXTERN _export  _cfrealtime
#ifdef INIT
= {(char *) &cfrealtime,sizeof(cfrealtime),GE_INT} 
#endif
;

EXTERN _export  _cfcompress
#ifdef INIT
= {(char *) &cfcompress,sizeof(cfcompress),GE_INT} 
#endif
;

EXTERN _export  _cfdbdtts
#ifdef INIT
= {(char *) &cfdbdtts,sizeof(cfdbdtts),GE_FLOAT} 
#endif
;

EXTERN _export  _cfdbdtper
#ifdef INIT
= {(char *) &cfdbdtper,sizeof(cfdbdtper),GE_FLOAT} 
#endif
;

EXTERN _export  _pidbdtts
#ifdef INIT
= {(char *) &pidbdtts,sizeof(pidbdtts),GE_FLOAT} 
#endif
;

EXTERN _export  _pidbdtper
#ifdef INIT
= {(char *) &pidbdtper,sizeof(pidbdtper),GE_FLOAT} 
#endif
;

EXTERN _export  _cfgcoiltype
#ifdef INIT
= {(char *) &cfgcoiltype,sizeof(cfgcoiltype),GE_INT} 
#endif
;

EXTERN _export  _cfsrmode
#ifdef INIT
= {(char *) &cfsrmode,sizeof(cfsrmode),GE_INT} 
#endif
;

EXTERN _export  _cfgpeakirms
#ifdef INIT
= {(char *) &cfgpeakirms,sizeof(cfgpeakirms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfgcontirms
#ifdef INIT
= {(char *) &cfgcontirms,sizeof(cfgcontirms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfgburstime
#ifdef INIT
= {(char *) &cfgburstime,sizeof(cfgburstime),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxirms
#ifdef INIT
= {(char *) &cfxirms,sizeof(cfxirms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyirms
#ifdef INIT
= {(char *) &cfyirms,sizeof(cfyirms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzirms
#ifdef INIT
= {(char *) &cfzirms,sizeof(cfzirms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxipeak
#ifdef INIT
= {(char *) &cfxipeak,sizeof(cfxipeak),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyipeak
#ifdef INIT
= {(char *) &cfyipeak,sizeof(cfyipeak),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzipeak
#ifdef INIT
= {(char *) &cfzipeak,sizeof(cfzipeak),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxamptran
#ifdef INIT
= {(char *) &cfxamptran,sizeof(cfxamptran),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyamptran
#ifdef INIT
= {(char *) &cfyamptran,sizeof(cfyamptran),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzamptran
#ifdef INIT
= {(char *) &cfzamptran,sizeof(cfzamptran),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxiavrgabs
#ifdef INIT
= {(char *) &cfxiavrgabs,sizeof(cfxiavrgabs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyiavrgabs
#ifdef INIT
= {(char *) &cfyiavrgabs,sizeof(cfyiavrgabs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfziavrgabs
#ifdef INIT
= {(char *) &cfziavrgabs,sizeof(cfziavrgabs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxirmspos
#ifdef INIT
= {(char *) &cfxirmspos,sizeof(cfxirmspos),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyirmspos
#ifdef INIT
= {(char *) &cfyirmspos,sizeof(cfyirmspos),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzirmspos
#ifdef INIT
= {(char *) &cfzirmspos,sizeof(cfzirmspos),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxirmsneg
#ifdef INIT
= {(char *) &cfxirmsneg,sizeof(cfxirmsneg),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyirmsneg
#ifdef INIT
= {(char *) &cfyirmsneg,sizeof(cfyirmsneg),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzirmsneg
#ifdef INIT
= {(char *) &cfzirmsneg,sizeof(cfzirmsneg),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxpwmdc
#ifdef INIT
= {(char *) &cfxpwmdc,sizeof(cfxpwmdc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfypwmdc
#ifdef INIT
= {(char *) &cfypwmdc,sizeof(cfypwmdc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzpwmdc
#ifdef INIT
= {(char *) &cfzpwmdc,sizeof(cfzpwmdc),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrmp2xfsfw
#ifdef INIT
= {(char *) &cfrmp2xfsfw,sizeof(cfrmp2xfsfw),GE_INT} 
#endif
;

EXTERN _export  _cfrmp2yfsfw
#ifdef INIT
= {(char *) &cfrmp2yfsfw,sizeof(cfrmp2yfsfw),GE_INT} 
#endif
;

EXTERN _export  _cfrmp2zfsfw
#ifdef INIT
= {(char *) &cfrmp2zfsfw,sizeof(cfrmp2zfsfw),GE_INT} 
#endif
;

EXTERN _export  _cffall2x0fw
#ifdef INIT
= {(char *) &cffall2x0fw,sizeof(cffall2x0fw),GE_INT} 
#endif
;

EXTERN _export  _cffall2y0fw
#ifdef INIT
= {(char *) &cffall2y0fw,sizeof(cffall2y0fw),GE_INT} 
#endif
;

EXTERN _export  _cffall2z0fw
#ifdef INIT
= {(char *) &cffall2z0fw,sizeof(cffall2z0fw),GE_INT} 
#endif
;

EXTERN _export  _cfmaxb1
#ifdef INIT
= {(char *) &cfmaxb1,sizeof(cfmaxb1),GE_FLOAT} 
#endif
;

EXTERN _export  _cfmaxb1sqrd
#ifdef INIT
= {(char *) &cfmaxb1sqrd,sizeof(cfmaxb1sqrd),GE_FLOAT} 
#endif
;

EXTERN _export  _cfmaxb1rms
#ifdef INIT
= {(char *) &cfmaxb1rms,sizeof(cfmaxb1rms),GE_FLOAT} 
#endif
;

EXTERN _export  _cfdbdtdx
#ifdef INIT
= {(char *) &cfdbdtdx,sizeof(cfdbdtdx),GE_FLOAT} 
#endif
;

EXTERN _export  _cfdbdtdy
#ifdef INIT
= {(char *) &cfdbdtdy,sizeof(cfdbdtdy),GE_FLOAT} 
#endif
;

EXTERN _export  _cfdbdtdz
#ifdef INIT
= {(char *) &cfdbdtdz,sizeof(cfdbdtdz),GE_FLOAT} 
#endif
;

EXTERN _export  _sigrammode
#ifdef INIT
= {(char *) &sigrammode,sizeof(sigrammode),GE_INT} 
#endif
;

EXTERN _export  _cfsrmodeconv
#ifdef INIT
= {(char *) &cfsrmodeconv,sizeof(cfsrmodeconv),GE_FLOAT} 
#endif
;

EXTERN _export  _cfsrmodeact
#ifdef INIT
= {(char *) &cfsrmodeact,sizeof(cfsrmodeact),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxtdel1
#ifdef INIT
= {(char *) &avmaxtdel1,sizeof(avmaxtdel1),GE_INT} 
#endif
;

EXTERN _export  _avminphases
#ifdef INIT
= {(char *) &avminphases,sizeof(avminphases),GE_INT} 
#endif
;

EXTERN _export  _avminetl
#ifdef INIT
= {(char *) &avminetl,sizeof(avminetl),GE_INT} 
#endif
;

EXTERN _export  _avmaxetl
#ifdef INIT
= {(char *) &avmaxetl,sizeof(avmaxetl),GE_INT} 
#endif
;

EXTERN _export  _avminyres
#ifdef INIT
= {(char *) &avminyres,sizeof(avminyres),GE_INT} 
#endif
;

EXTERN _export  _avminslicecnt
#ifdef INIT
= {(char *) &avminslicecnt,sizeof(avminslicecnt),GE_INT} 
#endif
;

EXTERN _export  _avmaxslicecnt
#ifdef INIT
= {(char *) &avmaxslicecnt,sizeof(avmaxslicecnt),GE_INT} 
#endif
;

EXTERN _export  _avmaxtseq
#ifdef INIT
= {(char *) &avmaxtseq,sizeof(avmaxtseq),GE_INT} 
#endif
;

EXTERN _export  _avminxres
#ifdef INIT
= {(char *) &avminxres,sizeof(avminxres),GE_INT} 
#endif
;

EXTERN _export  _avminnshots
#ifdef INIT
= {(char *) &avminnshots,sizeof(avminnshots),GE_INT} 
#endif
;

EXTERN _export  _avmaxnshots
#ifdef INIT
= {(char *) &avmaxnshots,sizeof(avmaxnshots),GE_INT} 
#endif
;

EXTERN _export  _avmaxphasefov
#ifdef INIT
= {(char *) &avmaxphasefov,sizeof(avmaxphasefov),GE_FLOAT} 
#endif
;

EXTERN _export  _avminphasefov
#ifdef INIT
= {(char *) &avminphasefov,sizeof(avminphasefov),GE_FLOAT} 
#endif
;

EXTERN _export  _avminslthick
#ifdef INIT
= {(char *) &avminslthick,sizeof(avminslthick),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxslthick
#ifdef INIT
= {(char *) &avmaxslthick,sizeof(avmaxslthick),GE_FLOAT} 
#endif
;

EXTERN _export  _avminnex
#ifdef INIT
= {(char *) &avminnex,sizeof(avminnex),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxnex
#ifdef INIT
= {(char *) &avmaxnex,sizeof(avmaxnex),GE_FLOAT} 
#endif
;

EXTERN _export  _avminflip
#ifdef INIT
= {(char *) &avminflip,sizeof(avminflip),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxflip
#ifdef INIT
= {(char *) &avmaxflip,sizeof(avmaxflip),GE_FLOAT} 
#endif
;

EXTERN _export  _avminslspace
#ifdef INIT
= {(char *) &avminslspace,sizeof(avminslspace),GE_FLOAT} 
#endif
;

EXTERN _export  _avmaxslspace
#ifdef INIT
= {(char *) &avmaxslspace,sizeof(avmaxslspace),GE_FLOAT} 
#endif
;

EXTERN _export  _cfmaxb1rmshead
#ifdef INIT
= {(char *) &cfmaxb1rmshead,sizeof(cfmaxb1rmshead),GE_FLOAT} 
#endif
;

EXTERN _export  _pidifpage
#ifdef INIT
= {(char *) &pidifpage,sizeof(pidifpage),GE_INT} 
#endif
;

EXTERN _export  _pidifaxnub
#ifdef INIT
= {(char *) &pidifaxnub,sizeof(pidifaxnub),GE_INT} 
#endif
;

EXTERN _export  _pidifaxval1
#ifdef INIT
= {(char *) pidifaxval1,sizeof(pidifaxval1),GE_STRUCT} 
#endif
;

EXTERN _export  _pidifaxval2
#ifdef INIT
= {(char *) pidifaxval2,sizeof(pidifaxval2),GE_STRUCT} 
#endif
;

EXTERN _export  _pidifaxval3
#ifdef INIT
= {(char *) pidifaxval3,sizeof(pidifaxval3),GE_STRUCT} 
#endif
;

EXTERN _export  _pidifaxval4
#ifdef INIT
= {(char *) pidifaxval4,sizeof(pidifaxval4),GE_STRUCT} 
#endif
;

EXTERN _export  _pidifaxval5
#ifdef INIT
= {(char *) pidifaxval5,sizeof(pidifaxval5),GE_STRUCT} 
#endif
;

EXTERN _export  _pidefbval
#ifdef INIT
= {(char *) &pidefbval,sizeof(pidefbval),GE_INT} 
#endif
;

EXTERN _export  _pibvnub
#ifdef INIT
= {(char *) &pibvnub,sizeof(pibvnub),GE_INT} 
#endif
;

EXTERN _export  _pibval2
#ifdef INIT
= {(char *) &pibval2,sizeof(pibval2),GE_INT} 
#endif
;

EXTERN _export  _pibval3
#ifdef INIT
= {(char *) &pibval3,sizeof(pibval3),GE_INT} 
#endif
;

EXTERN _export  _pibval4
#ifdef INIT
= {(char *) &pibval4,sizeof(pibval4),GE_INT} 
#endif
;

EXTERN _export  _pidifrecnub
#ifdef INIT
= {(char *) &pidifrecnub,sizeof(pidifrecnub),GE_INT} 
#endif
;

EXTERN _export  _pidifrecval1
#ifdef INIT
= {(char *) pidifrecval1,sizeof(pidifrecval1),GE_STRUCT} 
#endif
;

EXTERN _export  _pidfirecval2
#ifdef INIT
= {(char *) pidfirecval2,sizeof(pidfirecval2),GE_STRUCT} 
#endif
;

EXTERN _export  _pidfirecval3
#ifdef INIT
= {(char *) pidfirecval3,sizeof(pidfirecval3),GE_STRUCT} 
#endif
;

EXTERN _export  _pidfirecval4
#ifdef INIT
= {(char *) pidfirecval4,sizeof(pidfirecval4),GE_STRUCT} 
#endif
;

EXTERN _export  _pidfirecval5
#ifdef INIT
= {(char *) pidfirecval5,sizeof(pidfirecval5),GE_STRUCT} 
#endif
;

EXTERN _export  _pimonitor
#ifdef INIT
= {(char *) &pimonitor,sizeof(pimonitor),GE_INT} 
#endif
;

EXTERN _export  _pimonfovnub
#ifdef INIT
= {(char *) &pimonfovnub,sizeof(pimonfovnub),GE_INT} 
#endif
;

EXTERN _export  _pimonfovval2
#ifdef INIT
= {(char *) &pimonfovval2,sizeof(pimonfovval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pimonfovval3
#ifdef INIT
= {(char *) &pimonfovval3,sizeof(pimonfovval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pimonfovval4
#ifdef INIT
= {(char *) &pimonfovval4,sizeof(pimonfovval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pidfmonfov
#ifdef INIT
= {(char *) &pidfmonfov,sizeof(pidfmonfov),GE_FLOAT} 
#endif
;

EXTERN _export  _pimonthicknub
#ifdef INIT
= {(char *) &pimonthicknub,sizeof(pimonthicknub),GE_INT} 
#endif
;

EXTERN _export  _pimonthickval2
#ifdef INIT
= {(char *) &pimonthickval2,sizeof(pimonthickval2),GE_FLOAT} 
#endif
;

EXTERN _export  _pimonthickval3
#ifdef INIT
= {(char *) &pimonthickval3,sizeof(pimonthickval3),GE_FLOAT} 
#endif
;

EXTERN _export  _pimonthickval4
#ifdef INIT
= {(char *) &pimonthickval4,sizeof(pimonthickval4),GE_FLOAT} 
#endif
;

EXTERN _export  _pidfmonthick
#ifdef INIT
= {(char *) &pidfmonthick,sizeof(pidfmonthick),GE_FLOAT} 
#endif
;

EXTERN _export  _mon_loc
#ifdef INIT
= {(char *) &mon_loc,sizeof(mon_loc),GE_STRUCT} 
#endif
;

EXTERN _export  _pizmult
#ifdef INIT
= {(char *) &pizmult,sizeof(pizmult),GE_INT} 
#endif
;

EXTERN _export  _piccsat_obl
#ifdef INIT
= {(char *) &piccsat_obl,sizeof(piccsat_obl),GE_INT} 
#endif
;

EXTERN _export  _pifcinenub
#ifdef INIT
= {(char *) &pifcinenub,sizeof(pifcinenub),GE_INT} 
#endif
;

EXTERN _export  _pifcinedefval
#ifdef INIT
= {(char *) &pifcinedefval,sizeof(pifcinedefval),GE_INT} 
#endif
;

EXTERN _export  _pifcineval2
#ifdef INIT
= {(char *) &pifcineval2,sizeof(pifcineval2),GE_INT} 
#endif
;

EXTERN _export  _pifcineval3
#ifdef INIT
= {(char *) &pifcineval3,sizeof(pifcineval3),GE_INT} 
#endif
;

EXTERN _export  _pifcineval4
#ifdef INIT
= {(char *) &pifcineval4,sizeof(pifcineval4),GE_INT} 
#endif
;

EXTERN _export  _pitagging
#ifdef INIT
= {(char *) &pitagging,sizeof(pitagging),GE_INT} 
#endif
;

EXTERN _export  _pitagspcdefval
#ifdef INIT
= {(char *) &pitagspcdefval,sizeof(pitagspcdefval),GE_INT} 
#endif
;

EXTERN _export  _pitagspcval2
#ifdef INIT
= {(char *) &pitagspcval2,sizeof(pitagspcval2),GE_INT} 
#endif
;

EXTERN _export  _pitagspcval3
#ifdef INIT
= {(char *) &pitagspcval3,sizeof(pitagspcval3),GE_INT} 
#endif
;

EXTERN _export  _pitagspcval4
#ifdef INIT
= {(char *) &pitagspcval4,sizeof(pitagspcval4),GE_INT} 
#endif
;

EXTERN _export  _pibsptinub
#ifdef INIT
= {(char *) &pibsptinub,sizeof(pibsptinub),GE_INT} 
#endif
;

EXTERN _export  _pibsptidefval
#ifdef INIT
= {(char *) &pibsptidefval,sizeof(pibsptidefval),GE_INT} 
#endif
;

EXTERN _export  _pibsptival2
#ifdef INIT
= {(char *) &pibsptival2,sizeof(pibsptival2),GE_INT} 
#endif
;

EXTERN _export  _pibsptival3
#ifdef INIT
= {(char *) &pibsptival3,sizeof(pibsptival3),GE_INT} 
#endif
;

EXTERN _export  _pibsptival4
#ifdef INIT
= {(char *) &pibsptival4,sizeof(pibsptival4),GE_INT} 
#endif
;

EXTERN _export  _pibsptival5
#ifdef INIT
= {(char *) &pibsptival5,sizeof(pibsptival5),GE_INT} 
#endif
;

EXTERN _export  _pibsptival6
#ifdef INIT
= {(char *) &pibsptival6,sizeof(pibsptival6),GE_INT} 
#endif
;

EXTERN _export  _cfxmgrampow
#ifdef INIT
= {(char *) &cfxmgrampow,sizeof(cfxmgrampow),GE_FLOAT} 
#endif
;

EXTERN _export  _cfymgrampow
#ifdef INIT
= {(char *) &cfymgrampow,sizeof(cfymgrampow),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzmgrampow
#ifdef INIT
= {(char *) &cfzmgrampow,sizeof(cfzmgrampow),GE_FLOAT} 
#endif
;

EXTERN _export  _cfsdlim
#ifdef INIT
= {(char *) &cfsdlim,sizeof(cfsdlim),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxrsat
#ifdef INIT
= {(char *) &cfxrsat,sizeof(cfxrsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyrsat
#ifdef INIT
= {(char *) &cfyrsat,sizeof(cfyrsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzrsat
#ifdef INIT
= {(char *) &cfzrsat,sizeof(cfzrsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxvsat
#ifdef INIT
= {(char *) &cfxvsat,sizeof(cfxvsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyvsat
#ifdef INIT
= {(char *) &cfyvsat,sizeof(cfyvsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzvsat
#ifdef INIT
= {(char *) &cfzvsat,sizeof(cfzvsat),GE_FLOAT} 
#endif
;

EXTERN _export  _cfgpmpow
#ifdef INIT
= {(char *) &cfgpmpow,sizeof(cfgpmpow),GE_FLOAT} 
#endif
;

EXTERN _export  _cfmgps
#ifdef INIT
= {(char *) &cfmgps,sizeof(cfmgps),GE_FLOAT} 
#endif
;

EXTERN _export  _cfvhr
#ifdef INIT
= {(char *) &cfvhr,sizeof(cfvhr),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrcoil
#ifdef INIT
= {(char *) &cfrcoil,sizeof(cfrcoil),GE_FLOAT} 
#endif
;

EXTERN _export  _cflcoil
#ifdef INIT
= {(char *) &cflcoil,sizeof(cflcoil),GE_FLOAT} 
#endif
;

EXTERN _export  _cfraccoil
#ifdef INIT
= {(char *) &cfraccoil,sizeof(cfraccoil),GE_FLOAT} 
#endif
;

EXTERN _export  _cfpmgs
#ifdef INIT
= {(char *) &cfpmgs,sizeof(cfpmgs),GE_FLOAT} 
#endif
;

EXTERN _export  _cfrhr
#ifdef INIT
= {(char *) &cfrhr,sizeof(cfrhr),GE_FLOAT} 
#endif
;

EXTERN _export  _cfxvpwm
#ifdef INIT
= {(char *) &cfxvpwm,sizeof(cfxvpwm),GE_FLOAT} 
#endif
;

EXTERN _export  _cfyvpwm
#ifdef INIT
= {(char *) &cfyvpwm,sizeof(cfyvpwm),GE_FLOAT} 
#endif
;

EXTERN _export  _cfzvpwm
#ifdef INIT
= {(char *) &cfzvpwm,sizeof(cfzvpwm),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcerdbw1
#ifdef INIT
= {(char *) &cfcerdbw1,sizeof(cfcerdbw1),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcerdbw2
#ifdef INIT
= {(char *) &cfcerdbw2,sizeof(cfcerdbw2),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcerdbw3
#ifdef INIT
= {(char *) &cfcerdbw3,sizeof(cfcerdbw3),GE_FLOAT} 
#endif
;

EXTERN _export  _cfcerdbw4
#ifdef INIT
= {(char *) &cfcerdbw4,sizeof(cfcerdbw4),GE_FLOAT} 
#endif
;

EXTERN _export  _cffastprescan
#ifdef INIT
= {(char *) &cffastprescan,sizeof(cffastprescan),GE_INT} 
#endif
;

EXTERN _export  _pimultistation
#ifdef INIT
= {(char *) &pimultistation,sizeof(pimultistation),GE_INT} 
#endif
;

EXTERN _export  _piautostep
#ifdef INIT
= {(char *) &piautostep,sizeof(piautostep),GE_INT} 
#endif
;

EXTERN _export  _pisioverlap
#ifdef INIT
= {(char *) &pisioverlap,sizeof(pisioverlap),GE_INT} 
#endif
;

EXTERN _export  _csi_grid_on
#ifdef INIT
= {(char *) &csi_grid_on,sizeof(csi_grid_on),GE_INT} 
#endif
;

EXTERN _export  _pispecprescan
#ifdef INIT
= {(char *) &pispecprescan,sizeof(pispecprescan),GE_INT} 
#endif
;

EXTERN _export  _picsimode
#ifdef INIT
= {(char *) &picsimode,sizeof(picsimode),GE_INT} 
#endif
;

EXTERN _export  _rhrlfov
#ifdef INIT
= {(char *) &rhrlfov,sizeof(rhrlfov),GE_INT} 
#endif
;

EXTERN _export  _rhapfov
#ifdef INIT
= {(char *) &rhapfov,sizeof(rhapfov),GE_INT} 
#endif
;

EXTERN _export  _rhsifov
#ifdef INIT
= {(char *) &rhsifov,sizeof(rhsifov),GE_INT} 
#endif
;

EXTERN _export  _cfcerdtype
#ifdef INIT
= {(char *) &cfcerdtype,sizeof(cfcerdtype),GE_INT} 
#endif
;

EXTERN _export  _cfpicture
#ifdef INIT
= {(char *) &cfpicture,sizeof(cfpicture),GE_INT} 
#endif
;


#endif /* h_cv_const_exportstr_h */

