/*
 *  cv_const.allcv.h
 *
 *  Do not edit this file. It is automatically generated by EPIC+.
 *
 *  Date : May 19 2000
 *  Time : 11:31:19
 */

#ifndef h_cv_const_allcv_h
#define h_cv_const_allcv_h

#ifdef INC4CPP
#include "epic_struct.h"
#include "em_psd_ermes.in"
#include "cv_const.global.h"
#endif

EXTERN long  _firstcv 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opweight 
#ifdef INIT
= 50  
#endif
;

EXTERN int  opcoil 
#ifdef INIT
= PSD_HEAD  
#endif
;

EXTERN int  opentry 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oppos 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oppseq 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opcgate 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexor 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfcomp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opplane 
#ifdef INIT
= PSD_AXIAL  
#endif
;

EXTERN int  opgrx 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opgrxroi 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opobplane 
#ifdef INIT
= PSD_AXIAL  
#endif
;

EXTERN int  opnopwrap 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opimode 
#ifdef INIT
= PSD_2D  
#endif
;

EXTERN int  opsat 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opptsize 
#ifdef INIT
= 2 
#endif
;

EXTERN int  oppomp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opscic 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oprect 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsquare 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opvbw 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opblim 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfast 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opcs 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opdeprep 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opirprep 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmph 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opautotr 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opphcor 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opacqo 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opfphases 
#ifdef INIT
= PHASES_MIN  
#endif
;

EXTERN int  opsldelay 
#ifdef INIT
= 50000  
#endif
;

EXTERN int  opmt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsatx 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsaty 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsatz 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opsatxloc1 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatxloc2 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatyloc1 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatyloc2 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatzloc1 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatzloc2 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opsatxthick 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opsatythick 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opsatzthick 
#ifdef INIT
= 80  
#endif
;

EXTERN int  opsatmask 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfat 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opwater 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opccsat 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatmask 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opexsathick1 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsathick2 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsathick3 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsathick4 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsathick5 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsathick6 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opexsatloc1 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opexsatloc2 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opexsatloc3 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opexsatloc4 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opexsatloc5 
#ifdef INIT
= 9999  
#endif
;

EXTERN float  opexsatloc6 
#ifdef INIT
= 9999  
#endif
;

EXTERN int  opexsatparal 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff1 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff2 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff3 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff4 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff5 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatoff6 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opexsatlen1 
#ifdef INIT
= 480  
#endif
;

EXTERN int  opexsatlen2 
#ifdef INIT
= 480  
#endif
;

EXTERN int  opexsatlen3 
#ifdef INIT
= 480  
#endif
;

EXTERN int  opexsatlen4 
#ifdef INIT
= 480  
#endif
;

EXTERN int  opexsatlen5 
#ifdef INIT
= 480  
#endif
;

EXTERN int  opexsatlen6 
#ifdef INIT
= 480  
#endif
;

EXTERN float  opdfsathick1 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opdfsathick2 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opdfsathick3 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opdfsathick4 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opdfsathick5 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opdfsathick6 
#ifdef INIT
= 80  
#endif
;

EXTERN float  opvenc 
#ifdef INIT
= 50.0  
#endif
;

EXTERN int  opflaxx 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opflaxy 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opflaxz 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opflaxall 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opproject 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opcollapse 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oprlflow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opapflow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsiflow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmagc 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opflrecon 
#ifdef INIT
= 0 
#endif
;

EXTERN int  project 
#ifdef INIT
= 0 
#endif
;

EXTERN int  vas_ovrhd 
#ifdef INIT
= 0 
#endif
;

EXTERN int  slice_col 
#ifdef INIT
= 1 
#endif
;

EXTERN int  phase_col 
#ifdef INIT
= 0 
#endif
;

EXTERN int  read_col 
#ifdef INIT
= 0 
#endif
;

EXTERN int  mag_mask 
#ifdef INIT
= 1 
#endif
;

EXTERN int  phase_cor 
#ifdef INIT
= 1 
#endif
;

EXTERN int  extras 
#ifdef INIT
= 0 
#endif
;

EXTERN int  mag_create 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rl_flow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ap_flow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  si_flow 
#ifdef INIT
= 0 
#endif
;

EXTERN int  imagenum 
#ifdef INIT
= 1 
#endif
;

EXTERN int  motsa_ovrhd 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oprampdir 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfcaxis 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ophrate 
#ifdef INIT
= 60  
#endif
;

EXTERN int  oparr 
#ifdef INIT
= 10  
#endif
;

EXTERN int  ophrep 
#ifdef INIT
= 1 
#endif
;

EXTERN int  optdel1 
#ifdef INIT
= 20000  
#endif
;

EXTERN int  optseq 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opphases 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opcardseq 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmphases 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oparrmon 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opvps 
#ifdef INIT
= 8 
#endif
;

EXTERN int  opetl 
#ifdef INIT
= 8 
#endif
;

EXTERN int  opnecho 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opautote 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opte 
#ifdef INIT
= 25000  
#endif
;

EXTERN int  opte2 
#ifdef INIT
= 50000  
#endif
;

EXTERN int  optefw 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opti 
#ifdef INIT
= TI_MIN  
#endif
;

EXTERN int  opirmode 
#ifdef INIT
= SIRMODE  
#endif
;

EXTERN int  optr 
#ifdef INIT
= 400000  
#endif
;

EXTERN float  opflip 
#ifdef INIT
= 90  
#endif
;

EXTERN float  opfov 
#ifdef INIT
= FOV_MAX  
#endif
;

EXTERN float  opphasefov 
#ifdef INIT
= 1 
#endif
;

EXTERN float  opfreqfov 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opslquant 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opileave 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opslthick 
#ifdef INIT
= 5 
#endif
;

EXTERN float  opslspace 
#ifdef INIT
= 10  
#endif
;

EXTERN int  opcoax 
#ifdef INIT
= 1 
#endif
;

EXTERN float  opvthick 
#ifdef INIT
= 320  
#endif
;

EXTERN int  opvquant 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opovl 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplenrl 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplenap 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplensi 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplocrl 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplocap 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oplocsi 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oprlcsiis 
#ifdef INIT
= 1 
#endif
;

EXTERN float  opapcsiis 
#ifdef INIT
= 2 
#endif
;

EXTERN float  opsicsiis 
#ifdef INIT
= 3 
#endif
;

EXTERN int  opxres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  opyres 
#ifdef INIT
= 128  
#endif
;

EXTERN float  opnex 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opslicecnt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opspf 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opcfsel 
#ifdef INIT
= 0 
#endif
;

EXTERN float  oprbw 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  oprbw2 
#ifdef INIT
= 16.0  
#endif
;

EXTERN int  opchrate 
#ifdef INIT
= 100  
#endif
;

EXTERN int  opcphases 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opclocs 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opmctr 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmultrecv 
#ifdef INIT
= 0 
#endif
;

EXTERN int  specnuc 
#ifdef INIT
= 1 
#endif
;

EXTERN int  specpts 
#ifdef INIT
= 256  
#endif
;

EXTERN int  specwidth 
#ifdef INIT
= 2000  
#endif
;

EXTERN int  specnavs 
#ifdef INIT
= 1 
#endif
;

EXTERN int  specnex 
#ifdef INIT
= 2 
#endif
;

EXTERN int  specdwells 
#ifdef INIT
= 1 
#endif
;

EXTERN int  acquire_type 
#ifdef INIT
= 1 
#endif
;

EXTERN int  pixmtband 
#ifdef INIT
= AMP_ERBTEC  
#endif
;

EXTERN int  pibbandfilt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  asslquant 
#ifdef INIT
= 1 
#endif
;

EXTERN float  asflip 
#ifdef INIT
= 20  
#endif
;

EXTERN float  asslthick 
#ifdef INIT
= 10  
#endif
;

EXTERN int  asxres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  asyres 
#ifdef INIT
= 128  
#endif
;

EXTERN int  asbaseline 
#ifdef INIT
= 8 
#endif
;

EXTERN int  asrhblank 
#ifdef INIT
= 4 
#endif
;

EXTERN int  asptsize 
#ifdef INIT
= 4 
#endif
;

EXTERN int  opascalcfov 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opepi 
#ifdef INIT
= 0 
#endif
;

EXTERN int  optlrdrf 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opnshots 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oprtcgate 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oprtrate 
#ifdef INIT
= 12  
#endif
;

EXTERN int  oprtrep 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oprttdel1 
#ifdef INIT
= 20000  
#endif
;

EXTERN int  oprttseq 
#ifdef INIT
= 1 
#endif
;

EXTERN int  oprtcardseq 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oprtarr 
#ifdef INIT
= 10  
#endif
;

EXTERN int  oprtpoint
#ifdef INIT
= 10  
#endif
;

EXTERN int  opssrf 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opt2prep 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opspiral 
#ifdef INIT
= 0 
#endif
;

EXTERN int  piresol 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pioverlap 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfulltrain 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pi_neg_sp 
#ifdef INIT
= 0 
#endif
;

EXTERN float  piisvaldef 
#ifdef INIT
= 2 
#endif
;

EXTERN int  pidmode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  piviews 
#ifdef INIT
= 0 
#endif
;

EXTERN int  piclckcnt 
#ifdef INIT
= 1 
#endif
;

EXTERN float  avmintscan 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pitslice 
#ifdef INIT
= 0 
#endif
;

EXTERN float  pitscan 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pisaveinter 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pivextras 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pinecho 
#ifdef INIT
= 0 
#endif
;

EXTERN float  piscancenter 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pismode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihtr 
#ifdef INIT
= TR_MIN  
#endif
;

EXTERN int  ihti 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihtdel1 
#ifdef INIT
= MIN_TDEL1  
#endif
;

EXTERN float  ihnex 
#ifdef INIT
= 1 
#endif
;

EXTERN float  ihflip 
#ifdef INIT
= 90  
#endif
;

EXTERN int  ihte1 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte2 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte3 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte4 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte5 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte6 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte7 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte8 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte9 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte10 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte11 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte12 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte13 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte14 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte15 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihte16 
#ifdef INIT
= 0 
#endif
;

EXTERN float  ihvbw1 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw2 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw3 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw4 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw5 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw6 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw7 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw8 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw9 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw10 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw11 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw12 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw13 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw14 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw15 
#ifdef INIT
= 16.0  
#endif
;

EXTERN float  ihvbw16 
#ifdef INIT
= 16.0  
#endif
;

EXTERN int  ihnegscanspacing 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihoffsetfreq 
#ifdef INIT
= 1200  
#endif
;

EXTERN int  opuser_usage_tag 
#ifdef INIT
= 0x00000000  
#endif
;

EXTERN int  rhuser_usage_tag 
#ifdef INIT
= 0x00000000  
#endif
;

EXTERN int  rhFillMapMSW 
#ifdef INIT
= 0x00000000  
#endif
;

EXTERN int  rhFillMapLSW 
#ifdef INIT
= 0x00000000  
#endif
;

EXTERN int  rhbline 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhblank 
#ifdef INIT
= 4 
#endif
;

EXTERN int  rhnavs 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhnslices 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhnframes 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhfrsize 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhnecho 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhtype 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhtype1 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhformat 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhptsize 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhnpomp 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhrcctrl 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhdacqctrl 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhexecctrl 
#ifdef INIT
= 9 
#endif
;

EXTERN int  rhfdctrl 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhxoff 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhyoff 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhrecon 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhdatacq 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhvquant 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhslblank 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhhnover 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhoscans 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhddaover 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhzeroph 
#ifdef INIT
= 128.5  
#endif
;

EXTERN float  rhalpha 
#ifdef INIT
= 0.46  
#endif
;

EXTERN float  rhnwin 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhntran 
#ifdef INIT
= 2 
#endif
;

EXTERN float  rhfermw 
#ifdef INIT
= 10  
#endif
;

EXTERN float  rhfermr 
#ifdef INIT
= 128  
#endif
;

EXTERN float  rhferme 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhclipmin 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhclipmax 
#ifdef INIT
= 16383  
#endif
;

EXTERN float  rhdoffset 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhudasave 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhsspsave 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhscalei 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhscaleq 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhnpasses 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhrawsize 
#ifdef INIT
= 10000  
#endif
;

EXTERN int  rhincrpass 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhinitpass 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhmethod 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhdaxres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhdayres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhrcxres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhrcyres 
#ifdef INIT
= 256  
#endif
;

EXTERN int  rhimsize 
#ifdef INIT
= 256  
#endif
;

EXTERN float  rhuser0  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser1  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser2  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser3  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser4  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser5  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser6  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser7  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser8  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser9  
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser10 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser11 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser12 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser13 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser14 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser15 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser16 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser17 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser18 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser19 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser20 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser21 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser22 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser23 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser24 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser25 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser26 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser27 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser28 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser29 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser30 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser31 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser32 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser33 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser34 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser35 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser36 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser37 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser38 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser39 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser40 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser41 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser42 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser43 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser44 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser45 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser46 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser47 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhuser48 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhdab0s 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhdab0e 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhctr 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhcrrtime 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhcphases 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhovl 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhvtype 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvenc 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefxa 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefxb 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefxc 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefxd 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefya 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefyb 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefyc 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefyd 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefza 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefzb 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefzc 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvcoefzd 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvmcoef1 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvmcoef2 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvmcoef3 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhvmcoef4 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhphasescale 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhfreqscale 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rawmode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhileaves 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhkydir 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhalt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhreps 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhref 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhpcthrespts 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhpcthrespct 
#ifdef INIT
= 15  
#endif
;

EXTERN int  rhpcdiscbeg 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcdiscmid 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcdiscend 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcileave 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcextcorr 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhrefframes 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcsnore 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcspacial 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpctemporal 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhpcbestky 
#ifdef INIT
= 64.0  
#endif
;

EXTERN int  rhhdbestky 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcinvft 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcctrl 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpctest 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcgraph 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclin 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclinnorm 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclinnpts 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclinorder 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhpclinfitwt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclinavg 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpccon 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcconnorm 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcconnpts 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhpcconorder 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhpcconfitwt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhvrgfxres 
#ifdef INIT
= 128  
#endif
;

EXTERN int  rhvrgf 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhbp_corr 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhrecv_freq_s 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhrecv_freq_e 
#ifdef INIT
= 0.0  
#endif
;

EXTERN int  rhhniter 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhfast_rec 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhgridcontrol 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhb0map 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhtediff 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhradiusa 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhradiusb 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxgrad 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhslewmax 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhscanfov 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhtsamp 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhdensityfactor 
#ifdef INIT
= 0.0  
#endif
;

EXTERN float  rhdispfov 
#ifdef INIT
= 0.0  
#endif
;

EXTERN int  rhmotioncomp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pititle 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser0  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser1  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser2  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser3  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser4  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser5  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser6  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser7  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser8  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser9  
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser10 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser11 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser12 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser13 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser14 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser15 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser16 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser17 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser18 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser19 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser20 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser21 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser22 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser23 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser24 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser25 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser26 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser27 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser28 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser29 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser30 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser31 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser32 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser33 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser34 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser35 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser36 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser37 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser38 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser39 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser40 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser41 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser42 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser43 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser44 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser45 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser46 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser47 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opuser48 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pishldctrl
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  pinolr
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  pinoadc
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  pimixtime 
#ifdef INIT
= 0 
#endif
;

EXTERN int  psd_board_type 
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfcoilres
#ifdef INIT
= 0 
#endif
;

EXTERN int  cftxgate0
#ifdef INIT
= 0 
#endif
;

EXTERN int  cftxgate90
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfcoilportvu
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfcoilportvl
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfcoilbias
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfgradcoil 
#ifdef INIT
= 2 
#endif
;

EXTERN int  rhrefframep 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhscnframe 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpasframe 
#ifdef INIT
= 0 
#endif
;

EXTERN int  cont_flag
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  optabent
#ifdef INIT
= 1 
#endif
;

EXTERN int  sifsetwokey 
#ifdef INIT
= 0 
#endif
;

EXTERN int  iheesp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  oplandmark 
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  opautosldelay 
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  rhpcfitorig 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhpcshotfirst 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcshotlast 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpcmultegrp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhpclinfix 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhpclinslope 
#ifdef INIT
= 0.0  
#endif
;

EXTERN int  rhpcconfix 
#ifdef INIT
= 1 
#endif
;

EXTERN float  rhpcconslope 
#ifdef INIT
= 0.0  
#endif
;

EXTERN int  rhpccoil 
#ifdef INIT
= 1 
#endif
;

EXTERN int  piforkvrgf 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pinofreqoffset 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opssfse 
#ifdef INIT
= 0 
#endif
;

EXTERN int  t1flair_flag 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef1a 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef1b 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef1c 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef1d 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef2a 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef2b 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef2c 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef2d 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef3a 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef3b 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef3c 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhmaxcoef3d 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opdiffuse
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsavedf
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmintedif 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opdfaxx
#ifdef INIT
= 0 
#endif
;

EXTERN int  opdfaxy
#ifdef INIT
= 0 
#endif
;

EXTERN int  opdfaxz
#ifdef INIT
= 0 
#endif
;

EXTERN int  opdfaxall
#ifdef INIT
= 0 
#endif
;

EXTERN int  opbval
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhdptype 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhutctrl 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opflair 
#ifdef INIT
= 0 
#endif
;

EXTERN float  opmonfov 
#ifdef INIT
= 200  
#endif
;

EXTERN float  opmonthick 
#ifdef INIT
= 20  
#endif
;

EXTERN float  opdose 
#ifdef INIT
= 0 
#endif
;

EXTERN float  rhzipfact 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opzip512 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opzip1024 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opslzip2 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opslzip4 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opnvcoil 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opcmon 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opsmartprep 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opcgatetype 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opadvgate 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opfcine 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihfcineim 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihfcinent 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhfcinemode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhfcinearw 
#ifdef INIT
= 10  
#endif
;

EXTERN int  rhvps 
#ifdef INIT
= 8 
#endif
;

EXTERN int  rhvvsaimgs 
#ifdef INIT
= 1 
#endif
;

EXTERN int  rhvvstr 
#ifdef INIT
= 0 
#endif
;

EXTERN int  rhvvsgender 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opbsp 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opbspti 
#ifdef INIT
= TI_MIN  
#endif
;

EXTERN int  opautoti 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opautobti 
#ifdef INIT
= 0 
#endif
;

EXTERN int  ihbspti 
#ifdef INIT
= TI_MIN  
#endif
;

EXTERN int  optagging 
#ifdef INIT
= 0 
#endif
;

EXTERN int  optagspc 
#ifdef INIT
= 7 
#endif
;

EXTERN float  ihtagfa 
#ifdef INIT
= 180.0  
#endif
;

EXTERN float  ihtagor 
#ifdef INIT
= 45.0  
#endif
;

EXTERN float  pifractecho 
#ifdef INIT
= 1.0     
#endif
;

EXTERN int  oprealtime 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opET 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opmultistation 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opnostations 
#ifdef INIT
= 1 
#endif
;

EXTERN int  opstation 
#ifdef INIT
= 1 
#endif
;

EXTERN int  pscahead 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opprescanopt 
#ifdef INIT
= 0 
#endif
;

EXTERN int  autoadvtoscn 
#ifdef INIT
= 0 
#endif
;

EXTERN int  opprotRxMode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  acqs 
#ifdef INIT
= 1 
#endif
;

EXTERN int  avround 
#ifdef INIT
= 1 
#endif
;

EXTERN int  baseline 
#ifdef INIT
= 0 
#endif
;

EXTERN int  nex 
#ifdef INIT
= 1 
#endif
;

EXTERN float  fn 
#ifdef INIT
= 1 
#endif
;

EXTERN float  nop 
#ifdef INIT
= 1 
#endif
;

EXTERN int  acq_type 
#ifdef INIT
= TYPSPIN  
#endif
;

EXTERN int  seq_type 
#ifdef INIT
= TYPNCAT  
#endif
;

EXTERN int  num_images 
#ifdef INIT
= 1 
#endif
;

EXTERN int  mag 
#ifdef INIT
= 1 
#endif
;

EXTERN int  pha 
#ifdef INIT
= 0 
#endif
;

EXTERN int  imag 
#ifdef INIT
= 0 
#endif
;

EXTERN int  qmag 
#ifdef INIT
= 0 
#endif
;

EXTERN int  exnex 
#ifdef INIT
= 1 
#endif
;

EXTERN int  slquant1 
#ifdef INIT
= 1 
#endif
;

EXTERN int  psd_grd_wait 
#ifdef INIT
= 56  
#endif
;

EXTERN int  psd_rf_wait 
#ifdef INIT
= 0 
#endif
;

EXTERN int  pos_moment_start 
#ifdef INIT
= 0 
#endif
;

EXTERN int  mps1rf1_inst 
#ifdef INIT
= 0 
#endif
;

EXTERN int  scanrf1_inst 
#ifdef INIT
= 0 
#endif
;

EXTERN int  cfcarddelay 
#ifdef INIT
= 10  
#endif
;

EXTERN float  GAM 
#ifdef INIT
= 4257.59  
#endif
;

EXTERN int  psd_card_hdwr_delay 
#ifdef INIT
= 0 
#endif
;

EXTERN int  off90 
#ifdef INIT
= 80  
#endif
;

EXTERN int  TR_SLOP 
#ifdef INIT
= 2000  
#endif
;

EXTERN int  TR_PASS 
#ifdef INIT
= 50000  
#endif
;

EXTERN int  TR_PASS3D 
#ifdef INIT
= 550000  
#endif
;

EXTERN int  csweight
#ifdef INIT
= 100  
#endif
;

EXTERN float  truenex 
#ifdef INIT
= 0 
#endif
;

EXTERN int  eg_phaseres 
#ifdef INIT
= 0 
#endif
;

EXTERN int  sp_satcard_loc 
#ifdef INIT
= 0 
#endif
;

EXTERN int  min_rfdycc
#ifdef INIT
= 0 
#endif
;

EXTERN int  min_rfavgpow
#ifdef INIT
= 0 
#endif
;

EXTERN int  coll_prefls 
#ifdef INIT
= 1 
#endif
;

EXTERN int  maxGradRes 
#ifdef INIT
= 1 
#endif
;

EXTERN float  dfg 
#ifdef INIT
= 2 
#endif
;

EXTERN float  pg_beta 
#ifdef INIT
= 1.0  
#endif
;

EXTERN int  split_dab 
#ifdef INIT
= 0 
#endif
;

EXTERN float  freq_scale 
#ifdef INIT
= 1.0  
#endif
;

EXTERN int  numrecv 
#ifdef INIT
= 1 
#endif
;

EXTERN int  pe_on 
#ifdef INIT
= 1 
#endif
;

EXTERN float  psd_targetscale 
#ifdef INIT
= 1.0 
#endif
;

EXTERN float  logxfs
#ifdef INIT
= 0 
#endif
;

EXTERN float  logyfs
#ifdef INIT
= 0 
#endif
;

EXTERN float  logzfs
#ifdef INIT
= 0 
#endif
;

EXTERN int  logxrt
#ifdef INIT
= 0 
#endif
;

EXTERN int  logyrt
#ifdef INIT
= 0 
#endif
;

EXTERN int  logzrt
#ifdef INIT
= 0 
#endif
;

EXTERN int  logxft
#ifdef INIT
= 0 
#endif
;

EXTERN int  logyft
#ifdef INIT
= 0 
#endif
;

EXTERN int  logzft
#ifdef INIT
= 0 
#endif
;

EXTERN float  logxfa
#ifdef INIT
= 0 
#endif
;

EXTERN float  logyfa
#ifdef INIT
= 0 
#endif
;

EXTERN float  logzfa
#ifdef INIT
= 0 
#endif
;

EXTERN float  logxcc
#ifdef INIT
= 0 
#endif
;

EXTERN float  logycc
#ifdef INIT
= 0 
#endif
;

EXTERN float  logzcc
#ifdef INIT
= 0 
#endif
;

EXTERN float  logxbeta
#ifdef INIT
= 0 
#endif
;

EXTERN float  logybeta
#ifdef INIT
= 0 
#endif
;

EXTERN float  logzbeta
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtx
#ifdef INIT
= 0 
#endif
;

EXTERN float  logty
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtx_xy
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtx_xz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logty_xy
#ifdef INIT
= 0 
#endif
;

EXTERN float  logty_yz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtz_xz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtz_yz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtx_xyz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logty_xyz
#ifdef INIT
= 0 
#endif
;

EXTERN float  logtz_xyz
#ifdef INIT
= 0 
#endif
;

EXTERN int  min_rfrmsb1
#ifdef INIT
= 0 
#endif
;

EXTERN float  psd_zero 
#ifdef INIT
= 0.0  
#endif
;

EXTERN int  minseqgram_t
#ifdef INIT
= 0 
#endif
;

EXTERN int  lx_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  ly_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  lz_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  px_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  py_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  pz_pwmtime
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqcoil_t
#ifdef INIT
= 0 
#endif
;

EXTERN float  xa2s
#ifdef INIT
= 0 
#endif
;

EXTERN float  ya2s
#ifdef INIT
= 0 
#endif
;

EXTERN float  za2s
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqgrddrv_t
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqgrddrvx_t
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqgrddrvy_t
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqgrddrvz_t
#ifdef INIT
= 0 
#endif
;

EXTERN float  powerx
#ifdef INIT
= 0 
#endif
;

EXTERN float  powery
#ifdef INIT
= 0 
#endif
;

EXTERN float  powerz
#ifdef INIT
= 0 
#endif
;

EXTERN float  pospowerx
#ifdef INIT
= 0 
#endif
;

EXTERN float  pospowery
#ifdef INIT
= 0 
#endif
;

EXTERN float  pospowerz
#ifdef INIT
= 0 
#endif
;

EXTERN float  negpowerx
#ifdef INIT
= 0 
#endif
;

EXTERN float  negpowery
#ifdef INIT
= 0 
#endif
;

EXTERN float  negpowerz
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_lx
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_ly
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_lz
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_px
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_py
#ifdef INIT
= 0 
#endif
;

EXTERN float  amptrans_pz
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_lx
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_ly
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_lz
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_px
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_py
#ifdef INIT
= 0 
#endif
;

EXTERN float  abspower_pz
#ifdef INIT
= 0 
#endif
;

EXTERN int  time_pgen 
#ifdef INIT
= 0 
#endif
;

EXTERN int  cont_debug 
#ifdef INIT
= 0 
#endif
;

EXTERN int  maxpc_cor 
#ifdef INIT
= 0 
#endif
;

EXTERN int  maxpc_debug 
#ifdef INIT
= 0 
#endif
;

EXTERN int  maxpc_points 
#ifdef INIT
= 500  
#endif
;

EXTERN int  tsamp 
#ifdef INIT
= 4 
#endif
;

EXTERN int  seg_debug 
#ifdef INIT
= 0 
#endif
;

EXTERN int  gradHeatMethod 
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  minseqpwm_x
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqpwm_y
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqpwm_z
#ifdef INIT
= 0 
#endif
;

EXTERN int  minseqgpm_t
#ifdef INIT
= 0 
#endif
;

EXTERN int  sgd_perf_simulate 
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  gradHeatFile 
#ifdef INIT
= PSD_OFF  
#endif
;

EXTERN int  seqEntryIndex 
#ifdef INIT
= 0 
#endif
;

EXTERN int  dbdt_debug 
#ifdef INIT
= 0 
#endif
;

EXTERN int  reilly_mode 
#ifdef INIT
= 0 
#endif
;

EXTERN int  dbdt_disable 
#ifdef INIT
= 0 
#endif
;

EXTERN int  use_dbdt_opt 
#ifdef INIT
= 1 
#endif
;

EXTERN float  srderate 
#ifdef INIT
= 1.0  
#endif
;

EXTERN long  _lastcv 
#ifdef INIT
= 0 
#endif
;


#endif /* h_cv_const_allcv_h */

