/*
 *  cv_const.global.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_cv_const_global_h
#define h_cv_const_global_h


extern char psd_name[255];

/* ***************************
	IPG-PSD COMMON AREA
   Pulsegen Constants and
   Hardware specific variables
   ************************** */
#include "GEtypes.h"             /* type definitions from GEtypes project*/
#include "ca_filt.h"
#define EOS_PLAY 0
#define EOS_DEAD 1

/* IPG Trigger Codes */
#define TRIG_LINE 1
#define TRIG_ECG 3
#define TRIG_AUX 5
#define TRIG_INTERN 7
#define TRIG_NLINE 9  /* TRIG_NLINE is not a real hardware trigger.
			 It is used to bump up optr by TR_SLOP when a 
			 sequence may line gate based on the value
			 of optr.  So if a new #define is needed for
			 the hardware, change the value of TRIG_NLINE */

/* WARP codes */
#define WARP_UPDATE_NOW 0
#define WARP_UPDATE_ON_SSP_INT 1

/* Pause Attributes */
#define MAY_PAUSE 1
#define MUST_PAUSE 2
#define AUTO_PAUSE 3

/* Reilly dBdt value at infinite transition time  */
#define REILLYDBDTINF 54.0
/* DBDT factor divided by transition time added to REILLYDBDTINF */
#define REILLYDBDTFACTOR 132.0

/* Structure for the PSD supplied error parameters for rspexit */
typedef struct {
  long abcode;
  char text_string[256];
  char text_arg[16]; /* text argument */
  long *longarg[4];   /* pointers to global status ints */
} PSD_EXIT_ARG;

/* ************************************
   CINE Structures
   ********************************** */
typedef struct {     /* structure for cine info that is static */
  int c_numviews;   /* number of cine views to be played */
  int c_curpass;   /* current pass number */
  int c_tr;         /* cine TR in us */
  short c_slq;      /* number of slices */
  short c_acq;      /* # of acqs */
} CINE_PASS;        /* the psd will update this at the start of 
		       each pass */

/* The following packet will be updated by the IPG software and 
   ready to be read by the PSD ssivector routine during the ssi 
   interrupt.  It informs the the psd of the view to play, whether 
   the data collection should be in disdaq mode, whether a cine packet
   should be transmitted, and what information should be placed in
   the cine packet. */
typedef struct {   
  short c_arr;       /* arrhythmia of Cine packet */
  short c_op;        /* operation, as in DAB packet */
  int c_nview;       /* next view number to play */
  int c_pview;       /* previous view number  */
  short c_frame1;    /* frames, slice 1 */
  short c_frame2;    /* frames, slice 2 */
  short c_frame3;    /* frames, slice 3 */
  short c_frame4;    /* frames, slice 4 */
  int c_delay;       /* time from R-wave to beginning of first frame
			in units of 1.25 ms */
  int c_f1slice;     /* frame 1`s slice number */
  short c_check;     /* end of pass check */
  short c_collect;   /* data collection flag */
  short c_send;      /* cine packet send flag */
  short c_group;     /* cine exorcist group */
} CINE_SEQ;

/************************************/
/* These structures are new for 5.5 */
/************************************/

/* 3/13/95 YI changed for new system safety */

/* ************************************
   Physical and Logical Gradient Structures
  ********************************** */

typedef struct {   /* Physical gradient quantities */
  int xfull;       /* cfxfull */
  int yfull;       /* cfyfull */
  int zfull;       /* cfzfull */
  float xfs;       /* X grad full scale (G/cm) */
  float yfs;       /* Y grad full scale (G/cm) */
  float zfs;       /* Z grad full scale (G/cm) */
  int   xrt;       /* X rise time 0-full scale (usec) */
  int   yrt;       /* Y rise time 0-full scale (usec) */
  int   zrt;       /* Z rise time 0-full scale (usec) */
  int   xft;       /* X fall time full scale-0 (usec) */
  int   yft;       /* Y fall time full scale-0 (usec) */
  int   zft;       /* Z fall time full scale-0 (usec) */
  float xcc;       /* X current capacity (amps) */
  float ycc;       /* Y current capacity (amps) */
  float zcc;       /* Z current capacity (amps) */
  float xbeta;     /* X grad linear ramp factor */
  float ybeta;     /* Y grad linear ramp factor */
  float zbeta;     /* Z grad linear ramp factor */
  float xirms;     /* X constant RMS coil current rating  */
  float yirms;     /* Y constant RMS coil current rating  */
  float zirms;     /* Z constant RMS coil current rating  */
  float xipeak;    /* X peak current output (was xfa)   */
  float yipeak;    /* Y peak current output (was yfa)   */
  float zipeak;    /* Z peak current output (was zfa)   */
  float xamptran;  /* X amp transition current (KA/Sec) */
  float yamptran;  /* Y amp transition current (KA/Sec) */
  float zamptran;  /* Z amp transition current (KA/Sec) */
  float xiavrgabs; /* X absolute average value current limit (Amperes) */
  float yiavrgabs; /* Y absolute average value current limit (Amperes) */
  float ziavrgabs; /* Z absolute average value current limit (Amperes) */
  float xirmspos;  /* X positive RMS current limit (Amperes)  */
  float yirmspos;  /* Y positive RMS current limit (Amperes)  */
  float zirmspos;  /* Z positive RMS current limit (Amperes)  */
  float xirmsneg;  /* X negative RMS current limit (Amperes)  */
  float yirmsneg;  /* Y negative RMS current limit (Amperes)  */  
  float zirmsneg;  /* Z negative RMS current limit (Amperes)  */
  float xpwmdc;    /* X pulse width modulation duty cycle limit (0~1) */
  float ypwmdc;    /* Y pulse width modulation duty cycle limit (0~1) */
  float zpwmdc;    /* Z pulse width modulation duty cycle limit (0~1) */
  } PHYS_GRAD;

/*Structures for use with values that depend on the number of active
  logical gradients. For example t_xcon is a structure for information
  about gradient ramp-times (or targets) for the logical
  x-axis. The x structure member is used when only x is active, xy is
  used when only x and y are active, etc. */

typedef struct {
  int x;
  int xy;
  int xz;
  int xyz;
}  t_xact;

typedef struct {
  int y;
  int xy;
  int yz;
  int xyz;
}  t_yact;

typedef struct {
  int z;
  int xz;
  int yz;
  int xyz;
}  t_zact;

typedef struct { 
  int xrt;
  int yrt;
  int zrt;
  int xft;
  int yft;
  int zft;
} ramp_t;

typedef struct {   /* Logical gradient quantities */
  int   xrt;       /* X rise time 0-full scale (usec) */
  int   yrt;       /* Y rise time 0-full scale (usec) */
  int   zrt;       /* Z rise time 0-full scale (usec) */
  int   xft;       /* X fall time full scale-0 (usec) */
  int   yft;       /* Y fall time full scale-0 (usec) */
  int   zft;       /* Z fall time full scale-0 (usec) */
  ramp_t opt;      /* RJF optimized rise times for different axes based on actual dB/dt */
  t_xact xrta;     /* X rise time for different number of active gradients */
  t_yact yrta;     /* Y rise time for different number of active gradients */
  t_zact zrta;     /* Z rise time for different number of active gradients */
  t_xact xfta;     /* X fall time for different number of active gradients */
  t_yact yfta;     /* Y fall time for different number of active gradients */
  t_zact zfta;     /* Z fall time for different number of active gradients */
  float xbeta;     /* X grad linear ramp factor */
  float ybeta;     /* Y grad linear ramp factor */
  float zbeta;     /* Z grad linear ramp factor */
  float tx_xyz;    /* X target, 3 logical functions active (G/cm) */
  float ty_xyz;    /* Y target, 3 logical functions active (G/cm) */
  float tz_xyz;    /* Z target, 3 logical functions active (G/cm) */
  float tx_xy;     /* X target, x and y active (G/cm) */
  float tx_xz;     /* X target, x and z active (G/cm) */
  float ty_xy;     /* Y target, x and y active (G/cm) */
  float ty_yz;     /* Y target, y and z active (G/cm) */
  float tz_xz;     /* Z target, x and z active (G/cm) */
  float tz_yz;     /* Z target, y and z active (G/cm) */
  float tx;        /* X target, x active (G/cm) */
  float ty;        /* Y target, y active (G/cm) */
  float tz;        /* Z target, z active (G/cm) */
  float xfs;       /* X full scale value (G/cm)   */
  float yfs;       /* Y full scale value (G/cm)   */
  float zfs;       /* Z full scale value (G/cm)   */
  float xirms;     /* X constant RMS coil current rating  */
  float yirms;     /* Y constant RMS coil current rating  */
  float zirms;     /* Z constant RMS coil current rating  */
  float xipeak;    /* X peak current output    */
  float yipeak;    /* Y peak current output    */
  float zipeak;    /* Z peak current output    */
  float xamptran;  /* X amp transition current (KA/uSec)  */
  float yamptran;  /* Y amp transition current (KA/uSec)  */
  float zamptran;  /* Z amp transition current (KA/uSec)  */  
  float xiavrgabs; /* X absolute average value current limit (Amperes) */
  float yiavrgabs; /* Y absolute average value current limit (Amperes) */
  float ziavrgabs; /* Z absolute average value current limit (Amperes) */
  float xirmspos;  /* X positive RMS current limit (Amperes)   */
  float yirmspos;  /* Y positive RMS current limit (Amperes)   */
  float zirmspos;  /* Z positive RMS current limit (Amperes)   */
  float xirmsneg;  /* X negative RMS current limit (Amperes)    */
  float yirmsneg;  /* Y negative RMS current limit (Amperes)    */
  float zirmsneg;  /* Z negative RMS current limit (Amperes)    */
  float xpwmdc;    /* X pulse width modulation duty cycle limit (0~1) */
  float ypwmdc;    /* Y pulse width modulation duty cycle limit (0~1) */
  float zpwmdc;    /* Z pulse width modulation duty cycle limit (0~1) */
  } LOG_GRAD;

/* ************************************
   Echo Planar Optimization Structures
   ********************************** */
typedef struct {
  float xfs;       /* x grad full scale (g/cm) */
  float yfs;       /* y grad full scale (g/cm) */
  int   xrt;       /* x grad rise time 0-xfs (usec) */
  int   yrt;       /* y grad rise time 0-yfs (usec) */
  float xbeta;     /* beta for segmented parabolic waveshapes x grad */
  float ybeta;     /* beta for segmented parabolic waveshapes y grad*/
  float xfov;      /* fov in logical x direction (cm) */
  float yfov;      /* fov in logical y direction (cm) */
  int   xres;      /* operator selected x resolution (pixels) */
  int   yres;      /* operator selected y resolution (pixels) */
  int   ileaves;   /* number of interleaved shots */
  float xdis;      /* x distance for dB/dt calculation */
  float ydis;      /* y distance for dB/dt calculation */
  float tsp;       /* sample period */
  int   osamps;    /* Fractional echo oversamps */
  float fbhw;      /* fraction of blip half width excluded from
                                          sampling (VRG only) */
  int   vvp;       /* inter-echo base period */
  float pnsf;      /* peripheral nerve stimulation factor */
} OPT_GRAD_INPUT;
 
typedef struct {
  float *agxw;     /* epi readout pulse amplitude */
  int   *pwgxw;    /* epi readout pulse width */
  int   *pwgxwa;   /* epi readout attack/decay ramp */
  float *agyb;     /* epi blip pulse amplitude */
  int   *pwgyb;    /* epi blip pulse width */
  int   *pwgyba;   /* epi blip pulse attack/decay ramp */
  int   *frsize;   /* frame size - number of samples */
  int   *pwsamp;   /* sample window width */
  int   *pwxgap;   /* epi readout interecho gap */
} OPT_GRAD_PARAMS;
 
/*********************************/
/* End of new structures for 5.5 */
/*********************************/
 

#define CN_PASSES_EXCEEDED 1
#define CN_FRAMES_EXCEEDED 2
#define CN_NOINIT          3
#define EX_NOINIT          4
/* Number of entries in entry point table */
#define ENTRY_POINT_MAX 20

/* constants for createramps routine *//* merged 55 bch. YH */
#define PSD_SLOPE_NONE 0
#define PSD_SLOPE_UP 1
#define PSD_SLOPE_DOWN 2

/* END - PSD - IPG common area */

/* Visibility Constants */
#define VIS MODIFIABLE

#define PSD_FILTER_MAX 14

/* #ifdef MCVALL */ /* make all the CVs modifiable for vmx testing. 7/18/94 */ 

#define INVIS    MODIFIABLE
#define VISONLY  MODIFIABLE
/* #else
#define INVIS    INVISIBLE
#define VISONLY  VISIBLE
#endif */

/* Board Names */

#define XGRAD TYPXGRAD
#define YGRAD TYPYGRAD
#define ZGRAD TYPZGRAD
#define RHO   TYPRHO1
#define THETA TYPTHETA
#define OMEGA TYPOMEGA
#define SSP   TYPSSP
#define XGRADB TYPBXGRAD
#define YGRADB TYPBYGRAD
#define ZGRADB TYPBZGRAD
#define XGRD 1   /* merged 55 bch */
#define YGRD 2   /* into vmx.     */
#define ZGRD 3   /* YH 10/14/94   */
 
/* Can't use pulsegen constant for number of processors */
#define PSD_MAX_PROCESSORS 9
/* Misc. constants */
#ifndef PI
#define PI 3.14159265358979323846
#endif /* PI */
/* Positive Full Scale in IPG.  All #'s
/   scaled to this number */
#define FSI 32752 
#define FSI_PI

/* integer values for pi and 2pi */
#define FS_PI 32752
#define FS_2PI 65504

#define GFS 1.0 /* gradient full scale G/cm */

/* gradient amp constants */
#define G8603 0
#define G8604 1
#define G8607 2
#define G8645 3    /* merged 55 bch         */
#define G8250 4    /* Analogic single for VMX *//* into vmx. YH 10/14/94 */
#define G8251 5    /* Analogic twin for VMX SR40 *//* 06/21/95 YI */
#define G9090 6    /* YMS HDU for Profile system *//* 06/21/95 YI */
#define G8651 7    /* Analogic SGD Hi Slew */
#define G8280 8    /* Analogic SGD Base */
#define G8915 9    /* ACGD Hi Slew */

/* gradient coil types *//* vmx 12/07/94 YI */
#define GCOIL_NONE 0
#define GCOIL_CRD 1
#define GCOIL_ROEMER 2
#define GCOIL_HGC 101
#define GCOIL_VECTRA 102
#define GCOIL_PERMANENT 103

/* GRAM tuning board types */
#define GRAM_TUNE_ANALOG 0  /* merged 55 bch into vmx */
#define GRAM_TUNE_DIGITAL 1 /*            YH 10/14/94 */

/* Service Mode Types for Exciter */
#define PSD_SERVOFF 0
#define PSD_SERVSYNTH 1
#define PSD_SERVLB 2

/* Power Amplifier Selects */
#define AMP_ERBTEC 1
#define AMP_SPECTRO 2

/* Pre and Post Min RF AMP Unblank Times */
#define PSD_PRERFAMP_UBL 250
#define PSD_POSTRFAMP_UBL 50
#define PSD_PRERFAMP_UBL_VMX 600

/* Broadband Use */
#define PSD_BROADBANDOFF 0
#define PSD_BROADBANDON 1

/* Coil Types */
#define PSD_HEAD 1
#define PSD_BODY 2
#define PSD_SURFACE 3
#define PSD_TEST 4

/* Receiver Input Ports */
#define PSD_RP_HEAD 1
#define PSD_RP_BODY 2
#define PSD_RP_SURFACE 3
#define PSD_RP_CERDMC 4
#define PSD_RP_SPECTRO 5
#define PSD_RP_TEST 0

/* Receiver Bias Port */
#define PSD_RB_HEAD 4
#define PSD_RB_BODY 8
#define PSD_RB_SURFACE 16
#define PSD_RB_TEST 32

/* image modes */
#define PSD_2D 1
#define PSD_3D 2
#define PSD_CINE 3
#define PSD_ANGIO 4
#define PSD_SPECTRO 5
#define PSD_3DM 6   /* image mode for 3D Multi-slab */

/* Pulse Sequence Types */
#define PSD_SE 1
#define PSD_GE 2
#define PSD_IR 3
#define PSD_SSFP 4
#define PSD_SPGR 5
#define PSD_TOF 6
#define PSD_PC 7
#define PSD_TOFSP 8
#define PSD_PCSP 9
#define PSD_PROBES 10
#define PSD_PROBEP 11
#define PSD_PRESSCSI 12
#define PSD_STEAMCSI 13
#define PSD_FIDCSI 14
#define PSD_ECHOCSI 15
#define PSD_SPINECHO 16
#define PSD_3PLANELOC 17 

/* Scanning Planes */
#define PSD_AXIAL 1
#define PSD_SAG 2
#define PSD_COR 3
#define PSD_OBL 4
#define PSD_3PLANE 5

/* Scan Rotation Scaling */
#define SHAREDROTSCALE 32752

/* Maximum wave amplitude constants */
#define  max_pg_iamp 32767
#define  max_pg_wamp 32766
#define  MAX_PG_IAMP 32767
#define  MAX_PG_WAMP 32766

/* Pre Defined Timing Constants */
#define TGAP 2

/* Screen Flag values */
#define PSD_OFF 0
#define PSD_ON 1

/* TE Button Control Values */
#define PSD_MINFULLTE -1
#define PSD_MINIMUMTE -2
#define PSD_FWINPHASETE	-3
#define PSD_FWOUTPHASETE -4
#define PSD_MAXIMUMTE -5

/* Automin TR Button Control *//* merged 55 bch into vmx. YH 10/14/94 */
#define PSD_MINIMUMTR -1

/* label control for te buttons */
#define PSD_LABEL_TE_NORM 0
#define PSD_LABEL_TE_EFF  1

/* label control for ti buttons */
#define PSD_AUTO_TI -1
#define PSD_LABEL_TI_IR 0
#define PSD_LABEL_TE_PREP 1

/* label control for pause buttons */
#define PSD_LABEL_PAU_LOC 0
#define PSD_LABEL_PAU_REP 1
#define PSD_LABEL_PAU_ACQ 2

/* screen control for rbw buttons */
#define PSD_BW_SCREEN_SET 0
#define PSD_BW_SCREEN_TIM 1

/* Scan Clock Modes */
#define PSD_CLOCK_NORM 0
#define PSD_CLOCK_CARDIAC 1
#define PSD_CLOCK_PAUSE 2
#define PSD_CLOCK_CARDPAUSE 3

/* Cardiac Inter-Sequence Delay Defines */
#define PSD_CARD_INTER_OTHER 0
#define PSD_CARD_INTER_MIN 1
#define PSD_CARD_INTER_EVEN 2

/* Center Frequency Button Defines */
#define PSD_CFCURRENT 0
#define PSD_CFMID 1
#define PSD_CFH2O 2
#define PSD_CFFAT 3
#define PSD_CFPK 4
#define PSD_CFCENTROID 5

/* Rf pulse Activity bitmasks */
#define PSD_PULSE_OFF 0
#define PSD_CFL_ON 1
#define PSD_CFL_HAD 2
#define PSD_CFH_ON 4
#define PSD_CFH_HAD 8
#define PSD_MPS1_ON 16
#define PSD_MPS1_HAD 32
#define PSD_MPS2_ON 64
#define PSD_MPS2_HAD 128
#define PSD_APS1_ON 256
#define PSD_APS1_HAD 512
#define PSD_APS2_ON 1024
#define PSD_APS2_HAD 2048
#define PSD_SCAN_ON 4096
#define PSD_SCAN_HAD 8192
/*#define PSD_TEST_ON 16384
#define PSD_TEST_HAD 32768*/
#define PSD_FTG_ON  16384   /* merged 55 bch into vmx. YH 10/14/94 */
#define PSD_FTG_HAD 32768
#define PSD_AUS_ON 65536
#define PSD_AUS_HAD 131072
#define PSD_TEST_ON 262144
#define PSD_TEST_HAD 524288 /* merged 55 bch into vmx. YH 10/14/94 */

/* Type of phase generation for 
   altfrgen */

#define TYPLINEAR 0
#define TYPMFILE 1

/* Limit checks for advisory panel routines */
#define PSD_MIN3DSLICE 16
#define PSD_MINF3DSLICE 16
#define PSD_MIN3DPCSLICE 12
#define PSD_MINSLQPSLAB 16
#define PSD_MAXSLQPSLAB 128
#define PSD_MAXIMAGTYP 4

/* used for slice select external macro */
#define PLAY_GFILE 1
#define PLAY_TRAP 0
#define PLAY_RFFILE 1 /* merged 55 bch into vmx. YH 10/14/94 */
#define PLAY_SINC 0
#define PLAY_THETA 1
#define NO_THETA 0    /* merged 55 bch into vmx. YH 10/14/94 */

/* END - PSD - IPG common area */
/* Bitmask fields for explicit sat locations */
#define PSD_EXPLICIT_Z2 0x01
#define PSD_EXPLICIT_Z1 0x02
#define PSD_EXPLICIT_Y2 0x04
#define PSD_EXPLICIT_Y1 0x08
#define PSD_EXPLICIT_X2 0x10
#define PSD_EXPLICIT_X1 0x20

/* bits for opexsatmask */
#define PSD_EXPLICIT_1 0x01
#define PSD_EXPLICIT_2 0x02
#define PSD_EXPLICIT_3 0x04
#define PSD_EXPLICIT_4 0x08
#define PSD_EXPLICIT_5 0x10
#define PSD_EXPLICIT_6 0x20

/* bits for opexparal */
#define PSD_1_PARALLEL 0x01
#define PSD_2_PARALLEL 0x02
#define PSD_3_PARALLEL 0x04

/* Bitmask fields for rhvtype (vascular) */
#define VASCULAR   1                /* Vascular scan */
#define PHASE_CON  2                /* Phase contrast scan */
/** #define UNUSED    4             * Bit three currently unused */
#define TWO_SET    8                /* Two set processing */
#define ANTI_ALIAS 16               /* Anti alias algorithm */
#define PHASE_1    32               /* Phase correction bit 1 */
#define PHASE_2    64               /* Phase correction bit 2 */
#define NOISE_SUPP 128              /* Apply noise suppression mask */
#define MAGNITUDE  256              /* Display magnitude image */
#define PHYSICAL_X 512              /* Display physical x correction */
#define PHYSICAL_Y 1024             /* Display physical y correction */
#define PHYSICAL_Z 2048             /* Display physical z correction */
#define COLLAPSE_Z 4096             /* Collapse logical z image */
#define COLLAPSE_X 8192             /* Collapse logical x image */
#define COLLAPSE_Y 16384            /* Collapse logical y image */
#define VN_1SL_2ST 32768            /* Vinnie 1 slice, 2 set */
#define VN_1SL_4ST 65536            /* Vinnie 1 slice, 4 set */
#define VN_2SL_2ST 131072           /* Vinnie 2 slice, 2 set */
#define ANG_10_DEG 524288           /* Projections every 10 degrees */
#define ANG_5_DEG  1048576          /* Projections every 5  degrees */
#define NOISE2     2097152          /* Bit for complex difference */

/* constants for vascular enhancements */
#define PHASEDIFF 0
#define COMPLEXDIFF 1
#define FLOWANALYS 2

/* Argument types for psdexit */
#define PSD_ARG_INT 1
#define PSD_ARG_FLOAT 2
#define PSD_ARG_STRING 3

/* Control Fields in SSP instruction */
#define PSD_CINE_BIT  0x800000
#define PSD_EXOR_BIT  0x400000
#define PSD_ISI2_BIT  0x080000
#define PSD_ISI1_BIT  0x040000
#define PSD_ISI0_BIT  0x020000
#define PSD_EFB_BIT   0x000080
#define PSD_UBL_RFMOD 0x000040
#define PSD_SCP_TRIG  0x000020
#define PSD_UBL_SPECT 0x000010
#define PSD_UBL_ERB   0x000008
#define PSD_MTX_UPDT  0x000004
#define PSD_WVE_CLR   0x000002
#define PSD_SLC_MARK  0x000001
#define PSD_SPUI_BIT  0x000100

/* System Update Times */
#define GRAD_UPDATE_TIME 4  
#define RF_UPDATE_TIME 2  
#define SSP_UPDATE_TIME 1  

/* Macros for rounding up or down to a gradient or RF boundary */
/* These macros are also defined in supp_macros.h. Let's check for
   multiple definitions. - GFN - 21/Sep/1997 */
#ifndef RUP_GRD
#define RUP_GRD(A)  (((A)%GRAD_UPDATE_TIME) ? (int)((A) + GRAD_UPDATE_TIME) & ~(GRAD_UPDATE_TIME - 1) : (A))
#endif /* RUP_GRD */

#ifndef RDN_GRD
#define RDN_GRD(A)  ((int)(A) & ~(GRAD_UPDATE_TIME -1))
#endif /* RDN_GRD */

#ifndef RUP_RF
#define RUP_RF(A)  (((A)%RF_UPDATE_TIME) ? (int)((A) + RF_UPDATE_TIME) & ~(RF_UPDATE_TIME - 1) : (A))
#endif /* RUP_RF */

#ifndef RDN_RF
#define RDN_RF(A)  ((int)(A) & ~(RF_UPDATE_TIME -1))
#endif /* RDN_RF */

#define MIN_PLATEAU_TIME (2*GRAD_UPDATE_TIME)

/* Theta path frequency path multiplier */
#define PSD_THETAFREQ_SHIFT 4

/* IPG Instruction Size Allocations */
#define PSD_GRADX_INSTR_SIZE  4096
#define PSD_GRADY_INSTR_SIZE  4032
#define PSD_GRADZ_INSTR_SIZE  4096
#define PSD_RHO1_INSTR_SIZE   4096
#define PSD_RHO2_INSTR_SIZE   4096
#define PSD_THETA_INSTR_SIZE  4096
#define PSD_OMEGA_INSTR_SIZE  4096
#define PSD_SSP_INSTR_SIZE    4096
#define PSD_AUX_INSTR_SIZE     64

/* IPG Exit Codes */
#define ERRNONE 0 /* Normal error */

/* User CV control constants */
#define use0  1
#define use1  2
#define use2  4
#define use3  8
#define use4  16
#define use5  32
#define use6  64
#define use7  128
#define use8  256
#define use9  512
#define use10 1024
#define use11 2048
#define use12 4096
#define use13 8192
#define use14 16384
#define use15 32768
#define use16 65536
#define use17 131072
#define use18 262144
#define use19 524288
#define use20 1048576
#define use21 2097152
#define use22 4194304
#define use23 8388608
#define use24 16777216

/* Advisory panel bitmap posistions
 * Note: These are bit positions and not values.
 * The following are for echos, te, te2, ti, tr,
 * fov, receive bandwidth, and velocity encode. */
#define PSD_ADVECHO 0
#define PSD_ADVTE 1
#define PSD_ADVTE2 2 
#define PSD_ADVTI 3
#define PSD_ADVTR 4
#define PSD_ADVFOV 5
#define PSD_ADVRCVBW 6
#define PSD_ADVVENC 7
#define PSD_ADVRCVBW2 8

#define PSD_ADV_SCAN_PARAMS_MAX 7
/* More advisory panel bit positions.
 * The following are respectively for minimum scan time,
 * max. locations/acq, minimum acquisitions, and maximum
 * yres. */
#define PSD_ADVMINTSCAN PSD_ADV_SCAN_PARAMS_MAX + 1
#define PSD_ADVMAXLOCSPERACQ PSD_ADV_SCAN_PARAMS_MAX + 2
#define PSD_ADVMINACQS PSD_ADV_SCAN_PARAMS_MAX + 3
#define PSD_ADVMAXYRES PSD_ADV_SCAN_PARAMS_MAX + 4

#define PSD_ADV_TIME_MAX PSD_ADV_SCAN_PARAMS_MAX + 4

/* More advisory panel bitmap positions.
 * The following are respectively for minimum inter-sequence
 * time, maximum phases, effective TR, maximum scan locations,
 * available image time. 
 * ***************************************************** */
#define PSD_ADVISEQDELAY PSD_ADV_TIME_MAX + 1
#define PSD_ADVMAXPHASES PSD_ADV_TIME_MAX + 2
#define PSD_ADVEFFTR PSD_ADV_TIME_MAX + 3
#define PSD_ADVMAXSCANLOCS PSD_ADV_TIME_MAX + 4
#define PSD_ADVAVAILIMGTIME PSD_ADV_TIME_MAX + 5

/* VRG pulse Resolutions */
#define RES_VRG_GRD 256
#define RES_VRG_RF1 512
#define RES_VRG_RF2 512
#define RES_NVRG_RF1 800
#define RES_NVRG_RF2 400
#define PSD_HNOVER 8
#define PSD_TRMIN 18000


/* CV limit constants */
#define ECG_MIN 30
#define ECG_MAX 230
#define FOV_MIN 1
#define FOV_MIN_VMX 30
#define FOV_MIN_PROFILE 80        /* profile 09/11/95 NM */
#define FOV_MAX 480
#define FOV_MAX_VMX 450
#define FOV_MAX_PROFILE 400       /* profile 09/11/95 NM */
#define PSD_GRXROI_LEN 640.0
#define PSD_SEQMODE_OFF 0
#define ILIRMODE PSD_SEQMODE_OFF
#define MIN_TDEL1 10
#define MIN_SEQ_SYS 2048
#define MAX_TDEL1 1600000
#define MIN_RESP_POINT 10
#define MAX_RESP_POINT 90
#define MIN_RESP_WINDOW 10
#define MAX_RESP_WINDOW 90
#define MAX_CINE_PHASES 32
#define MAX_CINE_SLICES 4
#define MAX_STHICK 200
#define MAX_SLICE3D 128
#define MAXTHICK 20
#define MAXVTHICK 1280
#define MAXVQUANT 64
#define MIN_OFFSET -255
#define MIN_SLOC -12000
#define MIN_STHICK 10
#define MINTHICK 0.1
#define MINTHICK_VMX 2.7
#define NEX_MAX 200
#define NECHO_MIN 1
#define NECHO_MAX 4
#define NOIRMODE 0
#define PSD_NECHO_MAX 1024
#define PSD_SEQMODE_ON 1
#define SIRMODE PSD_SEQMODE_ON
#define SHORT_TE 22000
#define TE_MIN 1000
#define TE_MAX 2000000
#define TE2_MIN 20000
#define TI_MIN 50000
#define TI_MAX 4000000
#define TR_MIN 1000
/* VMX VALUE? #define TR_MAX 6000000 */
#define TR_MAX 15000000
#define XRES_MAX 1024
#define YRES_MAX 1024
#define MAXSLQUANT3D 128
#define MAXSLQUANT2D 256
#define PSD_HNOVER 8
#define PHASES_MIN 1
#define PHASES_MAX 512
#define PSD_MINTEFULL 1
#define PSD_MINTE 2
#define PSD_FWINPHS 3
#define PSD_FWOUTPHS 4
#define PSD_MAXTE 5

/* Fat/Water in Phase Range Limits */
#define PSD_LLIMTEIN1  4200 
#define PSD_ULIMTEIN1  6000 
#define PSD_LLIMTEIN2  8500 
#define PSD_ULIMTEIN2  10000 
#define PSD_LLIMTEIN3  13000 
#define PSD_ULIMTEIN3  TE_MAX

/* Fat/Water out of Phase Range Limits */
#define PSD_LLIMTEOUT1  1800 
#define PSD_ULIMTEOUT1  2800 
#define PSD_LLIMTEOUT2  6300 
#define PSD_ULIMTEOUT2  7300 
#define PSD_LLIMTEOUT3  10800 
#define PSD_ULIMTEOUT3  12000 

/* ************************************************
   CV Processing, Predownload, and RSP
   Initialization Routines

   Structures and Constants 
   
* ************************************************ */
/* Number of entries in data acq table */
#define DATA_ACQ_MAX 512
#define TRIG_ROT_MAX 2*DATA_ACQ_MAX /* double to accomodate graphic sat */
#define PRESCAN_ROT_MAX 1           /* MRIge43968: only one for Prescan */ 
/* Number of entries in scan info table */
#define SLTAB_MAX 256

/* Misc. constants */
#define TARDIS_FREQ_RES 0.59604648
#define RCV_FREQ_TARDIS 187500 /* receiver frequency for Tardis */
#define RCV_FREQ_CERD 125000   /* receiver frequency for CERD */
#define RCV_FREQ_FAST 0   /* receiver frequency offset for fast rcvr */

/* Acquisition Types */
#define TYPSPIN 0   /* Spin Echo */
#define TYPGRAD 1   /* Gradient Recalled */

/* Define Types */
#define TYPNDEF 0   /* Don't caculate */
#define TYPDEF 1    /* Calculate */

/* Sequence  Types */
#define TYPNCAT      0   /* Normal, Non CATSAT */
#define TYPCAT       1   /* CATSAT */
#define TYPXRR       2   /* Cross R-R Imaging */
#define TYPMPMP      3   /* Multiphase multiplanar cardiac */
#define TYPSSMP      4   /* Single Slice Multiphase */
#define TYP3D        5   /* Volume scanning */
#define TYPNORMORDER 6   /* Straight physical order for slices */
#define TYPFASTMPH   7   /* for FGRE MPH slice ordering */
#define TYPF3D       8   /* Fast Volume Scanning */
#define TYP3DMSNCAT  9   /* 3D Multislab non-concat */
#define TYP3DMSCAT  10   /* 3D Multislab concat */
#define TYP3DFSENCAT 11   /* 3D Fast Spin Echo non-concat */
#define TYP3DFSECAT  12   /* 3D Fast Spin Echo concat */
#define TYPRTG       13   /* Respiratory Trigger */
#define TYPF3DMPH       14   /* Fast, Multi-phase 3D */
#define TYPSSFSEINT  15   /* Interleaved slice acq. in ssfse */
#define TYPSSFSESEQ  16   /* Sequential slice acq. in ssfse */
#define TYPSSFSEXRR  17   /* XRR for ssfse */
#define TYPSSFSERTG  18   /* RTG for ssfse */
#define TYPSEQSLIC   19   /* Sequential Slice Ordering */
#define TYPF3DMSMPH  20   /* 3D Multislab Multiphase - added by latha@mr for 3d oblique */

/* Flow Comp Type */
#define TYPNFC 0    /* No Flow Comp */  
#define TYPFC 1     /* Flow Comp */

/* Echo Type */
#define TYPNVEMP 0     /* Normal */
#define TYPVEMP  1     /* VEMP sequence */

/* Resp Comp Type */
#define TYPNORM   0  /* Normal phase ordering */
#define TYPLSORT  1  /* Low Sort Exorcist */
#define TYPHSORT  2  /* High Sort Exorcist */
#define TYPAHSORT 3  /* Average High Sort */

/* Frequency generation type */
#define TYPTRANSMIT   0  /* Generate Transmit frequencies */
#define TYPREC        1  /* Receive frequency */
#define TYPRECGRDEVEN 2  /* Gradient Recall Even echo freq */
/*  following sentences are 5.5 changes. YH 10/14/94 */
#define TYPFASTREC        3 /* Receive frequency - research
                               fast recvr */
#define TYPFASTRECGRDEVEN 4 /* Gradient Recall Even echo freq - research
                                                          fast recvr */

/* Crusher Generation types */
#define PSD_TYPCMEMP 0
#define PSD_TYPCCSMEMP 1
#define PSD_TYPCFCMEMP 2
#define PSD_TYPCPOMP 3
#define PSD_TYPCFCPOMP 4


/* Chopping Codes */
#define CHOP_BL 0    /* Chopper state: chop only baselines (<1NEX) */
#define CHOP_ALL 1   /* Chopper state: chop all views (>1NEX) */
#define CHOP_NONE 2  /* Chopper state: chop nothing */

/* Entry Point Labels */
#define L_CFL 0
#define L_CFH 1
#define L_MPS1 2
#define L_MPS2 3
#define L_APS1 4
#define L_APS2 5
#define L_SCAN 6
/*#define L_TEST 7 */
#define L_FTG 7   /* merged 55 bch into vmx. YH 10/14/94 */
#define L_AUTOSHIM 8
#define L_TEST 9  /* merged 55 bch into vmx. YH 10/14/94 */

/* Autoshim constants */
#define PSD_AUS_ON 65536
#define PSD_AUS_HAS 131072

/* Dab Operations */
#define DABSTORE 0    /* DAB operation to store xcvr data */
#define DABADD 1     /* DAB operation to accumulate data */
#define DABSUBCNTS 2  /* DAB operation to subtract contents from xcvr data */
#define DABSUBXCVR 3   /* DAB operation to subtract xcvr data from contents */

/* Recon Types */
#define RHTYPCHP 1       /* For setting Chop bit in rhtyp */
#define RHTYPCINE  2
#define RHTYPSHIM  4
#define RHTYPGR    8
#define RHTYPFRACTNEX  16
#define RHTYPSTRIP    32
#define RHTYP3D    64
#define RHTYPXOR  128
#define RHTYPNPW   256
#define RHTYPNFW  512
#define RHTYPSPIRAL 1024
#define RHTYPFRACTECHO 2048
#define RHTYP75NEX  8192
#define RHTYPPOMP  16384   /* For setting POMP bit in rhtype */
#define RHTYPTURBO  32768	/* For setting turbo bit in rhtype */

/* More recon types, used in rhtype1 */
#define RHTYP3DM 16     /* 3D multi-slab */
#define RHTYPMAXOVL 32 /* maximum intensity pixel collapse overlap processing */
#define RHTYPMINOVL 64 /* minimum intensity pixel collapse overlap processing */
#define RHTYPAVEOVL 96  /* average intensity pixel collapse overlap processing */
/* *****************************
   Defines for rhrcctrl
   ***************************** */
#define RHRCMAG   1     /* magnitude images   */
#define RHRCPHS   2     /* phase images       */
#define RHRCIMAG  4     /* I magnitude images */
#define RHRCQMAG  8     /* Q magnitude images */
#define RHRCCOMP  16    /* compressed images  */
#define RHRCRAW   128   /* raw image recon */

/* *****************************
   Defines for rhdacqctrl
   ***************************** */
#define RH_FCINE_ET               1024 /* fcine Echotrain data acq. */
#define RH_PASS_THROUGH_CERD_FLAG 2048 /* passthrough data acq. */

/* Power Monitor Scale Factors */
#define PMFULL 255       /* Full scale power monitor.
			    Power monitor values are scaled to this */
#define PMFSPWH 12750    /* Full scale PW in ms. in head coil */
#define PMFSPWB 12750    /* Full scale PW in ms. in body coil */
#define PMFSDCH 0.255    /* Full scale duty cycle in % for head */
#define PMFSDCB 0.255    /* Full scale duty cycle in % for body */
#define PMFSRFH 3300.0   /* Full scale RF power in watts for head */
#define PMFSRFB 22000.0  /* Full scale RF power in watts for body */
#define PMFSRFS 275.0    /* Full scale RF power in watts for surf. */

/* We don't include value for surf. because it is run off the head port.
   Also there isn't any output on RF power amp for surface coil */

#define PMFSPWH_1P5 12750    /* Full scale PW in us. in head coil */
#define PMFSPWB_1P5 12750    /* Full scale PW in us. in body coil */
#define PMFSDCH_1P5 0.255    /* Full scale duty cycle in % for head */
#define PMFSDCB_1P5 0.255    /* Full scale duty cycle in % for body */
#define PMFSRFH_1P5 3300.0   /* Full scale RF power in watts for head */
#define PMFSRFB_1P5 22000.0  /* Full scale RF power in watts for body */

#define PMFSPWH_1P0 30000    /* Full scale PW in us. in head coil */
#define PMFSPWB_1P0 30000    /* Full scale PW in us. in body coil */
#define PMFSDCH_1P0 0.255    /* Full scale duty cycle in % for head */
#define PMFSDCB_1P0 0.255    /* Full scale duty cycle in % for body */
#define PMFSRFH_1P0 1000.0   /* Full scale RF power in watts for head */
#define PMFSRFB_1P0 10000.0  /* Full scale RF power in watts for body */

#define PMFSPWH_0P5 60000    /* Full scale PW in us. in head coil */
#define PMFSPWB_0P5 60000    /* Full scale PW in us. in body coil */
#define PMFSDCH_0P5 0.255    /* Full scale duty cycle in % for head */
#define PMFSDCB_0P5 0.255    /* Full scale duty cycle in % for body */
#define PMFSRFH_0P5 500.0    /* Full scale RF power in watts for head */
#define PMFSRFB_0P5 5000.0   /* Full scale RF power in watts for body */

 /* 
   GRAD_PULSE structure is used by a variety of support routines, as
   a convenient method of passing pulse object parameters.  The PSD
   must keep track of the type and quantity of grad pulses used.
  */  /* merged 55 bch into vmx. YH 10/14/94 */
/* 3/13/95 YI changed for new system safety */

typedef struct {
  int ptype;      /* gradient Type (e.g. ramp, constant, trapezoid, etc.) */
  int *attack;    /* pulse width of attack for trapezoidal pulses */
  int *decay;     /* pulse width of decay for trapezoidal pulses */
  int *pw;        /* pulse width (if trapezoidal, pulse width of center
                                         section) */
  float *amps;    /* starting amplitude of a trapezoidal pulse */
  float *amp;     /* amplitude (if trapezoidal, amplitude of ramp and left
                                         side of flat top) */
  float *ampd;    /* starting amplitude of decay ramp and right side amplitude
                                         of flat top for trapezoidal pulse */
  float *ampe;    /* ending amplitude of a trapezoidal pulse */
  /* old location of "float power" field  */
  char *gradfile; /* external grad filename */
  int num;        /* quantity of this gradpulse used */
  float scale;    /* gradient heating scale factor (e.g. phase encoding) */
  /* time and tdelta are for future use: */
  int *time;      /* location of pulse in time */
  int tdelta;     /* Time delta in microseconds in between multiple occurances
                                         of the pulse */
  float powscale; /* gradient driver current scale factor
                                     (<x,y,z>fs/target)      */
  /* For internal pulses, the function minseqgrddrv computes and fills in the
         following fields. They are NOT scaled by the powscale field.
         For external pulses, the programmer must fill these in with the 
         appropriate pulse properties. Note: for external pulses, the values
         must be normalized by the pulse width and the square of the 
         amplitude.                                          */
  float power;    /* total power in units of Ampere^2 usec   */
  float powpos;   /* positive power in units of Ampere^2 usec  */
  float powneg;   /* negative power in units of Ampere^2 usec  */
  float powabs;   /* absolute power in units of Ampere usec    */
  float amptran;  /* ampere transitions in units of Ampere     */
  int pwm;      /* pulse width modulation time               */
  int bridge;     /* bridge flag: 1 -- left or right crusher; 
                                  2 -- 180 slice select; 
                                  0 -- no bridge.   */ 
  float intabspwmcurr; /* Integral of the absolute value of the
                          current during the ramps. This is used for
                          gradient heating with SGD */
} GRAD_PULSE;   /* merged 55 bch into vmx. YH 10/14/94 */

typedef char EXTERN_FILENAME[80];
typedef char *EXTERN_FILENAME2;
/*
  Constants below are used above for the field ptype
*/

#define G_RAMP 1
#define G_TRAP 2
#define G_SIN  3      /* Half sin , 0 offset */
#define G_CONSTANT 4
/*#define G_SINPHASE 5 */ /* Phase encoding sin wave 
		        (varying amplitude ) */
#define G_ARBTRAP 5 /* Trapezoid with arbitrary start and
                       ending amplitudes and a possible
                       slope to the middle portion of the waveform */
#define G_USER 6     /* User defined.  Use power field. */
#define G_EMPTY -1   /* instructs CV routine to ignore this struct */

/* merged 55 bch into vmx. changed from 25 to 50. YH 10/14/94 */
#define MAX_GRADX_NUM 50 
#define MAX_GRADY_NUM 50
#define MAX_GRADZ_NUM 50
#define MAX_RFPULSE_NUM 50

/* 
  Structure RF_PULSE is used by the rf amplifier heating calcs
  and SAR calcs.  PSD keeps track of the type and quantity of 
  RF pulses used.

  isodelay structure tag is now provided and is intended to
  replace usage of the off90 CV.  It is the time from the zero
  phase reference of the pulse (where gradient phase bookkeeping begins)
  to its end.
  */

/* 3/13/95 YI  changed for new system safety */

typedef struct {
  int *pw;        /* pulse width */
  float *amp;     /* amplitude */
  float abswidth; /* calculated RF absolute width */
  float effwidth; /* calculated RF effective width */
  float area;     /* zero momemt of pulse */ 
  float dtycyc;   /* max % of pulse width above 23% and in any 1  lobe */
  float maxpw;    /* max % of time rf pulse is above 0 amp */
  int num;        /* quantity of this type of RF pulse */
  float max_b1;   /* peak B1 in G under standard conditions */
  float max_int_b1_sq;   /* peak integral B1^2 in GG-msec under standard conditions */
  float max_rms_b1;      /* peak RMS B1 in G under standard conditions */ 
  float nom_fa;   /* flip angle on resonance under standard conditions. */
  float *act_fa;  /* desired flip angle */
  float nom_pw;   /* pulse duration under standard conditions */
  float nom_bw;   /* pulse bandwidth under standard conditions */
  unsigned int activity; /* bitmask showing when pulse is used */
  unsigned char reference; /* flag for pulse used in TG setting */
  int   isodelay; /* time in usec from the zero phase reference of pulse
				     to its end*/
  float scale;    /* duty cycle scale factor */
  int *res; /* pulse resolution *//* vmx 3/13/95 YI changed from short to int */
  int extgradfile; /* TRUE = rfpulse uses external gradient waveform file */
} RF_PULSE;

/* 3/13/95 YI  added for new system safety */

/*********************************************************************
 * Structure RF_PULSE_INFO is used by HOST and IPG to track rf pulse
 * scaling and resolution when large patients cause system safety
 * violations. See 5.5 PSD SYSTEM SAFETY SDD for more specific explanation.
 * The structure is defined in @ipgexports, initialized in HOST by
 * scalerfpulses(), and used by IPG in pulsegen to scale rfpulses using
 * linear interpolation in stretchpulse() routine.
 *********************************************************************/
typedef struct {
  int  change;  /* PSD_ON: rfpulse scaling required, PSD_OFF: no scaling required */
  int  newres;  /* scaled resolution of rfpulse if maxB1 of rf amplifier violated */
} RF_PULSE_INFO;


/* Pulse activity masks */
#define PULSE_OFF 0
#define CFL_ON 1
#define CFL_HAD 2
#define CFH_ON 4
#define CFH_HAD 8
#define MPS1_ON 16
#define MPS1_HAD 32
#define MPS2_ON 64
#define MPS2_HAD 128
#define APS1_ON 256
#define APS1_HAD 512
#define APS2_ON 1024
#define APS2_HAD 2048
#define SCAN_ON 4096
#define SCAN_HAD 8192
/*#define TEST_ON 16384
#define TEST_HAD 32768*/
#define FTG_ON  16384  /* merged 55 bch into vmx. YH 10/14/94 */
#define FTG_HAD 32768
#define AUS_ON 65536
#define AUS_HAD 131072
#define TEST_ON 262144
#define TEST_HAD 524288 /* end of 5.5 changes. */

/* Flow comp axis codes */
#define XGRADFC 1
#define ZGRADFC 2

/* Ramp pulse directions */
#define PSD_POSRAMP 1
#define PSD_NORAMP 0
#define PSD_NEGRAMP -1

/* constants for TRAPEZOID2 macro */
#define TRAP_RAMPA 1
#define TRAP_CONST 2
#define TRAP_RAMPD 4
#define TRAP_SLOPED 8
#define TRAP_ALL 7
#define TRAP_ALL_SLOPED 15
/* Ratio of trapezoidal phase encoding flattop amplitudes.
   Equalt to 1.0 - 64.0/max_pg_wamp */
#define PSDRAMPEDTRAP 0.998047

#define PHASESTEP32 32

/* constants for slice quantity */
#define PSD_SLQUANT8 8
#define PSD_SLQUANT16 16
#define PSD_SLQUANT32 32
#define PSD_SLQUANT64 64
 
/* Default number of filter prefills */
#define DEFPREFILLS 129
 
/* constants for slice quantity */
#define PSD_SLQUANT8 8
#define PSD_SLQUANT16 16
#define PSD_SLQUANT32 32
#define PSD_SLQUANT64 64
 
/* opbloptimize defines */
#define PSD_OBL_RESTRICT 0
#define PSD_OBL_OPTIMAL 1

/* echo planar constants ***************************//* 3/13/95 YI */

/* k-space trajectory constants */
/* These indicate sense (or direction) only */
#define PSD_TOP_DOWN 0    /* top-to-bottom */
#define PSD_CENTER_OUT 1  /* center-to-top/center-to-bottom */
#define PSD_BOTTOM_UP 2   /* bottom-to-top */

/* ky fraction constants */
#define PSD_FULL_KY 0
#define PSD_FRACT_KY 1

/* alternation factor constants */
#define PSD_ALT_NONE 0
#define PSD_ALT_ODD_EVEN 1
#define PSD_ALT_HALVES 2
#define PSD_ALT_SUBGROUPS 3
/* end echo planar constants ***************************/
 
/* GRAM IDENTIFIERS */
#define PSD_NOGRAM      0
#define PSD_GRAM1       1
#define PSD_GRAM2       2
 
/* SR modes */
#define PSD_SR17	17	
#define PSD_SR20	20	
#define PSD_SR77	77	
#define PSD_SR120	120	
#define PSD_SR150	150	
#define PSD_SR230	230	

/* SR amplitude factors  - used to scale loggrd structure */
#define SR17_FACTOR     0.95
#define SR20_FACTOR     1.0
#define SR77_FACTOR     1.0
#define SR120_FACTOR    1.0
#define SR230_FACTOR    1.0

/* Gradient Coil Specifiers */
#define PSD_55_CM_COIL 1
#define PSD_60_CM_COIL 2  /* BRM */
#define PSD_CRM_COIL 6  

 /* bit map of GRAM axis for sigrammode  *//* 3/13/95 YI */
#define XGRAM 1  /* X GRAM */
#define YGRAM 2  /* Y GRAM */
#define ZGRAM 4  /* Z GRAM */

/*
  Structure to contain slice ordering within the pass
  and the pass number.
  */
  
typedef struct {
  short slloc;  /* prescribed location */
  short slpass; /* pass phase is acquired in */
  short sltime; /* time order within pass slice is acquired */
} DATA_ACQ_ORDER;

/*
  Structure to record each slice's loacation,  receive offset 
  location, and rotation matrix.
  */

typedef struct {
  float optloc; /* distance in mm from isocenter */
  float oprloc; /* distance in mm from receive center */
  float opphasoff; /* distance in mm from isocenter in the phase direction*/
  short  oprot[10]; /* rotation matrix */
  } SCAN_INFO;

typedef struct {
  float rsptloc;   /* location in mm from isocenter */
  float rsprloc;   /* receive location in mm */
  float rspphasoff; /*distance in mm from isocenter in the phase direction*/
  int slloc;       /* prescribed location */
 } RSP_INFO;

/*
  Structure to record entry point specific enformation for the power
  monitor and receiver/exciter setup
  */

typedef struct{
  s8     epname[16];		/* name that entry point will be named */

  n8            epamph;		/* power for the head coil*/
  n8            epampb;		/* power for the body coil*/
  n8            epamps;		/* peak power for the surface coil */ 
  n8            epwidthh;	/* max pulse width for the head coil */

  n8            epwidthb;	/* max pulse width for the body coil */
  n8            epwidths;	/* max pulse width for the surface coil */ 
  n8            epdcycleh;	/* peak duty cycle for the head coil */
  n8            epdcycleb;	/* peak duty cycle for the body coil */

  n8            epdcycles;	/* peak duty cycle for the surface coil */
  n8            epsmode;	/* select exciter mode */
  n8            epfilter;	/* initial filter to use */
  n8            eprcvrband;	/* tells whether broadband is used */

  n8            eprcvrinput;	/* receiver port to use */
  n8            eprcvrbias;	/* receiver to bias */
  n8            eptrdriver;	/* tr driver control */
  n8            epfastrec;     /*  type of recevier 0=standard, 1=fast */

  s16 epxmtadd;		/* additional transmit gain to add */
  s16 epprexres;		/* prescan xres */  
  s16 epshldctrl;		/* expansion for shield cooler control */
  s16 epgradcoil;		/* indicate gradient shield mode */
  n32 eppkpower;                /* peak power */
  n32 epseqtime;                /* seq time */
  s16 epstartrec;               /* start receiver */ /* merged 55 bch into vmx. */
  s16 ependrec;                 /* end receiver */   /* YH 10/14/94             */
} ENTRY_POINT_TABLE;

/*
  Structure below is used for filters
*/

typedef struct { 
  int decimation;      /* Input decimation ratio after CERD processing */
  int tdaq;            /* time for data acquisition in microseconds */
  float bw;            /* bandwidth in KHz */
  int fname;           /* filter filename e.g 160 for filter.160 */
  int fslot;           /* filter slot for permanemt filters */
  float output_dec;    /* Final decimation after SINC interpolation */
  float cerd_tsp;      /* Sampling period in usec after CERD decimation*/
  int cerd_out_points; /* Number of points to acquire, i.e, number of CERD
                          output points */
  int fracdec;         /* Flag indicating whether fractional decimation is
                          being used for the current acquisition */
  } FILTER_INFO;

/* phase offset structure and vars.  Prior to release 5.5, this
   was declared in each individual psd */
/*  array to store calculated phase offset and sign */
typedef struct {
        int ysign;  /* sign of the phase offset */
        int yoffs;  /* calculated phase offset from rsp_info structure */
        } PHASE_OFF;


#endif /* h_cv_const_global_h */

