/*
 *  cv_const.ipgex.h
 *
 *  Do not edit this file. It is automatically generated by EPIC+.
 *
 *  Date : May 19 2000
 *  Time : 11:31:19
 */

#ifndef h_cv_const_ipgex_h
#define h_cv_const_ipgex_h

#ifdef INC4CPP
#include "epic_struct.h"
#include "em_psd_ermes.in"
#include "cv_const.global.h"
#endif

EXTERN RSP_INFO  rsp_info[DATA_ACQ_MAX]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  rsprot[TRIG_ROT_MAX][9]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  rsptrigger[TRIG_ROT_MAX]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  ipg_alloc_instr[PSD_MAX_PROCESSORS] 
#ifdef INIT
= {PSD_GRADX_INSTR_SIZE,PSD_GRADY_INSTR_SIZE,PSD_GRADZ_INSTR_SIZE,PSD_RHO1_INSTR_SIZE,PSD_RHO2_INSTR_SIZE,PSD_THETA_INSTR_SIZE,PSD_OMEGA_INSTR_SIZE,PSD_SSP_INSTR_SIZE,PSD_AUX_INSTR_SIZE} 
#endif
;

EXTERN RSP_INFO  asrsp_info[3]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  sat_rot_matrices[14][9]
#ifdef INIT
= {0} 
#endif
;

EXTERN int  TARDIS_FREQ_OFFSET
#ifdef INIT
= {0} 
#endif
;

EXTERN PHYS_GRAD  phygrd
#ifdef INIT
= {0} 
#endif
;

EXTERN LOG_GRAD  loggrd
#ifdef INIT
= {0} 
#endif
;

EXTERN LOG_GRAD  satloggrd
#ifdef INIT
= {0} 
#endif
;

EXTERN LOG_GRAD  asloggrd
#ifdef INIT
= {0} 
#endif
;

EXTERN SCAN_INFO  asscan_info[3]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  PSrot[PRESCAN_ROT_MAX][9]
#ifdef INIT
= {0} 
#endif
;

EXTERN PHASE_OFF  phase_off[DATA_ACQ_MAX]
#ifdef INIT
= {0} 
#endif
;

EXTERN int  yres_phase
#ifdef INIT
= {0} 
#endif
;

EXTERN int  yoffs1
#ifdef INIT
= {0} 
#endif
;

EXTERN int  off_rfcsz_base[DATA_ACQ_MAX]
#ifdef INIT
= {0} 
#endif
;

EXTERN SCAN_INFO  scan_info_base[1]
#ifdef INIT
= {0} 
#endif
;

EXTERN float  xyz_base[DATA_ACQ_MAX][3]
#ifdef INIT
= {0} 
#endif
;

EXTERN long  rsprot_base[TRIG_ROT_MAX][9]
#ifdef INIT
= {0} 
#endif
;

EXTERN int  rtia_first_scan_flag 
#ifdef INIT
= 1 
#endif
;

EXTERN long  _lastipgex 
#ifdef INIT
= 0 
#endif
;


#endif /* h_cv_const_ipgex_h */

