/*
 * GE Medical Systems
 * Copyright (C) 1998 The General Electric Company
 * 
 * $Source: %M% $
 * $Revision: %I% $  $Date: %G% %U% $
 * 
 * Interface file for the CV copy functions generated by ec for every PSD.
 * 
 * Language : ANSI C
 * Author   : Gabriel Fernandez
 * Date     : 18/Nov/1998
 */
/* do not edit anything above this line */

/*
 Version      Date      Author      Description
------------------------------------------------------------------------------
           18-Nov-1998  GFN         Initial version.
 */

#ifndef cvcopy_proto_h
#define cvcopy_proto_h

/* Function prototypes */
int cvcopy_firstcv ( void );
void cvuncopy_firstcv ( void );
int cv_copysize( void );

/* Public variables */
extern long _downlCV[];

#endif /* cvcopy_proto_h */
