/*
 *  epic.ipgdecl.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_epic_ipgdecl_h
#define h_epic_ipgdecl_h

/* id tags - one for MROR-WS, one for pulse sequence, 0 based */
int cont_wsid, cont_psdid;
/* time stamp to recon for MROR header */
int cont_time;
/* variable communicating to recon that real time is on */
int cont_synch;
/* stops the cont imaging after acquisition of the last pass */
int cont_stop, cont_stop_usr;
/* x, y, and z offsets from original prescription - mm units, 1/10 mm
   accuracy, range TBD */
float cont_xoffset, cont_yoffset, cont_zoffset;
/* alpha, beta, and gamma offsets from original prescription - degree
   units, 1/10 degree accuracy, range 0-360 degrees */
float cont_alpha, cont_beta, cont_gamma;

/* variable for checking scan plane offset (cont_x/y/zofset )change */
int cont_sp_changed;

/* Fix for spr MRIge46008 making sure the following prescan vars*/
/* are available for all psds */
/* The following are set by prescan upon successful completion: */
int pscR1;  /* R1 receive attenuation (dB) */
int pscR2;  /* R2 receive attenuation (barrel shift) */
int pscCF;  /* CF center frequency (Hz) */
int pscTG;  /* TG transmit gain (dB) */



#endif /* h_epic_ipgdecl_h */

