/*
 *  epic.ipgex.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_epic_ipgex_h
#define h_epic_ipgex_h

/* *******************
   ipgexport
   ******************* */
RSP_INFO rsp_info[DATA_ACQ_MAX]= {0};
/* changed following 2 parameters from short to int. YH */
long rsprot[TRIG_ROT_MAX][9]= {0};    /* rotation matrix for this slice */
long rsptrigger[TRIG_ROT_MAX]= {0};   /* trigger type */

long ipg_alloc_instr[PSD_MAX_PROCESSORS] = {
PSD_GRADX_INSTR_SIZE,
PSD_GRADY_INSTR_SIZE,
PSD_GRADZ_INSTR_SIZE,
PSD_RHO1_INSTR_SIZE,
PSD_RHO2_INSTR_SIZE,
PSD_THETA_INSTR_SIZE,
PSD_OMEGA_INSTR_SIZE,
PSD_SSP_INSTR_SIZE,
PSD_AUX_INSTR_SIZE};


RSP_INFO asrsp_info[3]= {0};   /* transmit, receive locations for autoshim */
/* changed from short to in.  YH */
long sat_rot_matrices[14][9]= {0}; /* rotation matrices for sp sat */
int TARDIS_FREQ_OFFSET= {0};

/* following parameters are new for 55 *//* added  YH 10/14/94 */
PHYS_GRAD phygrd= {0};         /* physical gradient characteristics */
LOG_GRAD  loggrd= {0};         /* logical gradient characteristics */
LOG_GRAD  satloggrd= {0};      /* logical gradient chars. for graphic sat */
 
LOG_GRAD  asloggrd= {0};       /* logical gradient characteristics */
SCAN_INFO asscan_info[3]= {0};
/* MRIge43968 (BJM): redefined from long PSrot[10] to the following.. */
/* redefined to long PSrot from int as per CARDIAC34.01 version */
long PSrot[PRESCAN_ROT_MAX][9]= {0};             /* prescan rotation matrix */
 
PHASE_OFF phase_off[DATA_ACQ_MAX]= {0};
int yres_phase= {0};  /* offset in phase direction in mm */
int yoffs1= {0};  /* intermediate phase offset variable */

/*** RT ***/
/* For use in SpSat.e */
/* storage of original concat sat offsets */
int off_rfcsz_base[DATA_ACQ_MAX]= {0};
/* storage of original matrix location */
SCAN_INFO scan_info_base[1]= {0};

/* For use in Prescan.e and psds */
/* storage of original x, y, and z offsets */
float xyz_base[DATA_ACQ_MAX][3]= {0};
/* storage of original rotation matrices */
long rsprot_base[TRIG_ROT_MAX][9]= {0};
/*** End RT ***/


/* Begin RTIA */
int rtia_first_scan_flag = 1 ; 
/* End RTIA */

long _lastipgex = 0;

#endif /* h_epic_ipgex_h */

