/*
 *  epic.allcv.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_epic_allcv_h
#define h_epic_allcv_h

long _firstcv = 0;
/* *************************************************
   REQUIRED CVS
   ************************************************ */

/* ****************************
   Patient/Study Parameters 
   ************************** */
float opweight = 50 ;

/* ****************************
   Patient Position Parameters 
   ************************** */
int opcoil = PSD_HEAD 
;

int opentry = 1 
;

int oppos = 1 
;

/* ************************** 
   Imaging Parameter CVs 
   *************************** */
int oppseq = 1 
;

int opcgate = 0 
;

int opexor = 0 ;

int opfcomp = 0 ;

int opplane = PSD_AXIAL 
;

int opgrx = 0 
;
int opgrxroi = 0 

;
int opobplane = PSD_AXIAL 
;
int opnopwrap = 0 
;
int opimode = PSD_2D 
;
int opsat = 0 
;
int opptsize = 2 
;
int oppomp = 0 
;
int opscic = 0 
;
int oprect = 0 
;
int opsquare = 0 
;
int opvbw = 0 
;
int opblim = 0 
;
int opfast = 0 

;
int opcs = 0 

;
int opdeprep = 0 

;
int opirprep = 0 

;
int opmph = 0 

;
int opautotr = 0 
;
int opphcor = 0 
;
/* cvs for Faster sequence Multi-Phase option */
int opacqo = 1 
;
int opfphases = PHASES_MIN 
;
int opsldelay = 50000 
;

int opmt = 0 

;

/* *****************
   Saturation CVs 
   **************** */
int opsatx = 0 
;

int opsaty = 0 
;

int opsatz = 0 
;

float opsatxloc1 = 9999 
;
float opsatxloc2 = 9999 
;
float opsatyloc1 = 9999 
;
float opsatyloc2 = 9999 
;
float opsatzloc1 = 9999 
;
float opsatzloc2 = 9999 
;

float opsatxthick = 80 
;
float opsatythick = 80 
;
float opsatzthick = 80 
;

int opsatmask = 0 
;
int opfat = 0 
;
int opwater = 0 
;
int opccsat = 0 
;

/**********************************************
 These are for graphic sats.
***********************************************/
int opexsatmask = 0  
;
float opexsathick1 = 80 
;
float opexsathick2 = 80 
;
float opexsathick3 = 80 
;
float opexsathick4 = 80 
;
float opexsathick5 = 80 
;
float opexsathick6 = 80 
;

float opexsatloc1 = 9999 
;
float opexsatloc2 = 9999 
;
float opexsatloc3 = 9999 
;
float opexsatloc4 = 9999 
;
float opexsatloc5 = 9999 
;
float opexsatloc6 = 9999 
;

int opexsatparal = 0 
;

/*
   The opexsatoff<> cvs are for future use when targeted sat pulses
   are implemented 
*/
int opexsatoff1 = 0 
;
int opexsatoff2 = 0 
;
int opexsatoff3 = 0 
;
int opexsatoff4 = 0 
;
int opexsatoff5 = 0 
;
int opexsatoff6 = 0 
;
int opexsatlen1 = 480 
;
int opexsatlen2 = 480 
;
int opexsatlen3 = 480 
;
int opexsatlen4 = 480 
;
int opexsatlen5 = 480 
;
int opexsatlen6 = 480 
;
/* end of unused targeted sat cvs */

/* default sat band thicknesses */
float opdfsathick1 = 80 
;
float opdfsathick2 = 80 
;
float opdfsathick3 = 80 
;
float opdfsathick4 = 80 
;
float opdfsathick5 = 80 
;
float opdfsathick6 = 80 
;

/* *****************
   Vascular CVs
   ***************** */
float opvenc = 50.0 ;
int opflaxx = 0 ;
int opflaxy = 0 ;
int opflaxz = 0 ;
int opflaxall = 0 ;
int opproject = 0 ;
int opcollapse = 1 
; 
int oprlflow = 0 
;
int opapflow = 0 
;
int opsiflow = 0 
;
int opmagc = 1 
;
int opflrecon = 0 ;
int project = 0 ;
int vas_ovrhd = 0 ;
int slice_col = 1 
; 
int phase_col = 0 
;
int read_col = 0 
;
int mag_mask = 1 
;
int phase_cor = 1 
;
int extras = 0 
;
int mag_create = 1 
;
int rl_flow = 0 
;
int ap_flow = 0 
;
int si_flow = 0 
;
int imagenum = 1 ;
int motsa_ovrhd = 0 ;
int oprampdir = 0 ;
int opfcaxis = 0 ;


/* **************
   Cardiac CVs 
   ************* */

int ophrate = 60 


;
int oparr = 10 
;
int ophrep = 1 
;

int optdel1 = 20000 
;

int optseq = 1 
;

int opphases = 1 
;

int opcardseq = 0 
;

int opmphases = 0 
;

int oparrmon = 1 
;

int opvps = 8 
;

/* *******************
   Scan Timing CVs 
   ******************* */

int opetl = 8 
;

int opnecho = 1 
;

int opautote = 0 ;

int opte = 25000 
;

int opte2 = 50000 
;
/* cv for Faster sequence TE selection */
int optefw = 0 
;

int opti = TI_MIN 
;
			 
int opirmode = SIRMODE 
;

int optr = 400000 
;

float opflip = 90 
;

/* *********************
   Scanning Range CVs 
******************** */		

float opfov = FOV_MAX 
;

float opphasefov = 1 
;

float opfreqfov = 1 
;

int opslquant = 1 
;

int opileave = 0 
;

float opslthick = 5 
;
   
float opslspace = 10 
;

/* 0 is non coaxial
   1 is coaxial through isocenter
   2 is coaxial not through isocenter */

int opcoax = 1 
;

float opvthick = 320 
;

int opvquant = 1 
;

int opovl = 0 ;

/* ***********************
   Graphic ROI CVs
   ********************** */


float oplenrl = 0 
;
float oplenap = 0 
;
float oplensi = 0 
;

float oplocrl = 0 
;
float oplocap = 0 
;
float oplocsi = 0 
;

float oprlcsiis = 1 
;
float opapcsiis = 2 
;
float opsicsiis = 3 
;



/* ***********************
   Acquisition Time CVs 
   ********************** */

int opxres = 256 
;

int opyres = 128 
;

float opnex = 1 ;

int opslicecnt = 0 
;

int opspf = 0 
;

int opcfsel = 0 
;
/* oprbw is receive bw for echoes 2-4 for 1.5 T, receive bw for 1st echo
for 0.5 T */
float oprbw = 16.0 
;
float oprbw2 = 16.0 
;


/* *************
   Cine CVs 
   ************* */
int opchrate = 100 


;
int opcphases = 1 
;
int opclocs = 1 
;

/* *******************
    Multi Coil CVs
   ******************* */
int opmctr = 0 ;
int opmultrecv = 0 ;


/* *******************
    Spectroscopy CVs
   ******************* */
int specnuc = 1 ;
int specpts = 256 ;
int specwidth = 2000 ;
int specnavs = 1 ;
int specnex = 2 ;
int specdwells = 1 ;
int acquire_type = 1 ;

/* ********************
   Spectro Hardware 
   ******************** */
int pixmtband = AMP_ERBTEC ;
int pibbandfilt = 0 ;


/* *********************
   Autoshim CVs
   ********************* */
int asslquant = 1 
;
float asflip = 20 
;
float asslthick = 10 
;
int asxres = 256 
;
int asyres = 128 
;
int asbaseline = 8 
;
int asrhblank = 4 
;
int asptsize = 4 
;

int opascalcfov = 0 ;

/* merged 55 bch into vmx.  YH  10/13/94 */
/* ***************************
    EPI CVs
   *************************** */

int opepi = 0 
;

int optlrdrf = 0 
;

int opnshots = 1 
;

/* merged 55 bch into vmx.  YH  10/13/94 */
/* ***************************
   Resp Trig CVs
   *************************** */
int oprtcgate = 0 ;
int oprtrate = 12 
;

int oprtrep = 1 
;

int oprttdel1 = 20000 
;
     
int oprttseq = 1 
;
 
int oprtcardseq = 0 
;
 
int oprtarr = 10 
;
 
int oprtpoint= 10 ;

/* New imaging options...initially for spiral imaging only (NDG) */
int opssrf = 0 ;
int opt2prep = 0 ;
int opspiral = 0 
;

/* pi values for spiral */
int piresol = 0 ;
int pioverlap = 0 
;
 
 
/* **********************
   Lx: FLAIR/FSE CV
   ********************** */
int opfulltrain = 0 ;

/* **********************
   Lx: FMPVAS/FGRE CVs
   ********************** */
int pi_neg_sp = 0 
;
float piisvaldef = 2 
;

/* **********************
   Clock Operation CVs 
   ********************** */
int pidmode = 0 ;
int piviews = 0 ;
int piclckcnt = 1 ;
float avmintscan = 0 ;
int pitslice = 0 ;
float pitscan = 0 ;

/* **********************
   Image Creation CVs 
   ********************** */
int pisaveinter = 0 
;
int pivextras = 0 
;
int pinecho = 0 
;

/* *****************************
   IPG Needs for Table Position 
   ***************************** */
float piscancenter = 0 ;

/* ******************
   Service CVs
   ***************** */
int pismode = 0 
;


/* ******************
   Image header CVs
   ****************** */
int ihtr = TR_MIN 
;
int ihti = 0 
;
int ihtdel1 = MIN_TDEL1 
;
float ihnex = 1 
;
float ihflip = 90 
;
int ihte1 = 0 
;
int ihte2 = 0 
;
int ihte3 = 0 
;
int ihte4 = 0 
;
int ihte5 = 0 
;
int ihte6 = 0 
;
int ihte7 = 0 
;
int ihte8 = 0 
;
int ihte9 = 0 
;
int ihte10 = 0 
;
int ihte11 = 0 
;
int ihte12 = 0 
;
int ihte13 = 0 
;
int ihte14 = 0 
;
int ihte15 = 0 
;
int ihte16 = 0 
;

float ihvbw1 = 16.0 
;
float ihvbw2 = 16.0 
;
float ihvbw3 = 16.0 
;
float ihvbw4 = 16.0 
;
float ihvbw5 = 16.0 
;
float ihvbw6 = 16.0 
;
float ihvbw7 = 16.0 
;
float ihvbw8 = 16.0 
;
float ihvbw9 = 16.0 
;
float ihvbw10 = 16.0 
;
float ihvbw11 = 16.0 
;
float ihvbw12 = 16.0 
;
float ihvbw13 = 16.0 
;
float ihvbw14 = 16.0 
;
float ihvbw15 = 16.0 
;
float ihvbw16 = 16.0 
;

int ihnegscanspacing = 0 
;

int ihoffsetfreq = 1200 
;

/* *******************
   Custom Scan Schema CVs
   ****************** */
int opuser_usage_tag = 0x00000000 
;
int rhuser_usage_tag = 0x00000000 
;
int rhFillMapMSW = 0x00000000 
;
int rhFillMapLSW = 0x00000000 
;

/* *******************
   Recon Header CVs
   ****************** */
int rhbline = 0 
;
int rhblank = 4 
;
int rhnavs = 1 
;
int rhnslices = 1 
;
int rhnframes = 256 
;
int rhfrsize = 256 
;
int rhnecho = 1 
;

/* ********************************
   Bit patterns for rhtype 
   ------------------------------
   bit 0  Set if chopper data
   bit 1  Set if CINE
   bit 2  Set if SHIM
   bit 3  Set if GRASS
   bit 4  Set for fractional processing
   bit 5  Set for strip scan Y
   bit 6  Set for 3-D processing
   bit 7  Set if exorcist
   bit 8  Set if NPW
   bit 9  Set if NFW
   bit 10 Set if strip scan X.
   bit 12 No longer used.
   bit 13 Set if 3/4 nex.
   bit 14 Set if pomp
   ****************************** */
int rhtype = 0 
;
/* ********************************
   Bit patterns for rhtype1
   ------------------------------
   bit 0  Set if regular recon
   bit 1  Set if homodyne recon
   bit 2  Set if nex table per echo is required
   bit 3  Set if mulit-coil superframe
   bit 4  Set if 3D multi-slab
   bit 5 on, bit 6 off  Maximum intersity pixel collapse overlap processing
   bit 5 off, bit 6 on  Minimum intersity pixel collapse overlap processing
   bit 5 on, bit 6 on   Average intersity pixel collapse overlap processing
   bit 7  Set for "fast phase off" in phase-contrast scans
   bit 8  Set if automatic scan/pass detection scheme is enabled.  If set,
           then data acquisition will assert scan and pass packets based on
           frame counter limits.  These limits are set by:
               rhrefframes and rhrefframep for reference scan acquisitions
               rhscnframe and repasframe for other entry points (except
                 prescan)
           
  
   ******************************** */
int rhtype1 = 0 
;


/* merged 55 bch into vmx.  YH  10/13/94 */
/* ******************************
   Bit patterns for rhformat
   -----------------------------
   bit 0 set if no grad warp is desired (1)
   bit 1 set if no fermi filtering is desired (2)
   bit 2 For 3D, set if RF is chopped Z-encode (4)
   bit 3 For 3D, set if RF is chopped on Y encode (8)
   bit 4 set if IIC (opscic == PSD_ON) (32)
   bit 5 set if epi dab packet is used (64)
   bit 11 set if row flip file (/usr/g/bin/rowflip.param) is used (2048)
   ********************************************* */
int rhformat = 0 
;
int rhptsize = 2 
;
int rhnpomp = 1 
;

/* ******************************
   Bit patterns for rhrcctrl
   ------------------------------
   bit 0 set for magnitude images   ; RHRCMAG  = 1
   bit 1 set for phase images       ; RHRCPHS  = 2
   bit 2 set for I magnitude images ; RHRCIMAG = 4
   bit 3 set for Q magnitude images ; RHRCQMAG = 8
   bit 4 set for compressed images  ; RHRCCOMP = 16
   bit 7 set for raw image recon    ; RHRCRAW  = 128
   changed for 7.0 from 17 to 1..gp
   ********************************************* */
int rhrcctrl = 1 
;

/* ******************************
   bit patterns for rhdacqctrl
   ----------------------------
   bit 0	0= NO_REC data, 1=RAW data
   bit 1	Set if even echo phase flip desired.
   bit 2	Set if odd echo phase flip desired.
   bit 3	Set if even echo frequency flip desired.
   bit 4	Set if odd echo frequency flip desired.
   bit 5	Set if RAW collection without DAB SSP packets is desired.
   bit 6	Set if RAW collection should wrap around to the top of the
		buffer if overflow occurs.
   bit 10       set if fcine echotrain data acq. mode is used.
                MRIge56094                RH_FCINE_ET = 1024
   bit 11       Set if passthrough data acq. mode is used.; 
                                          RH_PASS_THROUGH_CERD_FLAG = 2048
   ********************************************* */
int rhdacqctrl = 2 
;


/* ******************************
   bit patterns for rhexecctrl
   ------------------------------
   bit 0= 1	Set if Auto display desired
   bit 1= 2	Set if auto lock of raw/no_rec files desired
   bit 2= 4	Set if auto perm desired ( BAM memory not released )
   bit 3= 8	Set if images should be transferred to disk
   bit 4= 16	Set if images should be saved in BAM memory
   bit 5= 32	Don't use
   bit 6= 64	Set if intermediate multi coil images are to be saved
 * ********************************************** */
int rhexecctrl = 9 
;


/* *********************************
   bit patterns for FEEDER control
   ---------------------------------
   bit 0	0= feed DAB, 1= feed filters.
   bit 1	0= locked, 1= unlocked
   bit 2	0= see bit 1, 1= use algorithm
   bit 3	Set if timing simulation desired
 * ********************************************** */
int rhfdctrl = 0 
;


float rhxoff = 0 
;
float rhyoff = 0 
;
int rhrecon = 0 
;
int rhdatacq = 0 
;
int rhvquant = 0 
;		
int rhslblank = 2 
;
int rhhnover = 0 
;
int rhoscans = 0 
;
int rhddaover = 0 
;
float rhzeroph = 128.5 
;
float rhalpha = 0.46 
;
float rhnwin = 0 
;
float rhntran = 2 
;
float rhfermw = 10 
;
float rhfermr = 128 
;
float rhferme = 1 
;
float rhclipmin = 0 
;
float rhclipmax = 16383 
;
float rhdoffset = 0 
;
int rhudasave = 0 
;
int rhsspsave = 0 
;
float rhscalei = 1 
;
float rhscaleq = 1 
; 
int rhnpasses = 1 
;
int rhrawsize = 10000 
;
int rhincrpass = 1 
;
int rhinitpass = 1 
;
int rhmethod = 0 
;
int rhdaxres = 256 
;
int rhdayres = 256 
;
int rhrcxres = 256 
;
int rhrcyres = 256 
;
int rhimsize = 256 
;
float rhuser0  = 0 ;
float rhuser1  = 0 ;
float rhuser2  = 0 ;
float rhuser3  = 0 ;
float rhuser4  = 0 ;
float rhuser5  = 0 ;
float rhuser6  = 0 ;
float rhuser7  = 0 ;
float rhuser8  = 0 ;
float rhuser9  = 0 ;
float rhuser10 = 0 ;
float rhuser11 = 0 ;
float rhuser12 = 0 ;
float rhuser13 = 0 ;
float rhuser14 = 0 ;
float rhuser15 = 0 ;
float rhuser16 = 0 ;
float rhuser17 = 0 ;
float rhuser18 = 0 ;
float rhuser19 = 0 ;
float rhuser20 = 0 ;
float rhuser21 = 0 ;
float rhuser22 = 0 ;
float rhuser23 = 0 ;
float rhuser24 = 0 ;
float rhuser25 = 0 ;
float rhuser26 = 0 ;
float rhuser27 = 0 ;
float rhuser28 = 0 ;
float rhuser29 = 0 ;
float rhuser30 = 0 ;
float rhuser31 = 0 ;
float rhuser32 = 0 ;
float rhuser33 = 0 ;
float rhuser34 = 0 ;
float rhuser35 = 0 ;
float rhuser36 = 0 ;
float rhuser37 = 0 ;
float rhuser38 = 0 ;
float rhuser39 = 0 ;
float rhuser40 = 0 ;
float rhuser41 = 0 ;
float rhuser42 = 0 ;
float rhuser43 = 0 ;
float rhuser44 = 0 ;
float rhuser45 = 0 ;
float rhuser46 = 0 ;
float rhuser47 = 0 ;
float rhuser48 = 0 ;

int rhdab0s = 0 
;
int rhdab0e = 0 
;
float rhctr = 1 
;
float rhcrrtime = 1 
;
int rhcphases = 1 
;
int rhovl = 0  
;

/* **********************************
   Vascular Recon CVs 
   ********************************** */

/* **********************************
   Vascular Recon Types
   1: vascular
   2: phase contrast scan
   4: unused
   8: 2 set processing
   16: anti alias algorithm
   32: phase contrast bit 1
   64: phase contrast bit 2
   128: apply noise suppression mask
   256: display magnitude image
   512: display physical x location
   1024: display physical y location
   2048: display physical z location
   4096: collapse logical z
   8192: collapse logical x
   16384: collapse logical y
   32768: vinnie 1 slice, 2 set
   65536: vinnie 1 slice, 4 set
   131072: vinnie 2 slice, 2 set
   ****************************************** */
int rhvtype = 0 
;

float rhvenc = 0 
;
float rhvcoefxa = 0 
;
float rhvcoefxb = 0 
;
float rhvcoefxc = 0 
;
float rhvcoefxd = 0 
;
float rhvcoefya = 0 
;
float rhvcoefyb = 0 
;
float rhvcoefyc = 0 
;
float rhvcoefyd = 0 
;
float rhvcoefza = 0 
;
float rhvcoefzb = 0 
;
float rhvcoefzc = 0 
;
float rhvcoefzd = 0 
;

/* The following are flow to static translation for phase contrast 
   scans if the phase correction bits are set or noise suppression or display
   magnitude bits are set. */

float rhvmcoef1 = 0 
;
float rhvmcoef2 = 0 
;
float rhvmcoef3 = 0 
;
float rhvmcoef4 = 0 
;

/* *********************
   Asymmetric FOV cvs
   ********************* */
float rhphasescale = 1 
;

float rhfreqscale = 1 
;

/* Raw image recon */
int rawmode = 0 ;
							   
/************************/
/* Refernce Scan/EPI recon cvs */
/************************/

int rhileaves = 1 
;

int rhkydir = 0 
;

int rhalt = 0 
;

int rhreps = 1 
;

int rhref = 1 ;

/****************************************/
/* EPI Phase Correction recon header CVs */
/****************************************/

int rhpcthrespts = 2 
;
                  
int rhpcthrespct = 15 
;
 
int rhpcdiscbeg = 0 
;
 
int rhpcdiscmid = 0 
;
 
int rhpcdiscend = 0 
;
 
int rhpcileave = 0 
;
 
int rhpcextcorr = 0 
;
 
int rhrefframes = 0 
;
/* to avoid compiling error on IFCC   3/17/95 YI */
int rhpcsnore = 0 
;

                                     
int rhpcspacial = 0 
;
 
int rhpctemporal = 0 
;
 
float rhpcbestky = 64.0 
;
 
int rhhdbestky = 0 ;
/* to avoid compiling error on IFCC   3/17/95 YI */
int rhpcinvft = 0 
;
 
int rhpcctrl = 0 
;
/* to avoid compiling error on IFCC   3/17/95 YI */
int rhpctest = 0 
;

int rhpcgraph = 0 ;

int rhpclin = 0 ;
 
int rhpclinnorm = 0 
;
 
int rhpclinnpts = 0 
;
 
int rhpclinorder = 2 
;
 
int rhpclinfitwt = 0 
;
 
int rhpclinavg = 0 
;
 
int rhpccon = 0 ;
 
int rhpcconnorm = 0 
;
 
int rhpcconnpts = 2 ;
 
int rhpcconorder = 2 
;
 
int rhpcconfitwt = 0 
;
 
/****************************************/
/* VRGF recon header CVs */
/****************************************/
 
int rhvrgfxres = 128 
;
int rhvrgf = 0 ;

/****************************************/
/* Bandpass correction recon header CVs */
/****************************************/
 
int rhbp_corr = 0 
;
 
float rhrecv_freq_s = 0.0 
;
 
float rhrecv_freq_e = 0.0 
;
 
int rhhniter = 0 
;
 
int rhfast_rec = 0 
;


/*************************************/
/* Spiral gridding recon related CVs */
/*************************************/
int rhgridcontrol = 0 ;
int rhb0map = 0 ;
int rhtediff = 0 ;
float rhradiusa = 0 ;
float rhradiusb = 0 ;
float rhmaxgrad = 0.0 ;
float rhslewmax = 0.0 ;
float rhscanfov = 0.0 ;
float rhtsamp = 0.0 ;
float rhdensityfactor = 0.0 ;
float rhdispfov = 0.0 ;
int rhmotioncomp = 0 ;

/* **********************
   op user CVs
   ********************* */
int pititle = 0 ;
float opuser0  = 0 ;
float opuser1  = 0 ;
float opuser2  = 0 ;
float opuser3  = 0 ;
float opuser4  = 0 ;
float opuser5  = 0 ;
float opuser6  = 0 ;
float opuser7  = 0 ;
float opuser8  = 0 ;
float opuser9  = 0 ;
float opuser10 = 0 ;
float opuser11 = 0 ;
float opuser12 = 0 ;
float opuser13 = 0 ;
float opuser14 = 0 ;
float opuser15 = 0 ;
float opuser16 = 0 ;
float opuser17 = 0 ;
float opuser18 = 0 ;
float opuser19 = 0 ;
float opuser20 = 0 ;
float opuser21 = 0 ;
float opuser22 = 0 ;
float opuser23 = 0 ;
float opuser24 = 0 ;
float opuser25 = 0 ;
float opuser26 = 0 ;
float opuser27 = 0 ;
float opuser28 = 0 ;
float opuser29 = 0 ;
float opuser30 = 0 ;
float opuser31 = 0 ;
float opuser32 = 0 ;
float opuser33 = 0 ;
float opuser34 = 0 ;
float opuser35 = 0 ;
float opuser36 = 0 ;
float opuser37 = 0 ;
float opuser38 = 0 ;
float opuser39 = 0 ;
float opuser40 = 0 ;
float opuser41 = 0 ;
float opuser42 = 0 ;
float opuser43 = 0 ;
float opuser44 = 0 ;
float opuser45 = 0 ;
float opuser46 = 0 ;
float opuser47 = 0 ;
float opuser48 = 0 ;

/* *************************************************
   MORE REQUIRED CVS 
   ************************************************ */

int pishldctrl= PSD_OFF 
;

int pinolr=PSD_OFF 
;

int pinoadc=PSD_OFF 
;

int pimixtime = 0 ;

int psd_board_type = 0 ;

/* vmx 1/10/95 YI moved here from reqexport section */
int cfcoilres=0;      /* coil resistance, 1LSB = 16ohm */
int cftxgate0=0;      /* Indicates 0 degree transmit gate enable: 0=Disable,
		       1=Enable */
int cftxgate90=0;      /* Indicates 90 degree transmit gate enable: 0=Disable,
		       1=Enable */
int cfcoilportvu=0;    /* Indicates coil port voltage Upper Byte */
int cfcoilportvl=0;    /* Indicates coil port voltage Lower Byte */
int cfcoilbias=0;      /* Coil Bias select: 0=Disable, 1=Head, 2=Body,
			3=Surface */
int cfgradcoil = 2;  /* Indicate gradient coil type : 1:CRD 2:Roemer
                        101:HGC 102:Vectra 103:Permanent */
/* end vmx */

/* *************************************************
   MORE REQUIRED CVS
   ************************************************ */

/*  ADD NEW CVs HERE (before next "@") UNTIL YOU CAN BUMP UP THE
	REVISION NUMBER */

int rhrefframep = 0 
;
int rhscnframe = 0 
;
int rhpasframe = 0 
;
 
/* *************************************************
   MORE REQUIRED CVS 
   ************************************************ */
int cont_flag=PSD_OFF 
;
int optabent=1 
;
int sifsetwokey = 0 
;
int iheesp = 0 
;

int oplandmark = PSD_OFF 
;

int opautosldelay = PSD_OFF 
;

int rhpcfitorig = 1 
;
int rhpcshotfirst = 0 
;
int rhpcshotlast = 0 
;
int rhpcmultegrp = 0 
;
int rhpclinfix = 1 
;
float rhpclinslope = 0.0 
;
int rhpcconfix = 1 
;
float rhpcconslope = 0.0 
;
int rhpccoil = 1 
;
int piforkvrgf = 0;  /*  1 causes scan to spawn the vrgf process upon download */
int pinofreqoffset = 0; /*  1 disables fov offset in frequency direction */
int opssfse = 0 ;
int t1flair_flag = 0 ;
                                                                        
float rhmaxcoef1a = 0 
;
float rhmaxcoef1b = 0 
;
float rhmaxcoef1c = 0 
;
float rhmaxcoef1d = 0 
;
float rhmaxcoef2a = 0 
;
float rhmaxcoef2b = 0 
;
float rhmaxcoef2c = 0 
;
float rhmaxcoef2d = 0 
;
float rhmaxcoef3a = 0 
;
float rhmaxcoef3b = 0 
;
float rhmaxcoef3c = 0 
;
float rhmaxcoef3d = 0 
;


/********************************************************/
/*   EPI DWI cv's					*/
/********************************************************/

int opdiffuse=0 ;
int opsavedf=0 ;	
int opmintedif = 1 ;

int opdfaxx=0;		/*   diffusion direction variables      */
int opdfaxy=0;
int opdfaxz=0;
int opdfaxall=0;

int opbval=0 ;

int rhdptype = 0 
;
int rhutctrl = 0 
;

/********************************************************/
/*   EPI FLAIR cv's					*/
/********************************************************/
int opflair = 0 ;

/* *************************************************
   SmartPrep Required CVs
   ************************************************ */

float opmonfov = 200 
;


float opmonthick = 20 
;

float opdose = 0 ;

float rhzipfact = 0 ;



int opzip512 = 0 
;

int opzip1024 = 0 
;

int opslzip2 = 0 
;

int opslzip4 = 0 
;


/* *************************************************
   MORE REQUIRED CVS 
   ************************************************ */

/* Neuro Vascular Coil CV    */
int opnvcoil = 0 ;
int opcmon = 0 
;
int opsmartprep = 0 ;


/* *************************************************
   MORE REQUIRED CVS 
   ************************************************ */
/* Cardiac Gating */
int opcgatetype = 0 

;
int opadvgate = 0 

;

/* Fast CINE */
/* Enable selection by changing cvmax field */
int opfcine = 0 

;
int ihfcineim = 0 


;
int ihfcinent = 0 


;
int rhfcinemode = 0 

;
int rhfcinearw = 10 

;
int rhvps = 8 

;
int rhvvsaimgs = 1 

;
int rhvvstr = 0 

;
int rhvvsgender = 0 

;

/* Black Blood Suppression */
/* Enable selection by changing cvmax field */
int opbsp = 0 

;
int opbspti = TI_MIN 


;
int opautoti = 0 

;
int opautobti = 0 

;
int ihbspti = TI_MIN 

;

/* Cardiac Tagging */
/* Enable selection by changing cvmax field */
int optagging = 0 


;
int optagspc = 7 

;
float ihtagfa = 180.0 

;
float ihtagor = 45.0 

;

/* Added for SNR Index */
float pifractecho = 1.0
    ;

/* Added for RTIA, RJF */
int oprealtime = 0 


;

/* Added for Echotrain */
int opET = 0 


;


/* Bolus Chasing CVs - CMC */
int opmultistation = 0 


;

int opnostations = 1 

;

int opstation = 1 

;

int pscahead = 0 

;

int opprescanopt = 0 

;

int autoadvtoscn = 0 

;

int opprotRxMode = 0 ;  /* Added to indicate whether Procol/Scan mode -TAA */


/* ************************************************************
 * CVs
 * Certain CVs are not necessary for Scan/PSD communication
 * but are essential intermediate calculations for determining 
 * recon CV values and pulsegen values.
 * ********************************************************* */

int acqs = 1 ;

int avround = 1 ;
int baseline = 0 ;

/* CV nex has value 1 for .5 nex and .75 nex scans */
int nex = 1 ;

/* ***************
 * fn 1 full kspace
 *    .5 half nex
 *    .75 3/4 nex 
 **************** */
float fn = 1 ;
/* no phase wrap is used for exorcist high sort and avg high sort */

float nop = 1 ;
int acq_type = TYPSPIN ;
int seq_type = TYPNCAT ;
int num_images = 1 ;

/* Image Type CVs */
int mag = 1 ;
int pha = 0 ;
int imag = 0 ;
int qmag = 0 ;

/* Nex can not be accumulated with exorcist running.  exnex
 * calculates the number of frames/view that must be stored in BAM */
int exnex = 1 ;

/* slquant1 is number of pomp groups imaged in first pass for pomp */
int slquant1 = 1 ;
/* changed from psd_grad_acq_delay to psd_grd_wait.  YH  10/14/94 */
int psd_grd_wait = 56 
;
int psd_rf_wait = 0 
;

/* pos_moment_start holds the time in us from the start of the sequence
   to the middle of the alpha pulse.  This is used to automate flow
   compensation and zeroth moment graphing tests.   */
int pos_moment_start = 0 ;

/* mps1rf1_inst and scanrf1_inst are used to hold the index into
   the rf1 instruction for scan and mps1. This allows the code
   for MPS1Prescan to simply copy the rf1 waveform used in scan.
   Thus, MPS1 is simplified for non-typical rf pulses  */
int mps1rf1_inst = 0 ;
int scanrf1_inst = 0 ;

/* cfcarddelay holds the delay of the cardiac hardware  */
int cfcarddelay = 10 ;

float GAM = 4257.59 ;

int psd_card_hdwr_delay = 0 
;
int off90 = 80 ;
int TR_SLOP = 2000 ;
int TR_PASS = 50000 ;
int TR_PASS3D = 550000 
;
int csweight= 100 
;
float truenex = 0 ;
int eg_phaseres =0;
int sp_satcard_loc = 0 ;

int min_rfdycc=0; /* minimum seq time based on duty cycle (us) */
int min_rfavgpow=0; /* minimum seq time based on avg. power (us) */
int coll_prefls = 1 
;
/* following parameters are new for 55.  YH  10/14/94 */
int maxGradRes = 1 
;

float dfg = 2 
;

float pg_beta = 1.0 
;
     
int split_dab = 0 
;
 
float freq_scale = 1.0 
;
int numrecv = 1 ;
 
/* for phase encoding */
int pe_on = 1 
;
 
float psd_targetscale = 1.0; /* %fullscale for amps-set in obloptimize */
 
/* CVs used to display logical gradient values calculated by
   obloptimize */
float logxfs=0; /* set equal to loggrd.xfs */
float logyfs=0; /* set equal to loggrd.yfs */
float logzfs=0; /* set equal to loggrd.zfs */
int logxrt=0; /* set equal to loggrd.xrt */
int logyrt=0; /* set equal to loggrd.yrt */
int logzrt=0; /* set equal to loggrd.zrt */
int logxft=0; /* set equal to loggrd.xft */
int logyft=0; /* set equal to loggrd.yft */
int logzft=0; /* set equal to loggrd.zft */
float logxfa=0; /* set equal to loggrd.xfa */
float logyfa=0; /* set equal to loggrd.yfa */
float logzfa=0; /* set equal to loggrd.zfa */
float logxcc=0; /* set equal to loggrd.xcc */
float logycc=0; /* set equal to loggrd.ycc */
float logzcc=0; /* set equal to loggrd.zcc */
float logxbeta=0; /* set equal to loggrd.xbeta */
float logybeta=0; /* set equal to loggrd.ybeta */
float logzbeta=0; /* set equal to loggrd.zbeta */
float logtx=0; /* set equal to loggrd.tx */
float logty=0; /* set equal to loggrd.ty */
float logtz=0; /* set equal to loggrd.tz */
float logtx_xy=0; /* set equal to loggrd.tx_xy */
float logtx_xz=0; /* set equal to loggrd.tx_xz */
float logty_xy=0; /* set equal to loggrd.ty_xy */
float logty_yz=0; /* set equal to loggrd.ty_yz */
float logtz_xz=0; /* set equal to loggrd.tz_xz */
float logtz_yz=0; /* set equal to loggrd.tz_yz */
float logtx_xyz=0; /* set equal to loggrd.tx_xyz */
float logty_xyz=0; /* set equal to loggrd.ty_xyz */
float logtz_xyz=0; /* set equal to loggrd.tz_xyz */

int min_rfrmsb1=0; /* minimum seq time based on rms B1 limitation (us). To be moved below
		  * min_avgpow later on 
                  */

float psd_zero = 0.0 
;


int minseqgram_t=0;              /* min seq time based on gram heating  */

/* gram pulse modulation width time per logical axis */
int lx_pwmtime=0; 
int ly_pwmtime=0;
int lz_pwmtime=0;

/* gram pulse modulation width time per physical axis  */
int px_pwmtime=0; 
int py_pwmtime=0;
int pz_pwmtime=0;

int minseqcoil_t=0;  /* minseq time based on coil heating  */

/* per axis loading in units of A^2*uSec */
float xa2s=0;
float ya2s=0;
float za2s=0;

/* min seq time based on gradient driver heating  */
int minseqgrddrv_t=0;      /* minseqtime based on gradient driver heating */
int minseqgrddrvx_t=0;     /* minseqtime based on X gradient driver heating */
int minseqgrddrvy_t=0;     /* minseqtime based on Y gradient driver heating */
int minseqgrddrvz_t=0;     /* minseqtime based on Z gradient driver heating */
float powerx=0;             /* total scaled power in X in Ampere^2 usec     */
float powery=0;             /* total scaled power in Y in Ampere^2 usec     */
float powerz=0;             /* total scaled power in Z in Ampere^2 usec     */
float pospowerx=0;          /* positive scaled power in X in Ampere^2 usec  */
float pospowery=0;          /* positive scaled power in Y in Ampere^2 usec  */
float pospowerz=0;          /* positive scaled power in Z in Ampere^2 usec  */
float negpowerx=0;          /* negative scaled power in X in Ampere^2 usec  */
float negpowery=0;          /* negative scaled power in Y in Ampere^2 usec  */
float negpowerz=0;          /* negative scaled power in Z in Ampere^2 usec  */
float amptrans_lx=0;          /* logical X ampere trans in (Amp/usec)*usec   */
float amptrans_ly=0;          /* logical Y ampere trans in (Amp/usec)*usec   */
float amptrans_lz=0;          /* logical Z ampere trans in (Amp/usec)*usec   */
float amptrans_px=0;        /* physical X ampere trans in (Amp/usec)*usec   */
float amptrans_py=0;        /* physical X ampere trans in (Amp/usec)*usec   */
float amptrans_pz=0;        /* physical Y ampere trans in (Amp/usec)*usec   */
float abspower_lx=0;          /* logical Z abs avrg ampere in Ampere * usec   */
float abspower_ly=0;          /* logical Y abs avrg ampere in Ampere * usec   */
float abspower_lz=0;          /* logical Z abs avrg ampere in Ampere * usec   */
float abspower_px=0;        /* physical X abs avrg amperere in Amp * usec   */
float abspower_py=0;        /* physical Y abs avrg amperere in Amp * usec   */
float abspower_pz=0;        /* physical Y abs avrg amperere in Amp * usec   */

int time_pgen = 0;       /* timing variable added to monitor pulsegen execution time RK 6/11/96 */

int cont_debug = 0 ;

/* CVs added for Maxwell correction for phase-contrast */
int maxpc_cor = 0 ;
int maxpc_debug = 0 ;
int maxpc_points = 500 
;

/*
 * MRIge47485 - Improved Gradient Duty Cycle
 */
/* Linear segment heating model */
int tsamp = 4 






;
int seg_debug = 0 






;
int gradHeatMethod = PSD_OFF 






;
/* SGD gradient heating */
int minseqpwm_x=0;
int minseqpwm_y=0;
int minseqpwm_z=0;
int minseqgpm_t=0;

/* SGD performance simulation flag CV added by RJF for RTIA */
/* See minseqseg.c, minseqgrad.c for details. */
int sgd_perf_simulate = PSD_OFF 






;
int gradHeatFile = PSD_OFF 






;
int seqEntryIndex = 0 






;


/* dB/dtOpt CVs - RJF */
int dbdt_debug = 0 






;

int reilly_mode = 0 






;

/* Use this cv to manually turn on/off dB/dt feature */

int dbdt_disable = 0 






;

/* Add the following cv as a logic flag.  This depends on 3 conditions:
   1)Reilly Model being used, 2)CRM is present, 3)dB/dt feature is turned on.*/

int use_dbdt_opt = 1 






;

float srderate =  1.0 






;

long _lastcv = 0;

#endif /* h_epic_allcv_h */

