/*********************************************************************
    INCLUDE FILE : epic_struct.h
    DESCRIPTION: File which gets included automatically by the C files
        generated by the EPIC compiler. Also is included by various epic
        run time routines.  Since this is included by the PSD code, put
        underscores in front of the items that the PSD programmer does
	not directly use to avoid conflicts with his/her definitions.
	Contains various constants along with typdefs for the CV structures.
  
    $Source: epic_struct.h $
    $Revision: 1.15 $  $Date: 9/22/97 02:05:24 $

    RELEASE     DATE            AUTHOR(S)       DESCRIPTION
    -------     ------------    ------------    -----------
    5.0         10/24/89        Douglas Earl    initial version
    5.2          7/8/92		Chuck Lloyd	Add code for MCVALL symbol
    5.3         930407      Mike Hartmann        Make all cv's modifiable for 
                                                 clinicals and testing.

    5.3         930507      Mike Hartmann        Undo last change
    5.4         07/05/95    Robert J. Laferriere Add new epic_nerror constansts for
                                                 printARGS routine in psdsupport()
					       
    5.5         07/13/95    Robert J. Laferriere Add CV_ARG
    8.0         02/39/96    Robert J. Laferriere Added popupflag to cv struct
                                                 definition by using a bit from
                                                 the existflag bitfield
						 which is no longer used by the
                                                 PSDs.

   CDP-0       09/21/1997  GFN     Added a #ifndef block to avoid multiple
                                   inclusions.

 ***************************************************************************
 Version          Date/        Author
                  Comment
 ***************************************************************************

 /main/mr_main/2  8-Oct-98     Dale Thayer
                  Changed defines from epic_struct.h which conflicted with
                  stdarg.h (_INT, _SHORT, _FLOAT, _DOUBLE, _EXPORT,  _STRUCT).


**********************************************************************/

#ifndef epic_struct_h
#define epic_struct_h


/* CV and export variable types */
#define GE_INT 0
#define GE_SHORT 1
#define GE_FLOAT 2
#define GE_DOUBLE 3
#define GE_EXPORT 4
#define GE_STRUCT 5

/* Used in epic_nerror to indicate the type of the argument */
#define INT_ARG 0
#define SHORT_ARG 1
#define FLOAT_ARG 2
#define DOUBLE_ARG 3
#define CHAR_ARG 4
#define STRING_ARG 5
#define GRADPULSE_ARG 6
#define RFPULSE_ARG 7
#define LOGGRAD_ARG 8
#define PHYSGRAD_ARG 9
#define CV_ARG 10

/* visibility attributes */
#define _VISBIT 1
#define _MODBIT 2

#ifdef MCVALL
#define MODIFIABLE (_VISBIT + _MODBIT)
#define VISIBLE MODIFIABLE
#define INVISIBLE MODIFIABLE
#define UNACCESSIBLE MODIFIABLE
#else
#define MODIFIABLE (_VISBIT + _MODBIT)
#define VISIBLE _VISBIT
#define INVISIBLE 0
#define UNACCESSIBLE 0
#endif

/* unit conversion, multiply by these constants to get base unit (usec)*/
#define _U 1		/* to convert microseconds */
#define _M 1000		/* to convert milliseconds */
#define _S 1000000	/* to convert seconds */

/* for PSD "header", mode field */
#define _DEVELOPMENT 1
#define _PRODUCT 2

/* common_portion must be last since EPIC compiler requires that min, max and
   def are 1st */
#define _COMMON_PORTION \
    unsigned int fixedflag:1, existflag:4, modifiedflag:1, popupflag:1, visflag:2;\
    char *descr;\
    int errnum;\
    char *errstr;
    
typedef struct {
    int *addr, minval, maxval, defval;
    _COMMON_PORTION
} _cvint;

typedef struct {
    float *addr, minval, maxval, defval;
    _COMMON_PORTION
} _cvfloat;

typedef struct {
    double *addr, minval, maxval, defval;
    _COMMON_PORTION
} _cvdouble;

typedef struct {
    short *addr, minval, maxval, defval;
    _COMMON_PORTION
} _cvshort;

typedef struct {
    char *addr;
    short size;
    short type;
} _export;

typedef union {
    _cvint *i;
    _cvfloat *f;
    _cvdouble *d;
    _cvshort *s;
    _export *e;
    char *ptr;
} _cvptr;

typedef struct {
    char *cvname;
    int index;
} _cvname;

typedef struct {
    short type;
    /* When initializing this structure, cast the following field (address
       of the cv data) to a pointer to a character so it compiles without
       warnings, (since it can actually be a pointer to any number of
       different types of structures) */
    char *cv;
} _cvdataptr;

typedef struct {
    char *rsp;
    short type;
    int nelements;
} _rspdataptr;


#endif /* epic_struct_h */
