#ifndef epic_ext_h
#define epic_ext_h

extern long _firstcv ;
extern float opweight ;
extern int opcoil ;
extern int opentry ;
extern int oppos ;
extern int oppseq ;
extern int opcgate ;
extern int opexor ;
extern int opfcomp ;
extern int opplane ;
extern int opgrx ;
extern int opgrxroi ;
extern int opobplane ;
extern int opnopwrap ;
extern int opimode ;
extern int opsat ;
extern int opptsize ;
extern int oppomp ;
extern int opscic ;
extern int oprect ;
extern int opsquare ;
extern int opvbw ;
extern int opblim ;
extern int opfast ;
extern int opcs ;
extern int opdeprep ;
extern int opirprep ;
extern int opmph ;
extern int opautotr ;
extern int opphcor ;
extern int opacqo ;
extern int opfphases ;
extern int opsldelay ;
extern int opmt ;
extern int opsatx ;
extern int opsaty ;
extern int opsatz ;
extern float opsatxloc1 ;
extern float opsatxloc2 ;
extern float opsatyloc1 ;
extern float opsatyloc2 ;
extern float opsatzloc1 ;
extern float opsatzloc2 ;
extern float opsatxthick ;
extern float opsatythick ;
extern float opsatzthick ;
extern int opsatmask ;
extern int opfat ;
extern int opwater ;
extern int opccsat ;
extern int opexsatmask ;
extern float opexsathick1 ;
extern float opexsathick2 ;
extern float opexsathick3 ;
extern float opexsathick4 ;
extern float opexsathick5 ;
extern float opexsathick6 ;
extern float opexsatloc1 ;
extern float opexsatloc2 ;
extern float opexsatloc3 ;
extern float opexsatloc4 ;
extern float opexsatloc5 ;
extern float opexsatloc6 ;
extern int opexsatparal ;
extern int opexsatoff1 ;
extern int opexsatoff2 ;
extern int opexsatoff3 ;
extern int opexsatoff4 ;
extern int opexsatoff5 ;
extern int opexsatoff6 ;
extern int opexsatlen1 ;
extern int opexsatlen2 ;
extern int opexsatlen3 ;
extern int opexsatlen4 ;
extern int opexsatlen5 ;
extern int opexsatlen6 ;
extern float opdfsathick1 ;
extern float opdfsathick2 ;
extern float opdfsathick3 ;
extern float opdfsathick4 ;
extern float opdfsathick5 ;
extern float opdfsathick6 ;
extern float opvenc ;
extern int opflaxx ;
extern int opflaxy ;
extern int opflaxz ;
extern int opflaxall ;
extern int opproject ;
extern int opcollapse ;
extern int oprlflow ;
extern int opapflow ;
extern int opsiflow ;
extern int opmagc ;
extern int opflrecon ;
extern int project ;
extern int vas_ovrhd ;
extern int slice_col ;
extern int phase_col ;
extern int read_col ;
extern int mag_mask ;
extern int phase_cor ;
extern int extras ;
extern int mag_create ;
extern int rl_flow ;
extern int ap_flow ;
extern int si_flow ;
extern int imagenum ;
extern int motsa_ovrhd ;
extern int oprampdir ;
extern int opfcaxis ;
extern int ophrate ;
extern int oparr ;
extern int ophrep ;
extern int optdel1 ;
extern int optseq ;
extern int opphases ;
extern int opcardseq ;
extern int opmphases ;
extern int oparrmon ;
extern int opvps ;
extern int opetl ;
extern int opnecho ;
extern int opautote ;
extern int opte ;
extern int opte2 ;
extern int optefw ;
extern int opti ;
extern int opirmode ;
extern int optr ;
extern float opflip ;
extern float opfov ;
extern float opphasefov ;
extern float opfreqfov ;
extern int opslquant ;
extern int opileave ;
extern float opslthick ;
extern float opslspace ;
extern int opcoax ;
extern float opvthick ;
extern int opvquant ;
extern int opovl ;
extern float oplenrl ;
extern float oplenap ;
extern float oplensi ;
extern float oplocrl ;
extern float oplocap ;
extern float oplocsi ;
extern float oprlcsiis ;
extern float opapcsiis ;
extern float opsicsiis ;
extern int opxres ;
extern int opyres ;
extern float opnex ;
extern int opslicecnt ;
extern int opspf ;
extern int opcfsel ;
extern float oprbw ;
extern float oprbw2 ;
extern int opchrate ;
extern int opcphases ;
extern int opclocs ;
extern int opmctr ;
extern int opmultrecv ;
extern int specnuc ;
extern int specpts ;
extern int specwidth ;
extern int specnavs ;
extern int specnex ;
extern int specdwells ;
extern int acquire_type ;
extern int pixmtband ;
extern int pibbandfilt ;
extern int asslquant ;
extern float asflip ;
extern float asslthick ;
extern int asxres ;
extern int asyres ;
extern int asbaseline ;
extern int asrhblank ;
extern int asptsize ;
extern int opascalcfov ;
extern int opepi ;
extern int optlrdrf ;
extern int opnshots ;
extern int oprtcgate ;
extern int oprtrate ;
extern int oprtrep ;
extern int oprttdel1 ;
extern int oprttseq ;
extern int oprtcardseq ;
extern int oprtarr ;
extern int oprtpoint;
extern int opssrf ;
extern int opt2prep ;
extern int opspiral ;
extern int piresol ;
extern int pioverlap ;
extern int opfulltrain ;
extern int pi_neg_sp ;
extern float piisvaldef ;
extern int pidmode ;
extern int piviews ;
extern int piclckcnt ;
extern float avmintscan ;
extern int pitslice ;
extern float pitscan ;
extern int pisaveinter ;
extern int pivextras ;
extern int pinecho ;
extern float piscancenter ;
extern int pismode ;
extern int ihtr ;
extern int ihti ;
extern int ihtdel1 ;
extern float ihnex ;
extern float ihflip ;
extern int ihte1 ;
extern int ihte2 ;
extern int ihte3 ;
extern int ihte4 ;
extern int ihte5 ;
extern int ihte6 ;
extern int ihte7 ;
extern int ihte8 ;
extern int ihte9 ;
extern int ihte10 ;
extern int ihte11 ;
extern int ihte12 ;
extern int ihte13 ;
extern int ihte14 ;
extern int ihte15 ;
extern int ihte16 ;
extern float ihvbw1 ;
extern float ihvbw2 ;
extern float ihvbw3 ;
extern float ihvbw4 ;
extern float ihvbw5 ;
extern float ihvbw6 ;
extern float ihvbw7 ;
extern float ihvbw8 ;
extern float ihvbw9 ;
extern float ihvbw10 ;
extern float ihvbw11 ;
extern float ihvbw12 ;
extern float ihvbw13 ;
extern float ihvbw14 ;
extern float ihvbw15 ;
extern float ihvbw16 ;
extern int ihnegscanspacing ;
extern int ihoffsetfreq ;
extern int opuser_usage_tag ;
extern int rhuser_usage_tag ;
extern int rhFillMapMSW ;
extern int rhFillMapLSW ;
extern int rhbline ;
extern int rhblank ;
extern int rhnavs ;
extern int rhnslices ;
extern int rhnframes ;
extern int rhfrsize ;
extern int rhnecho ;
extern int rhtype ;
extern int rhtype1 ;
extern int rhformat ;
extern int rhptsize ;
extern int rhnpomp ;
extern int rhrcctrl ;
extern int rhdacqctrl ;
extern int rhexecctrl ;
extern int rhfdctrl ;
extern float rhxoff ;
extern float rhyoff ;
extern int rhrecon ;
extern int rhdatacq ;
extern int rhvquant ;
extern int rhslblank ;
extern int rhhnover ;
extern int rhoscans ;
extern int rhddaover ;
extern float rhzeroph ;
extern float rhalpha ;
extern float rhnwin ;
extern float rhntran ;
extern float rhfermw ;
extern float rhfermr ;
extern float rhferme ;
extern float rhclipmin ;
extern float rhclipmax ;
extern float rhdoffset ;
extern int rhudasave ;
extern int rhsspsave ;
extern float rhscalei ;
extern float rhscaleq ;
extern int rhnpasses ;
extern int rhrawsize ;
extern int rhincrpass ;
extern int rhinitpass ;
extern int rhmethod ;
extern int rhdaxres ;
extern int rhdayres ;
extern int rhrcxres ;
extern int rhrcyres ;
extern int rhimsize ;
extern float rhuser0  ;
extern float rhuser1  ;
extern float rhuser2  ;
extern float rhuser3  ;
extern float rhuser4  ;
extern float rhuser5  ;
extern float rhuser6  ;
extern float rhuser7  ;
extern float rhuser8  ;
extern float rhuser9  ;
extern float rhuser10 ;
extern float rhuser11 ;
extern float rhuser12 ;
extern float rhuser13 ;
extern float rhuser14 ;
extern float rhuser15 ;
extern float rhuser16 ;
extern float rhuser17 ;
extern float rhuser18 ;
extern float rhuser19 ;
extern float rhuser20 ;
extern float rhuser21 ;
extern float rhuser22 ;
extern float rhuser23 ;
extern float rhuser24 ;
extern float rhuser25 ;
extern float rhuser26 ;
extern float rhuser27 ;
extern float rhuser28 ;
extern float rhuser29 ;
extern float rhuser30 ;
extern float rhuser31 ;
extern float rhuser32 ;
extern float rhuser33 ;
extern float rhuser34 ;
extern float rhuser35 ;
extern float rhuser36 ;
extern float rhuser37 ;
extern float rhuser38 ;
extern float rhuser39 ;
extern float rhuser40 ;
extern float rhuser41 ;
extern float rhuser42 ;
extern float rhuser43 ;
extern float rhuser44 ;
extern float rhuser45 ;
extern float rhuser46 ;
extern float rhuser47 ;
extern float rhuser48 ;
extern int rhdab0s ;
extern int rhdab0e ;
extern float rhctr ;
extern float rhcrrtime ;
extern int rhcphases ;
extern int rhovl ;
extern int rhvtype ;
extern float rhvenc ;
extern float rhvcoefxa ;
extern float rhvcoefxb ;
extern float rhvcoefxc ;
extern float rhvcoefxd ;
extern float rhvcoefya ;
extern float rhvcoefyb ;
extern float rhvcoefyc ;
extern float rhvcoefyd ;
extern float rhvcoefza ;
extern float rhvcoefzb ;
extern float rhvcoefzc ;
extern float rhvcoefzd ;
extern float rhvmcoef1 ;
extern float rhvmcoef2 ;
extern float rhvmcoef3 ;
extern float rhvmcoef4 ;
extern float rhphasescale ;
extern float rhfreqscale ;
extern int rawmode ;
extern int rhileaves ;
extern int rhkydir ;
extern int rhalt ;
extern int rhreps ;
extern int rhref ;
extern int rhpcthrespts ;
extern int rhpcthrespct ;
extern int rhpcdiscbeg ;
extern int rhpcdiscmid ;
extern int rhpcdiscend ;
extern int rhpcileave ;
extern int rhpcextcorr ;
extern int rhrefframes ;
extern int rhpcsnore ;
extern int rhpcspacial ;
extern int rhpctemporal ;
extern float rhpcbestky ;
extern int rhhdbestky ;
extern int rhpcinvft ;
extern int rhpcctrl ;
extern int rhpctest ;
extern int rhpcgraph ;
extern int rhpclin ;
extern int rhpclinnorm ;
extern int rhpclinnpts ;
extern int rhpclinorder ;
extern int rhpclinfitwt ;
extern int rhpclinavg ;
extern int rhpccon ;
extern int rhpcconnorm ;
extern int rhpcconnpts ;
extern int rhpcconorder ;
extern int rhpcconfitwt ;
extern int rhvrgfxres ;
extern int rhvrgf ;
extern int rhbp_corr ;
extern float rhrecv_freq_s ;
extern float rhrecv_freq_e ;
extern int rhhniter ;
extern int rhfast_rec ;
extern int rhgridcontrol ;
extern int rhb0map ;
extern int rhtediff ;
extern float rhradiusa ;
extern float rhradiusb ;
extern float rhmaxgrad ;
extern float rhslewmax ;
extern float rhscanfov ;
extern float rhtsamp ;
extern float rhdensityfactor ;
extern float rhdispfov ;
extern int rhmotioncomp ;
extern int pititle ;
extern float opuser0  ;
extern float opuser1  ;
extern float opuser2  ;
extern float opuser3  ;
extern float opuser4  ;
extern float opuser5  ;
extern float opuser6  ;
extern float opuser7  ;
extern float opuser8  ;
extern float opuser9  ;
extern float opuser10 ;
extern float opuser11 ;
extern float opuser12 ;
extern float opuser13 ;
extern float opuser14 ;
extern float opuser15 ;
extern float opuser16 ;
extern float opuser17 ;
extern float opuser18 ;
extern float opuser19 ;
extern float opuser20 ;
extern float opuser21 ;
extern float opuser22 ;
extern float opuser23 ;
extern float opuser24 ;
extern float opuser25 ;
extern float opuser26 ;
extern float opuser27 ;
extern float opuser28 ;
extern float opuser29 ;
extern float opuser30 ;
extern float opuser31 ;
extern float opuser32 ;
extern float opuser33 ;
extern float opuser34 ;
extern float opuser35 ;
extern float opuser36 ;
extern float opuser37 ;
extern float opuser38 ;
extern float opuser39 ;
extern float opuser40 ;
extern float opuser41 ;
extern float opuser42 ;
extern float opuser43 ;
extern float opuser44 ;
extern float opuser45 ;
extern float opuser46 ;
extern float opuser47 ;
extern float opuser48 ;
extern int pishldctrl;
extern int pinolr;
extern int pinoadc;
extern int pimixtime ;
extern int psd_board_type ;
extern int cfcoilres;
extern int cftxgate0;
extern int cftxgate90;
extern int cfcoilportvu;
extern int cfcoilportvl;
extern int cfcoilbias;
extern int cfgradcoil ;
extern int rhrefframep ;
extern int rhscnframe ;
extern int rhpasframe ;
extern int cont_flag;
extern int optabent;
extern int sifsetwokey ;
extern int iheesp ;
extern int oplandmark ;
extern int opautosldelay ;
extern int rhpcfitorig ;
extern int rhpcshotfirst ;
extern int rhpcshotlast ;
extern int rhpcmultegrp ;
extern int rhpclinfix ;
extern float rhpclinslope ;
extern int rhpcconfix ;
extern float rhpcconslope ;
extern int rhpccoil ;
extern int piforkvrgf ;
extern int pinofreqoffset ;
extern int opssfse ;
extern int t1flair_flag ;
extern float rhmaxcoef1a ;
extern float rhmaxcoef1b ;
extern float rhmaxcoef1c ;
extern float rhmaxcoef1d ;
extern float rhmaxcoef2a ;
extern float rhmaxcoef2b ;
extern float rhmaxcoef2c ;
extern float rhmaxcoef2d ;
extern float rhmaxcoef3a ;
extern float rhmaxcoef3b ;
extern float rhmaxcoef3c ;
extern float rhmaxcoef3d ;
extern int opdiffuse;
extern int opsavedf;
extern int opmintedif ;
extern int opdfaxx;
extern int opdfaxy;
extern int opdfaxz;
extern int opdfaxall;
extern int opbval;
extern int rhdptype ;
extern int rhutctrl ;
extern int opflair ;
extern float opmonfov ;
extern float opmonthick ;
extern float opdose ;
extern float rhzipfact ;
extern int opzip512 ;
extern int opzip1024 ;
extern int opslzip2 ;
extern int opslzip4 ;
extern int opnvcoil ;
extern int opcmon ;
extern int opsmartprep ;
extern int opcgatetype ;
extern int opadvgate ;
extern int opfcine ;
extern int ihfcineim ;
extern int ihfcinent ;
extern int rhfcinemode ;
extern int rhfcinearw ;
extern int rhvps ;
extern int rhvvsaimgs ;
extern int rhvvstr ;
extern int rhvvsgender ;
extern int opbsp ;
extern int opbspti ;
extern int opautoti ;
extern int opautobti ;
extern int ihbspti ;
extern int optagging ;
extern int optagspc ;
extern float ihtagfa ;
extern float ihtagor ;
extern float pifractecho ;
extern int oprealtime ;
extern int opET ;
extern int opmultistation ;
extern int opnostations ;
extern int opstation ;
extern int pscahead ;
extern int opprescanopt ;
extern int autoadvtoscn ;
extern int opprotRxMode ;
extern int acqs ;
extern int avround ;
extern int baseline ;
extern int nex ;
extern float fn ;
extern float nop ;
extern int acq_type ;
extern int seq_type ;
extern int num_images ;
extern int mag ;
extern int pha ;
extern int imag ;
extern int qmag ;
extern int exnex ;
extern int slquant1 ;
extern int psd_grd_wait ;
extern int psd_rf_wait ;
extern int pos_moment_start ;
extern int mps1rf1_inst ;
extern int scanrf1_inst ;
extern int cfcarddelay ;
extern float GAM ;
extern int psd_card_hdwr_delay ;
extern int off90 ;
extern int TR_SLOP ;
extern int TR_PASS ;
extern int TR_PASS3D ;
extern int csweight;
extern float truenex ;
extern int eg_phaseres ;
extern int sp_satcard_loc ;
extern int min_rfdycc;
extern int min_rfavgpow;
extern int coll_prefls ;
extern int maxGradRes ;
extern float dfg ;
extern float pg_beta ;
extern int split_dab ;
extern float freq_scale ;
extern int numrecv ;
extern int pe_on ;
extern float psd_targetscale ;
extern float logxfs;
extern float logyfs;
extern float logzfs;
extern int logxrt;
extern int logyrt;
extern int logzrt;
extern int logxft;
extern int logyft;
extern int logzft;
extern float logxfa;
extern float logyfa;
extern float logzfa;
extern float logxcc;
extern float logycc;
extern float logzcc;
extern float logxbeta;
extern float logybeta;
extern float logzbeta;
extern float logtx;
extern float logty;
extern float logtz;
extern float logtx_xy;
extern float logtx_xz;
extern float logty_xy;
extern float logty_yz;
extern float logtz_xz;
extern float logtz_yz;
extern float logtx_xyz;
extern float logty_xyz;
extern float logtz_xyz;
extern int min_rfrmsb1;
extern float psd_zero ;
extern int minseqgram_t;
extern int lx_pwmtime;
extern int ly_pwmtime;
extern int lz_pwmtime;
extern int px_pwmtime;
extern int py_pwmtime;
extern int pz_pwmtime;
extern int minseqcoil_t;
extern float xa2s;
extern float ya2s;
extern float za2s;
extern int minseqgrddrv_t;
extern int minseqgrddrvx_t;
extern int minseqgrddrvy_t;
extern int minseqgrddrvz_t;
extern float powerx;
extern float powery;
extern float powerz;
extern float pospowerx;
extern float pospowery;
extern float pospowerz;
extern float negpowerx;
extern float negpowery;
extern float negpowerz;
extern float amptrans_lx;
extern float amptrans_ly;
extern float amptrans_lz;
extern float amptrans_px;
extern float amptrans_py;
extern float amptrans_pz;
extern float abspower_lx;
extern float abspower_ly;
extern float abspower_lz;
extern float abspower_px;
extern float abspower_py;
extern float abspower_pz;
extern int time_pgen ;
extern int cont_debug ;
extern int maxpc_cor ;
extern int maxpc_debug ;
extern int maxpc_points ;
extern int tsamp ;
extern int seg_debug ;
extern int gradHeatMethod ;
extern int minseqpwm_x;
extern int minseqpwm_y;
extern int minseqpwm_z;
extern int minseqgpm_t;
extern int sgd_perf_simulate ;
extern int gradHeatFile ;
extern int seqEntryIndex ;
extern int dbdt_debug ;
extern int reilly_mode ;
extern int dbdt_disable ;
extern int use_dbdt_opt ;
extern float srderate ;
extern long _lastcv ;
extern int _cv_revision ;
extern _cvfloat  _opweight;
extern _cvint  _opcoil;
extern _cvint  _opentry;
extern _cvint  _oppos;
extern _cvint  _oppseq;
extern _cvint  _opcgate;
extern _cvint  _opexor;
extern _cvint  _opfcomp;
extern _cvint  _opplane;
extern _cvint  _opgrx;
extern _cvint  _opgrxroi;
extern _cvint  _opobplane;
extern _cvint  _opnopwrap;
extern _cvint  _opimode;
extern _cvint  _opsat;
extern _cvint  _opptsize;
extern _cvint  _oppomp;
extern _cvint  _opscic;
extern _cvint  _oprect;
extern _cvint  _opsquare;
extern _cvint  _opvbw;
extern _cvint  _opblim;
extern _cvint  _opfast;
extern _cvint  _opcs;
extern _cvint  _opdeprep;
extern _cvint  _opirprep;
extern _cvint  _opmph;
extern _cvint  _opautotr;
extern _cvint  _opphcor;
extern _cvint  _opacqo;
extern _cvint  _opfphases;
extern _cvint  _opsldelay;
extern _cvint  _opmt;
extern _cvint  _opsatx;
extern _cvint  _opsaty;
extern _cvint  _opsatz;
extern _cvfloat  _opsatxloc1;
extern _cvfloat  _opsatxloc2;
extern _cvfloat  _opsatyloc1;
extern _cvfloat  _opsatyloc2;
extern _cvfloat  _opsatzloc1;
extern _cvfloat  _opsatzloc2;
extern _cvfloat  _opsatxthick;
extern _cvfloat  _opsatythick;
extern _cvfloat  _opsatzthick;
extern _cvint  _opsatmask;
extern _cvint  _opfat;
extern _cvint  _opwater;
extern _cvint  _opccsat;
extern _cvint  _opexsatmask;
extern _cvfloat  _opexsathick1;
extern _cvfloat  _opexsathick2;
extern _cvfloat  _opexsathick3;
extern _cvfloat  _opexsathick4;
extern _cvfloat  _opexsathick5;
extern _cvfloat  _opexsathick6;
extern _cvfloat  _opexsatloc1;
extern _cvfloat  _opexsatloc2;
extern _cvfloat  _opexsatloc3;
extern _cvfloat  _opexsatloc4;
extern _cvfloat  _opexsatloc5;
extern _cvfloat  _opexsatloc6;
extern _cvint  _opexsatparal;
extern _cvint  _opexsatoff1;
extern _cvint  _opexsatoff2;
extern _cvint  _opexsatoff3;
extern _cvint  _opexsatoff4;
extern _cvint  _opexsatoff5;
extern _cvint  _opexsatoff6;
extern _cvint  _opexsatlen1;
extern _cvint  _opexsatlen2;
extern _cvint  _opexsatlen3;
extern _cvint  _opexsatlen4;
extern _cvint  _opexsatlen5;
extern _cvint  _opexsatlen6;
extern _cvfloat  _opdfsathick1;
extern _cvfloat  _opdfsathick2;
extern _cvfloat  _opdfsathick3;
extern _cvfloat  _opdfsathick4;
extern _cvfloat  _opdfsathick5;
extern _cvfloat  _opdfsathick6;
extern _cvfloat  _opvenc;
extern _cvint  _opflaxx;
extern _cvint  _opflaxy;
extern _cvint  _opflaxz;
extern _cvint  _opflaxall;
extern _cvint  _opproject;
extern _cvint  _opcollapse;
extern _cvint  _oprlflow;
extern _cvint  _opapflow;
extern _cvint  _opsiflow;
extern _cvint  _opmagc;
extern _cvint  _opflrecon;
extern _cvint  _project;
extern _cvint  _vas_ovrhd;
extern _cvint  _slice_col;
extern _cvint  _phase_col;
extern _cvint  _read_col;
extern _cvint  _mag_mask;
extern _cvint  _phase_cor;
extern _cvint  _extras;
extern _cvint  _mag_create;
extern _cvint  _rl_flow;
extern _cvint  _ap_flow;
extern _cvint  _si_flow;
extern _cvint  _imagenum;
extern _cvint  _motsa_ovrhd;
extern _cvint  _oprampdir;
extern _cvint  _opfcaxis;
extern _cvint  _ophrate;
extern _cvint  _oparr;
extern _cvint  _ophrep;
extern _cvint  _optdel1;
extern _cvint  _optseq;
extern _cvint  _opphases;
extern _cvint  _opcardseq;
extern _cvint  _opmphases;
extern _cvint  _oparrmon;
extern _cvint  _opvps;
extern _cvint  _opetl;
extern _cvint  _opnecho;
extern _cvint  _opautote;
extern _cvint  _opte;
extern _cvint  _opte2;
extern _cvint  _optefw;
extern _cvint  _opti;
extern _cvint  _opirmode;
extern _cvint  _optr;
extern _cvfloat  _opflip;
extern _cvfloat  _opfov;
extern _cvfloat  _opphasefov;
extern _cvfloat  _opfreqfov;
extern _cvint  _opslquant;
extern _cvint  _opileave;
extern _cvfloat  _opslthick;
extern _cvfloat  _opslspace;
extern _cvint  _opcoax;
extern _cvfloat  _opvthick;
extern _cvint  _opvquant;
extern _cvint  _opovl;
extern _cvfloat  _oplenrl;
extern _cvfloat  _oplenap;
extern _cvfloat  _oplensi;
extern _cvfloat  _oplocrl;
extern _cvfloat  _oplocap;
extern _cvfloat  _oplocsi;
extern _cvfloat  _oprlcsiis;
extern _cvfloat  _opapcsiis;
extern _cvfloat  _opsicsiis;
extern _cvint  _opxres;
extern _cvint  _opyres;
extern _cvfloat  _opnex;
extern _cvint  _opslicecnt;
extern _cvint  _opspf;
extern _cvint  _opcfsel;
extern _cvfloat  _oprbw;
extern _cvfloat  _oprbw2;
extern _cvint  _opchrate;
extern _cvint  _opcphases;
extern _cvint  _opclocs;
extern _cvint  _opmctr;
extern _cvint  _opmultrecv;
extern _cvint  _specnuc;
extern _cvint  _specpts;
extern _cvint  _specwidth;
extern _cvint  _specnavs;
extern _cvint  _specnex;
extern _cvint  _specdwells;
extern _cvint  _acquire_type;
extern _cvint  _pixmtband;
extern _cvint  _pibbandfilt;
extern _cvint  _asslquant;
extern _cvfloat  _asflip;
extern _cvfloat  _asslthick;
extern _cvint  _asxres;
extern _cvint  _asyres;
extern _cvint  _asbaseline;
extern _cvint  _asrhblank;
extern _cvint  _asptsize;
extern _cvint  _opascalcfov;
extern _cvint  _opepi;
extern _cvint  _optlrdrf;
extern _cvint  _opnshots;
extern _cvint  _oprtcgate;
extern _cvint  _oprtrate;
extern _cvint  _oprtrep;
extern _cvint  _oprttdel1;
extern _cvint  _oprttseq;
extern _cvint  _oprtcardseq;
extern _cvint  _oprtarr;
extern _cvint  _oprtpoint;
extern _cvint  _opssrf;
extern _cvint  _opt2prep;
extern _cvint  _opspiral;
extern _cvint  _piresol;
extern _cvint  _pioverlap;
extern _cvint  _opfulltrain;
extern _cvint  _pi_neg_sp;
extern _cvfloat  _piisvaldef;
extern _cvint  _pidmode;
extern _cvint  _piviews;
extern _cvint  _piclckcnt;
extern _cvfloat  _avmintscan;
extern _cvint  _pitslice;
extern _cvfloat  _pitscan;
extern _cvint  _pisaveinter;
extern _cvint  _pivextras;
extern _cvint  _pinecho;
extern _cvfloat  _piscancenter;
extern _cvint  _pismode;
extern _cvint  _ihtr;
extern _cvint  _ihti;
extern _cvint  _ihtdel1;
extern _cvfloat  _ihnex;
extern _cvfloat  _ihflip;
extern _cvint  _ihte1;
extern _cvint  _ihte2;
extern _cvint  _ihte3;
extern _cvint  _ihte4;
extern _cvint  _ihte5;
extern _cvint  _ihte6;
extern _cvint  _ihte7;
extern _cvint  _ihte8;
extern _cvint  _ihte9;
extern _cvint  _ihte10;
extern _cvint  _ihte11;
extern _cvint  _ihte12;
extern _cvint  _ihte13;
extern _cvint  _ihte14;
extern _cvint  _ihte15;
extern _cvint  _ihte16;
extern _cvfloat  _ihvbw1;
extern _cvfloat  _ihvbw2;
extern _cvfloat  _ihvbw3;
extern _cvfloat  _ihvbw4;
extern _cvfloat  _ihvbw5;
extern _cvfloat  _ihvbw6;
extern _cvfloat  _ihvbw7;
extern _cvfloat  _ihvbw8;
extern _cvfloat  _ihvbw9;
extern _cvfloat  _ihvbw10;
extern _cvfloat  _ihvbw11;
extern _cvfloat  _ihvbw12;
extern _cvfloat  _ihvbw13;
extern _cvfloat  _ihvbw14;
extern _cvfloat  _ihvbw15;
extern _cvfloat  _ihvbw16;
extern _cvint  _ihnegscanspacing;
extern _cvint  _ihoffsetfreq;
extern _cvint  _opuser_usage_tag;
extern _cvint  _rhuser_usage_tag;
extern _cvint  _rhFillMapMSW;
extern _cvint  _rhFillMapLSW;
extern _cvint  _rhbline;
extern _cvint  _rhblank;
extern _cvint  _rhnavs;
extern _cvint  _rhnslices;
extern _cvint  _rhnframes;
extern _cvint  _rhfrsize;
extern _cvint  _rhnecho;
extern _cvint  _rhtype;
extern _cvint  _rhtype1;
extern _cvint  _rhformat;
extern _cvint  _rhptsize;
extern _cvint  _rhnpomp;
extern _cvint  _rhrcctrl;
extern _cvint  _rhdacqctrl;
extern _cvint  _rhexecctrl;
extern _cvint  _rhfdctrl;
extern _cvfloat  _rhxoff;
extern _cvfloat  _rhyoff;
extern _cvint  _rhrecon;
extern _cvint  _rhdatacq;
extern _cvint  _rhvquant;
extern _cvint  _rhslblank;
extern _cvint  _rhhnover;
extern _cvint  _rhoscans;
extern _cvint  _rhddaover;
extern _cvfloat  _rhzeroph;
extern _cvfloat  _rhalpha;
extern _cvfloat  _rhnwin;
extern _cvfloat  _rhntran;
extern _cvfloat  _rhfermw;
extern _cvfloat  _rhfermr;
extern _cvfloat  _rhferme;
extern _cvfloat  _rhclipmin;
extern _cvfloat  _rhclipmax;
extern _cvfloat  _rhdoffset;
extern _cvint  _rhudasave;
extern _cvint  _rhsspsave;
extern _cvfloat  _rhscalei;
extern _cvfloat  _rhscaleq;
extern _cvint  _rhnpasses;
extern _cvint  _rhrawsize;
extern _cvint  _rhincrpass;
extern _cvint  _rhinitpass;
extern _cvint  _rhmethod;
extern _cvint  _rhdaxres;
extern _cvint  _rhdayres;
extern _cvint  _rhrcxres;
extern _cvint  _rhrcyres;
extern _cvint  _rhimsize;
extern _cvfloat  _rhuser0;
extern _cvfloat  _rhuser1;
extern _cvfloat  _rhuser2;
extern _cvfloat  _rhuser3;
extern _cvfloat  _rhuser4;
extern _cvfloat  _rhuser5;
extern _cvfloat  _rhuser6;
extern _cvfloat  _rhuser7;
extern _cvfloat  _rhuser8;
extern _cvfloat  _rhuser9;
extern _cvfloat  _rhuser10;
extern _cvfloat  _rhuser11;
extern _cvfloat  _rhuser12;
extern _cvfloat  _rhuser13;
extern _cvfloat  _rhuser14;
extern _cvfloat  _rhuser15;
extern _cvfloat  _rhuser16;
extern _cvfloat  _rhuser17;
extern _cvfloat  _rhuser18;
extern _cvfloat  _rhuser19;
extern _cvfloat  _rhuser20;
extern _cvfloat  _rhuser21;
extern _cvfloat  _rhuser22;
extern _cvfloat  _rhuser23;
extern _cvfloat  _rhuser24;
extern _cvfloat  _rhuser25;
extern _cvfloat  _rhuser26;
extern _cvfloat  _rhuser27;
extern _cvfloat  _rhuser28;
extern _cvfloat  _rhuser29;
extern _cvfloat  _rhuser30;
extern _cvfloat  _rhuser31;
extern _cvfloat  _rhuser32;
extern _cvfloat  _rhuser33;
extern _cvfloat  _rhuser34;
extern _cvfloat  _rhuser35;
extern _cvfloat  _rhuser36;
extern _cvfloat  _rhuser37;
extern _cvfloat  _rhuser38;
extern _cvfloat  _rhuser39;
extern _cvfloat  _rhuser40;
extern _cvfloat  _rhuser41;
extern _cvfloat  _rhuser42;
extern _cvfloat  _rhuser43;
extern _cvfloat  _rhuser44;
extern _cvfloat  _rhuser45;
extern _cvfloat  _rhuser46;
extern _cvfloat  _rhuser47;
extern _cvfloat  _rhuser48;
extern _cvint  _rhdab0s;
extern _cvint  _rhdab0e;
extern _cvfloat  _rhctr;
extern _cvfloat  _rhcrrtime;
extern _cvint  _rhcphases;
extern _cvint  _rhovl;
extern _cvint  _rhvtype;
extern _cvfloat  _rhvenc;
extern _cvfloat  _rhvcoefxa;
extern _cvfloat  _rhvcoefxb;
extern _cvfloat  _rhvcoefxc;
extern _cvfloat  _rhvcoefxd;
extern _cvfloat  _rhvcoefya;
extern _cvfloat  _rhvcoefyb;
extern _cvfloat  _rhvcoefyc;
extern _cvfloat  _rhvcoefyd;
extern _cvfloat  _rhvcoefza;
extern _cvfloat  _rhvcoefzb;
extern _cvfloat  _rhvcoefzc;
extern _cvfloat  _rhvcoefzd;
extern _cvfloat  _rhvmcoef1;
extern _cvfloat  _rhvmcoef2;
extern _cvfloat  _rhvmcoef3;
extern _cvfloat  _rhvmcoef4;
extern _cvfloat  _rhphasescale;
extern _cvfloat  _rhfreqscale;
extern _cvint  _rawmode;
extern _cvint  _rhileaves;
extern _cvint  _rhkydir;
extern _cvint  _rhalt;
extern _cvint  _rhreps;
extern _cvint  _rhref;
extern _cvint  _rhpcthrespts;
extern _cvint  _rhpcthrespct;
extern _cvint  _rhpcdiscbeg;
extern _cvint  _rhpcdiscmid;
extern _cvint  _rhpcdiscend;
extern _cvint  _rhpcileave;
extern _cvint  _rhpcextcorr;
extern _cvint  _rhrefframes;
extern _cvint  _rhpcsnore;
extern _cvint  _rhpcspacial;
extern _cvint  _rhpctemporal;
extern _cvfloat  _rhpcbestky;
extern _cvint  _rhhdbestky;
extern _cvint  _rhpcinvft;
extern _cvint  _rhpcctrl;
extern _cvint  _rhpctest;
extern _cvint  _rhpcgraph;
extern _cvint  _rhpclin;
extern _cvint  _rhpclinnorm;
extern _cvint  _rhpclinnpts;
extern _cvint  _rhpclinorder;
extern _cvint  _rhpclinfitwt;
extern _cvint  _rhpclinavg;
extern _cvint  _rhpccon;
extern _cvint  _rhpcconnorm;
extern _cvint  _rhpcconnpts;
extern _cvint  _rhpcconorder;
extern _cvint  _rhpcconfitwt;
extern _cvint  _rhvrgfxres;
extern _cvint  _rhvrgf;
extern _cvint  _rhbp_corr;
extern _cvfloat  _rhrecv_freq_s;
extern _cvfloat  _rhrecv_freq_e;
extern _cvint  _rhhniter;
extern _cvint  _rhfast_rec;
extern _cvint  _rhgridcontrol;
extern _cvint  _rhb0map;
extern _cvint  _rhtediff;
extern _cvfloat  _rhradiusa;
extern _cvfloat  _rhradiusb;
extern _cvfloat  _rhmaxgrad;
extern _cvfloat  _rhslewmax;
extern _cvfloat  _rhscanfov;
extern _cvfloat  _rhtsamp;
extern _cvfloat  _rhdensityfactor;
extern _cvfloat  _rhdispfov;
extern _cvint  _rhmotioncomp;
extern _cvint  _pititle;
extern _cvfloat  _opuser0;
extern _cvfloat  _opuser1;
extern _cvfloat  _opuser2;
extern _cvfloat  _opuser3;
extern _cvfloat  _opuser4;
extern _cvfloat  _opuser5;
extern _cvfloat  _opuser6;
extern _cvfloat  _opuser7;
extern _cvfloat  _opuser8;
extern _cvfloat  _opuser9;
extern _cvfloat  _opuser10;
extern _cvfloat  _opuser11;
extern _cvfloat  _opuser12;
extern _cvfloat  _opuser13;
extern _cvfloat  _opuser14;
extern _cvfloat  _opuser15;
extern _cvfloat  _opuser16;
extern _cvfloat  _opuser17;
extern _cvfloat  _opuser18;
extern _cvfloat  _opuser19;
extern _cvfloat  _opuser20;
extern _cvfloat  _opuser21;
extern _cvfloat  _opuser22;
extern _cvfloat  _opuser23;
extern _cvfloat  _opuser24;
extern _cvfloat  _opuser25;
extern _cvfloat  _opuser26;
extern _cvfloat  _opuser27;
extern _cvfloat  _opuser28;
extern _cvfloat  _opuser29;
extern _cvfloat  _opuser30;
extern _cvfloat  _opuser31;
extern _cvfloat  _opuser32;
extern _cvfloat  _opuser33;
extern _cvfloat  _opuser34;
extern _cvfloat  _opuser35;
extern _cvfloat  _opuser36;
extern _cvfloat  _opuser37;
extern _cvfloat  _opuser38;
extern _cvfloat  _opuser39;
extern _cvfloat  _opuser40;
extern _cvfloat  _opuser41;
extern _cvfloat  _opuser42;
extern _cvfloat  _opuser43;
extern _cvfloat  _opuser44;
extern _cvfloat  _opuser45;
extern _cvfloat  _opuser46;
extern _cvfloat  _opuser47;
extern _cvfloat  _opuser48;
extern _cvint  _pishldctrl;
extern _cvint  _pinolr;
extern _cvint  _pinoadc;
extern _cvint  _pimixtime;
extern _cvint  _psd_board_type;
extern _cvint  _cfcoilres;
extern _cvint  _cftxgate0;
extern _cvint  _cftxgate90;
extern _cvint  _cfcoilportvu;
extern _cvint  _cfcoilportvl;
extern _cvint  _cfcoilbias;
extern _cvint  _cfgradcoil;
extern SCAN_INFO scan_info[SLTAB_MAX];
extern DATA_ACQ_ORDER data_acq_order[DATA_ACQ_MAX];
extern ENTRY_POINT_TABLE entry_point_table[ENTRY_POINT_MAX];
extern int *ihtdeltab;
extern int *ihtrtab;
extern int avminnecho;
extern int avmaxnecho;
extern int avminte;
extern int avmaxte;
extern int avminte2;
extern int avmaxte2;
extern int avminti;
extern int avmaxti;
extern int avminbspti;
extern int avmaxbspti;
extern int avmintr;
extern int avmaxtr;
extern int avmaxphases;
extern int avmintseq;
extern int avmintdel1;
extern int pitdel1;
extern float avminfov;
extern float avmaxfov;
extern int avminslquant;
extern int avmaxslquant;
extern int avmaxacqs;
extern int avmaxyres;
extern int avmaxxres;
extern float avminrbw;
extern float avmaxrbw;
extern float avminrbw2;
extern float avmaxrbw2;
extern float avminvenc;
extern float avmaxvenc;
extern int avminsldelay;
extern int avmaxsldelay;
extern int avminfphases;
extern int avmaxfphases;
extern int avmaxovl;
extern int piimages ;
extern int pisatthick ;
extern int pisatthickx ;
extern int pisatthicky ;
extern int pisatthickz ;
extern int piautopause ;
extern int pislblank ;
extern int pitseq;
extern int piait;
extern int pietr;
extern int picsifov;
extern int pirlcsi;
extern int piapcsi;
extern int pisicsi;
extern int piroigrx;
extern int piadvise ;
extern int piadvmin ;
extern int piadvmax ;
extern int piadvtime ;
extern int piadvcard ;
extern int pifilt4 ;
extern int pifilt5 ;
extern int pifilt6 ;
extern int pifilt7 ;
extern int pitfeextra;
extern float pipsar;
extern float piasar;
extern int pitr;
extern int pichop;
extern int pitsp1;
extern int pitsp2;
extern int picalmode;
extern int pislquant;
extern int pinex;
extern int piuset;
extern int pimphscrn ;
extern int pifphasenub;
extern int pifphaseval2 ;
extern int pifphaseval3 ;
extern int pifphaseval4 ;
extern int pifphaseval5 ;
extern int pifphaseval6 ;
extern int pisldelnub;
extern int pisldelval3 ;
extern int pisldelval4 ;
extern int pisldelval5 ;
extern int pisldelval6 ;
extern int piacqnub;
extern int pisctim ;
extern int pifanub ;
extern int pifaval2 ;
extern int pifaval3 ;
extern int pifaval4 ;
extern int pifaval5 ;
extern int pifaval6 ;
extern int pisatnub ;
extern int piccsatnub ;
extern int pisupnub ;
extern int pietlnub ;
extern int pietlval2 ;
extern int pietlval3 ;
extern int pietlval4 ;
extern int pietlval5 ;
extern int pietlval6 ;
extern int piechnub ;
extern int piechval1 ;
extern int piechval2 ;
extern int piechval3 ;
extern int piechval4 ;
extern int piechval5 ;
extern int pitetype ;
extern int pite1nub ;
extern int pite1val2 ;
extern int pite1val3 ;
extern int pite1val4 ;
extern int pite1val5 ;
extern int pite1val6 ;
extern int pite2nub ;
extern int pite2val2 ;
extern int pite2val3 ;
extern int pite2val4 ;
extern int pite2val5 ;
extern int pite2val6 ;
extern int pitrnub ;
extern int pitrval2 ;
extern int pitrval3 ;
extern int pitrval4 ;
extern int pitrval5 ;
extern int pitrval6 ;
extern int pititype   ;
extern int pitinub    ;
extern int pitidefval ;
extern int pitival2   ;
extern int pitival3   ;
extern int pitival4   ;
extern int pitival5   ;
extern int pitival6   ;
extern int pirbwpage ;
extern int pircbnub ;
extern float pircbval2 ;
extern float pircbval3 ;
extern float pircbval4 ;
extern float pircbval5 ;
extern float pircbval6 ;
extern int pipscoptnub ;
extern int piflosup ;
extern int piflanub ;
extern int pivelnub ;
extern int piprojnub ;
extern int piaddinub ;
extern int piflrcnub ;
extern int piscran ;
extern int pifovnub ;
extern float pifovval2 ;
extern float pifovval3 ;
extern float pifovval4 ;
extern float pifovval5 ;
extern float pifovval6 ;
extern int piphasfovnub ;
extern int pifreqfovnub ;
extern int pistnub ;
extern float pistval2 ;
extern float pistval3 ;
extern float pistval4 ;
extern float pistval5 ;
extern float pistval6 ;
extern int piisnub ;
extern int piisil ;
extern float piisval2 ;
extern float piisval3 ;
extern float piisval4 ;
extern float piisval5 ;
extern float piisval6 ;
extern int pilocnub ;
extern int pilocval2 ;
extern int pilocval3 ;
extern int pilocval4 ;
extern int pilocval5 ;
extern int pilocval6 ;
extern int piactim ;
extern int piamnub ;
extern char piamval1[8] ;
extern char piamval2[8] ;
extern char piamval3[8] ;
extern char piamval4[8] ;
extern char piamval5[8] ;
extern char piamval6[8] ;
extern int piyresnub ;
extern int piyresval2 ;
extern int piyresval3 ;
extern int piyresval4 ;
extern int piyresval5 ;
extern int piyresval6 ;
extern int pixresnub ;
extern int pixresval2 ;
extern int pixresval3 ;
extern int pixresval4 ;
extern int pixresval5 ;
extern int pixresval6 ;
extern int pinexnub ;
extern float pinexval2 ;
extern float pinexval3 ;
extern float pinexval4 ;
extern float pinexval5 ;
extern float pinexval6 ;
extern float pisctim1 ;
extern float pisctim2 ;
extern float pisctim3 ;
extern float pisctim4 ;
extern float pisctim5 ;
extern float pisctim6 ;
extern int pipautype ;
extern int pipaunub ;
extern int pipauval2 ;
extern int pipauval3 ;
extern int pipauval4 ;
extern int pipauval5 ;
extern int pipauval6 ;
extern int pircb2nub ;
extern float pircb2val2 ;
extern float pircb2val3 ;
extern float pircb2val4 ;
extern float pircb2val5 ;
extern float pircb2val6 ;
extern int pisetup ;
extern int pihrepnub;
extern int pihrepval2;
extern int pihrepval3;
extern int pihrepval4;
extern int pihrepval5;
extern int pihrepval6;
extern int pite2type ;
extern int pifsefcnub ;
extern int pideffcaxis ;
extern int pislqnub ;
extern int pislqval2 ;
extern int pislqval3 ;
extern int pislqval4 ;
extern int pidefslq ;
extern int pislqval5 ;
extern int pirampnub ;
extern int pideframp ;
extern int pipctovl ;
extern int pidefovl ;
extern int piovlnub ;
extern int pitdel1nub ;
extern int pitrigwinnub ;
extern int pitseqnub ;
extern int piphasenub ;
extern int piphslnub ;
extern int piviewseg ;
extern PSD_FILTER_GEN psd_filt_spec[PSD_FILTER_MAX];
extern int pivascop ;
extern int pimultigroup ;
extern int pimultislab  ;
extern int pidefproj ;
extern int pidefflax ;
extern int pidefaddimg ;
extern int pidefflrc ;
extern short eg_sat_rot[6][9];
extern int pivpsdef;
extern int pidefrbw ;
extern int pigradcoil ;
extern float dfscale ;
extern int pipscdef ;
extern int avminrttseq;
extern int pitetr ;
extern int pirtrigwinnub ;
extern int pirtwindefval ;
extern int pirtwinval2 ;
extern int pirtwinval3 ;
extern int pirtwinval4 ;
extern int pirtwinval5 ;
extern int pirtwinval6 ;
extern int pirtseqnub ;
extern int pirttseq;
extern int pirtait;
extern int pirtetr;
extern int pirtrepnub ;
extern int pirtrepval2 ;
extern int pirtrepval3 ;
extern int pirtrepval4 ;
extern int pirtrepval5 ;
extern int pirtrepval6 ;
extern int pirtpointnub ;
extern int pirtpointval2 ;
extern int pirtpointval3 ;
extern int pirtpointval4 ;
extern int pirtpointval5 ;
extern int pirtpointval6 ;
extern int pishotnub ;
extern int pishotval2 ;
extern int pishotval3 ;
extern int pishotval4 ;
extern int pishotval5 ;
extern int pishotval6 ;
extern float piphasfovval2 ;
extern float piphasfovval3 ;
extern float piphasfovval4;
extern float piphasfovval5;
extern float piphasfovval6;
extern int rec_mode ;
extern int opnewgeo ;
extern int simulation ;
extern float cflinfrq ;
extern float cffield ;
extern float cfhpdl ;
extern float cfbpdl ;
extern float cfhpsl ;
extern float cfbpsl ;
extern float cfhpv ;
extern float cfbpv ;
extern float cfhqpc ;
extern float cfbqpc ;
extern float cfhllr ;
extern float cfbllr ;
extern float cfloss ;
extern int cfbwmin ;
extern int cfbwmin1 ;
extern float cfmaxave ;
extern float cfmaxpeak ;
extern int cftpssize ;
extern float cccal ;
extern float ccjcoil ;
extern int cfxfull ;
extern int cfyfull ;
extern int cfzfull ;
extern int cfdbmax ;
extern int cfbbmod ;
extern int cftrnew ;
extern int cfrecvst ;
extern int cfrecvend ;
extern int cfgradamp ;
extern int cfhtdel ;
extern int cfcftdel ;
extern float cfcgain ;
extern int cfcoilatten ;
extern int cfrfrapb ;
extern int cfrfraph ;
extern int cfrfmapb ;
extern int cfrfmaph ;
extern float cfrfmpeb ;
extern float cfrfmpeh ;
extern int cfrfmpwb ;
extern int cfrfmpwh ;
extern float cfrfmdcb ;
extern float cfrfmdch ;
extern int cfrfamptyp ;
extern int cfpwrmontyp ;
extern int cfpsdgraddly ;
extern int cfpsdrfdly ;
extern int cfxrdelay ;
extern int cfyrdelay ;
extern int cfzrdelay ;
extern int piphasfovnub2;
extern int piswapfc ;
extern int pidltime ;
extern float piphasfovval1 ;
extern int cfcoilshld ;
extern int cfrfunblank;
extern int cfrmp2xfs ;
extern int cffall2x0 ;
extern float cfxfs ;
extern float cfxfa ;
extern float cfxcc ;
extern float cfxbeta ;
extern int cfrmp2yfs ;
extern int cffall2y0 ;
extern float cfyfs ;
extern float cfyfa ;
extern float cfycc ;
extern float cfybeta ;
extern int cfrmp2zfs ;
extern int cffall2z0 ;
extern float cfzfs ;
extern float cfzfa ;
extern float cfzcc ;
extern float cfzbeta ;
extern int cffrecvst ;
extern int cffrecvend ;
extern int cffrecvnum ;
extern int cfxgram ;
extern int cfygram ;
extern int cfzgram ;
extern int cfxasm ;
extern int cfyasm ;
extern int cfzasm ;
extern int cfxgasm ;
extern int cfygasm ;
extern int cfzgasm ;
extern int cfxseries ;
extern int cfyseries ;
extern int cfzseries ;
extern int cfxnumpower ;
extern int cfynumpower ;
extern int cfznumpower ;
extern int cftuning ;
extern int cfrealtime ;
extern int cfcompress ;
extern float cfdbdtts ;
extern float cfdbdtper ;
extern float pidbdtts ;
extern float pidbdtper ;
extern int cfgcoiltype ;
extern int cfsrmode ;
extern float cfgpeakirms ;
extern float cfgcontirms ;
extern float cfgburstime ;
extern float cfxirms ;
extern float cfyirms ;
extern float cfzirms ;
extern float cfxipeak ;
extern float cfyipeak ;
extern float cfzipeak ;
extern float cfxamptran ;
extern float cfyamptran ;
extern float cfzamptran ;
extern float cfxiavrgabs ;
extern float cfyiavrgabs ;
extern float cfziavrgabs ;
extern float cfxirmspos ;
extern float cfyirmspos ;
extern float cfzirmspos ;
extern float cfxirmsneg ;
extern float cfyirmsneg ;
extern float cfzirmsneg ;
extern float cfxpwmdc ;
extern float cfypwmdc ;
extern float cfzpwmdc ;
extern int cfrmp2xfsfw ;
extern int cfrmp2yfsfw ;
extern int cfrmp2zfsfw ;
extern int cffall2x0fw ;
extern int cffall2y0fw ;
extern int cffall2z0fw ;
extern float cfmaxb1 ;
extern float cfmaxb1sqrd ;
extern float cfmaxb1rms ;
extern float cfdbdtdx ;
extern float cfdbdtdy ;
extern float cfdbdtdz ;
extern int sigrammode ;
extern _cvint  _rhrefframep;
extern _cvint  _rhscnframe;
extern _cvint  _rhpasframe;
extern float cfsrmodeconv ;
extern float cfsrmodeact ;
extern _cvint  _cont_flag;
extern _cvint  _optabent;
extern _cvint  _sifsetwokey;
extern _cvint  _iheesp;
extern _cvint  _oplandmark;
extern _cvint  _opautosldelay;
extern _cvint  _rhpcfitorig;
extern _cvint  _rhpcshotfirst;
extern _cvint  _rhpcshotlast;
extern _cvint  _rhpcmultegrp;
extern _cvint  _rhpclinfix;
extern _cvfloat  _rhpclinslope;
extern _cvint  _rhpcconfix;
extern _cvfloat  _rhpcconslope;
extern _cvint  _rhpccoil;
extern _cvint  _piforkvrgf;
extern _cvint  _pinofreqoffset;
extern _cvint  _opssfse;
extern _cvint  _t1flair_flag;
extern _cvfloat  _rhmaxcoef1a;
extern _cvfloat  _rhmaxcoef1b;
extern _cvfloat  _rhmaxcoef1c;
extern _cvfloat  _rhmaxcoef1d;
extern _cvfloat  _rhmaxcoef2a;
extern _cvfloat  _rhmaxcoef2b;
extern _cvfloat  _rhmaxcoef2c;
extern _cvfloat  _rhmaxcoef2d;
extern _cvfloat  _rhmaxcoef3a;
extern _cvfloat  _rhmaxcoef3b;
extern _cvfloat  _rhmaxcoef3c;
extern _cvfloat  _rhmaxcoef3d;
extern int avmaxtdel1;
extern int avminphases;
extern int avminetl;
extern int avmaxetl;
extern int avminyres;
extern int avminslicecnt;
extern int avmaxslicecnt;
extern int avmaxtseq;
extern int avminxres;
extern int avminnshots;
extern int avmaxnshots;
extern float avmaxphasefov;
extern float avminphasefov;
extern float avminslthick;
extern float avmaxslthick;
extern float avminnex;
extern float avmaxnex;
extern float avminflip;
extern float avmaxflip;
extern float avminslspace;
extern float avmaxslspace;
extern float cfmaxb1rmshead ;
extern _cvint  _opdiffuse;
extern _cvint  _opsavedf;
extern _cvint  _opmintedif;
extern _cvint  _opdfaxx;
extern _cvint  _opdfaxy;
extern _cvint  _opdfaxz;
extern _cvint  _opdfaxall;
extern _cvint  _opbval;
extern _cvint  _rhdptype;
extern _cvint  _rhutctrl;
extern _cvint  _opflair;
extern _cvfloat  _opmonfov;
extern _cvfloat  _opmonthick;
extern _cvfloat  _opdose;
extern _cvfloat  _rhzipfact;
extern _cvint  _opzip512;
extern _cvint  _opzip1024;
extern _cvint  _opslzip2;
extern _cvint  _opslzip4;
extern int pidifpage;
extern int pidifaxnub;
extern char pidifaxval1[6];
extern char pidifaxval2[6];
extern char pidifaxval3[6];
extern char pidifaxval4[6];
extern char pidifaxval5[6];
extern int pidefbval;
extern int pibvnub;
extern int pibval2;
extern int pibval3;
extern int pibval4;
extern int pidifrecnub;
extern char pidifrecval1[30];
extern char pidfirecval2[30];
extern char pidfirecval3[30];
extern char pidfirecval4[30];
extern char pidfirecval5[30];
extern int pimonitor;
extern int pimonfovnub;
extern float pimonfovval2;
extern float pimonfovval3;
extern float pimonfovval4;
extern float pidfmonfov;
extern int pimonthicknub;
extern float pimonthickval2;
extern float pimonthickval3;
extern float pimonthickval4;
extern float pidfmonthick;
extern SCAN_INFO mon_loc;
extern _cvint  _opnvcoil;
extern _cvint  _opcmon;
extern _cvint  _opsmartprep;
extern int pizmult ;
extern int piccsat_obl ;
extern int pifcinenub    ;
extern int pifcinedefval ;
extern int pifcineval2   ;
extern int pifcineval3	  ;
extern int pifcineval4	  ;
extern int pitagging      ;
extern int pitagspcdefval ;
extern int pitagspcval2   ;
extern int pitagspcval3   ;
extern int pitagspcval4   ;
extern int pibsptinub    ;
extern int pibsptidefval ;
extern int pibsptival2   ;
extern int pibsptival3   ;
extern int pibsptival4   ;
extern int pibsptival5   ;
extern int pibsptival6   ;
extern float cfxmgrampow ;
extern float cfymgrampow ;
extern float cfzmgrampow ;
extern float cfsdlim ;
extern float cfxrsat ;
extern float cfyrsat ;
extern float cfzrsat ;
extern float cfxvsat ;
extern float cfyvsat ;
extern float cfzvsat ;
extern float cfgpmpow ;
extern float cfmgps ;
extern float cfvhr ;
extern float cfrcoil ;
extern float cflcoil ;
extern float cfraccoil ;
extern float cfpmgs ;
extern float cfrhr ;
extern float cfxvpwm ;
extern float cfyvpwm ;
extern float cfzvpwm ;
extern float cfcerdbw1 ;
extern float cfcerdbw2 ;
extern float cfcerdbw3 ;
extern float cfcerdbw4 ;
extern int cffastprescan ;
extern _cvint  _opcgatetype;
extern _cvint  _opadvgate;
extern _cvint  _opfcine;
extern _cvint  _ihfcineim;
extern _cvint  _ihfcinent;
extern _cvint  _rhfcinemode;
extern _cvint  _rhfcinearw;
extern _cvint  _rhvps;
extern _cvint  _rhvvsaimgs;
extern _cvint  _rhvvstr;
extern _cvint  _rhvvsgender;
extern _cvint  _opbsp;
extern _cvint  _opbspti;
extern _cvint  _opautoti;
extern _cvint  _opautobti;
extern _cvint  _ihbspti;
extern _cvint  _optagging;
extern _cvint  _optagspc;
extern _cvfloat  _ihtagfa;
extern _cvfloat  _ihtagor;
extern _cvfloat  _pifractecho;
extern _cvint  _oprealtime;
extern _cvint  _opET;
extern _cvint  _opmultistation;
extern _cvint  _opnostations;
extern _cvint  _opstation;
extern _cvint  _pscahead;
extern _cvint  _opprescanopt;
extern _cvint  _autoadvtoscn;
extern _cvint  _opprotRxMode;
extern int pimultistation ;
extern int piautostep ;
extern int pisioverlap ;
extern int csi_grid_on ;
extern int pispecprescan ;
extern int picsimode ;
extern int rhrlfov ;
extern int rhapfov ;
extern int rhsifov ;
extern int cfcerdtype ;
extern int cfpicture ;
extern _cvint  _acqs;
extern _cvint  _avround;
extern _cvint  _baseline;
extern _cvint  _nex;
extern _cvfloat  _fn;
extern _cvfloat  _nop;
extern _cvint  _acq_type;
extern _cvint  _seq_type;
extern _cvint  _num_images;
extern _cvint  _mag;
extern _cvint  _pha;
extern _cvint  _imag;
extern _cvint  _qmag;
extern _cvint  _exnex;
extern _cvint  _slquant1;
extern _cvint  _psd_grd_wait;
extern _cvint  _psd_rf_wait;
extern _cvint  _pos_moment_start;
extern _cvint  _mps1rf1_inst;
extern _cvint  _scanrf1_inst;
extern _cvint  _cfcarddelay;
extern _cvfloat  _GAM;
extern _cvint  _psd_card_hdwr_delay;
extern _cvint  _off90;
extern _cvint  _TR_SLOP;
extern _cvint  _TR_PASS;
extern _cvint  _TR_PASS3D;
extern _cvint  _csweight;
extern _cvfloat  _truenex;
extern _cvint  _eg_phaseres;
extern _cvint  _sp_satcard_loc;
extern _cvint  _min_rfdycc;
extern _cvint  _min_rfavgpow;
extern _cvint  _coll_prefls;
extern _cvint  _maxGradRes;
extern _cvfloat  _dfg;
extern _cvfloat  _pg_beta;
extern _cvint  _split_dab;
extern _cvfloat  _freq_scale;
extern _cvint  _numrecv;
extern _cvint  _pe_on;
extern _cvfloat  _psd_targetscale;
extern _cvfloat  _logxfs;
extern _cvfloat  _logyfs;
extern _cvfloat  _logzfs;
extern _cvint  _logxrt;
extern _cvint  _logyrt;
extern _cvint  _logzrt;
extern _cvint  _logxft;
extern _cvint  _logyft;
extern _cvint  _logzft;
extern _cvfloat  _logxfa;
extern _cvfloat  _logyfa;
extern _cvfloat  _logzfa;
extern _cvfloat  _logxcc;
extern _cvfloat  _logycc;
extern _cvfloat  _logzcc;
extern _cvfloat  _logxbeta;
extern _cvfloat  _logybeta;
extern _cvfloat  _logzbeta;
extern _cvfloat  _logtx;
extern _cvfloat  _logty;
extern _cvfloat  _logtz;
extern _cvfloat  _logtx_xy;
extern _cvfloat  _logtx_xz;
extern _cvfloat  _logty_xy;
extern _cvfloat  _logty_yz;
extern _cvfloat  _logtz_xz;
extern _cvfloat  _logtz_yz;
extern _cvfloat  _logtx_xyz;
extern _cvfloat  _logty_xyz;
extern _cvfloat  _logtz_xyz;
extern _cvint  _min_rfrmsb1;
extern _cvfloat  _psd_zero;
extern _cvint  _minseqgram_t;
extern _cvint  _lx_pwmtime;
extern _cvint  _ly_pwmtime;
extern _cvint  _lz_pwmtime;
extern _cvint  _px_pwmtime;
extern _cvint  _py_pwmtime;
extern _cvint  _pz_pwmtime;
extern _cvint  _minseqcoil_t;
extern _cvfloat  _xa2s;
extern _cvfloat  _ya2s;
extern _cvfloat  _za2s;
extern _cvint  _minseqgrddrv_t;
extern _cvint  _minseqgrddrvx_t;
extern _cvint  _minseqgrddrvy_t;
extern _cvint  _minseqgrddrvz_t;
extern _cvfloat  _powerx;
extern _cvfloat  _powery;
extern _cvfloat  _powerz;
extern _cvfloat  _pospowerx;
extern _cvfloat  _pospowery;
extern _cvfloat  _pospowerz;
extern _cvfloat  _negpowerx;
extern _cvfloat  _negpowery;
extern _cvfloat  _negpowerz;
extern _cvfloat  _amptrans_lx;
extern _cvfloat  _amptrans_ly;
extern _cvfloat  _amptrans_lz;
extern _cvfloat  _amptrans_px;
extern _cvfloat  _amptrans_py;
extern _cvfloat  _amptrans_pz;
extern _cvfloat  _abspower_lx;
extern _cvfloat  _abspower_ly;
extern _cvfloat  _abspower_lz;
extern _cvfloat  _abspower_px;
extern _cvfloat  _abspower_py;
extern _cvfloat  _abspower_pz;
extern _cvint  _time_pgen;
extern _cvint  _cont_debug;
extern _cvint  _maxpc_cor;
extern _cvint  _maxpc_debug;
extern _cvint  _maxpc_points;
extern _cvint  _tsamp;
extern _cvint  _seg_debug;
extern _cvint  _gradHeatMethod;
extern _cvint  _minseqpwm_x;
extern _cvint  _minseqpwm_y;
extern _cvint  _minseqpwm_z;
extern _cvint  _minseqgpm_t;
extern _cvint  _sgd_perf_simulate;
extern _cvint  _gradHeatFile;
extern _cvint  _seqEntryIndex;
extern _cvint  _dbdt_debug;
extern _cvint  _reilly_mode;
extern _cvint  _dbdt_disable;
extern _cvint  _use_dbdt_opt;
extern _cvfloat  _srderate;
extern RSP_INFO rsp_info[DATA_ACQ_MAX];
extern long rsprot[TRIG_ROT_MAX][9];
extern long rsptrigger[TRIG_ROT_MAX];
extern long ipg_alloc_instr[PSD_MAX_PROCESSORS] ;
extern RSP_INFO asrsp_info[3];
extern long sat_rot_matrices[14][9];
extern int TARDIS_FREQ_OFFSET;
extern PHYS_GRAD phygrd;
extern LOG_GRAD  loggrd;
extern LOG_GRAD  satloggrd;
extern LOG_GRAD  asloggrd;
extern SCAN_INFO asscan_info[3];
extern long PSrot[PRESCAN_ROT_MAX][9];
extern PHASE_OFF phase_off[DATA_ACQ_MAX];
extern int yres_phase;
extern int yoffs1;
extern int off_rfcsz_base[DATA_ACQ_MAX];
extern SCAN_INFO scan_info_base[1];
extern float xyz_base[DATA_ACQ_MAX][3];
extern long rsprot_base[TRIG_ROT_MAX][9];
extern int rtia_first_scan_flag ;
extern long _lastipgex ;

#endif /* epic_ext_h */


