/*
 *  epic.exportstr.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_epic_exportstr_h
#define h_epic_exportstr_h














_export _scan_info={(char *) scan_info,sizeof(scan_info),GE_STRUCT};




_export _data_acq_order={(char *) data_acq_order,sizeof(data_acq_order),GE_STRUCT};

_export _entry_point_table={(char *) entry_point_table,sizeof(entry_point_table),GE_STRUCT};

_export _ihtdeltab={(char *) &ihtdeltab,sizeof(ihtdeltab),GE_STRUCT};
_export _ihtrtab={(char *) &ihtrtab,sizeof(ihtrtab),GE_STRUCT};



_export _avminnecho={(char *) &avminnecho,sizeof(avminnecho),GE_INT};
_export _avmaxnecho={(char *) &avmaxnecho,sizeof(avmaxnecho),GE_INT};
_export _avminte={(char *) &avminte,sizeof(avminte),GE_INT};
_export _avmaxte={(char *) &avmaxte,sizeof(avmaxte),GE_INT};
_export _avminte2={(char *) &avminte2,sizeof(avminte2),GE_INT};
_export _avmaxte2={(char *) &avmaxte2,sizeof(avmaxte2),GE_INT};
_export _avminti={(char *) &avminti,sizeof(avminti),GE_INT};
_export _avmaxti={(char *) &avmaxti,sizeof(avmaxti),GE_INT};
_export _avminbspti={(char *) &avminbspti,sizeof(avminbspti),GE_INT};
_export _avmaxbspti={(char *) &avmaxbspti,sizeof(avmaxbspti),GE_INT};
_export _avmintr={(char *) &avmintr,sizeof(avmintr),GE_INT};
_export _avmaxtr={(char *) &avmaxtr,sizeof(avmaxtr),GE_INT};



_export _avmaxphases={(char *) &avmaxphases,sizeof(avmaxphases),GE_INT};
_export _avmintseq={(char *) &avmintseq,sizeof(avmintseq),GE_INT};
_export _avmintdel1={(char *) &avmintdel1,sizeof(avmintdel1),GE_INT};
_export _pitdel1={(char *) &pitdel1,sizeof(pitdel1),GE_INT};



_export _avminfov={(char *) &avminfov,sizeof(avminfov),GE_FLOAT};
_export _avmaxfov={(char *) &avmaxfov,sizeof(avmaxfov),GE_FLOAT};
_export _avminslquant={(char *) &avminslquant,sizeof(avminslquant),GE_INT};
_export _avmaxslquant={(char *) &avmaxslquant,sizeof(avmaxslquant),GE_INT};
_export _avmaxacqs={(char *) &avmaxacqs,sizeof(avmaxacqs),GE_INT};



_export _avmaxyres={(char *) &avmaxyres,sizeof(avmaxyres),GE_INT};
_export _avmaxxres={(char *) &avmaxxres,sizeof(avmaxxres),GE_INT};

_export _avminrbw={(char *) &avminrbw,sizeof(avminrbw),GE_FLOAT};
_export _avmaxrbw={(char *) &avmaxrbw,sizeof(avmaxrbw),GE_FLOAT};

_export _avminrbw2={(char *) &avminrbw2,sizeof(avminrbw2),GE_FLOAT};
_export _avmaxrbw2={(char *) &avmaxrbw2,sizeof(avmaxrbw2),GE_FLOAT};





_export _avminvenc={(char *) &avminvenc,sizeof(avminvenc),GE_FLOAT};
_export _avmaxvenc={(char *) &avmaxvenc,sizeof(avmaxvenc),GE_FLOAT};


_export _avminsldelay={(char *) &avminsldelay,sizeof(avminsldelay),GE_INT};
_export _avmaxsldelay={(char *) &avmaxsldelay,sizeof(avmaxsldelay),GE_INT};
_export _avminfphases={(char *) &avminfphases,sizeof(avminfphases),GE_INT};
_export _avmaxfphases={(char *) &avmaxfphases,sizeof(avmaxfphases),GE_INT};


_export _avmaxovl={(char *) &avmaxovl,sizeof(avmaxovl),GE_INT};



_export _piimages={(char *) &piimages,sizeof(piimages),GE_INT};


_export _pisatthick={(char *) &pisatthick,sizeof(pisatthick),GE_INT};
_export _pisatthickx={(char *) &pisatthickx,sizeof(pisatthickx),GE_INT};
_export _pisatthicky={(char *) &pisatthicky,sizeof(pisatthicky),GE_INT};
_export _pisatthickz={(char *) &pisatthickz,sizeof(pisatthickz),GE_INT};

_export _piautopause={(char *) &piautopause,sizeof(piautopause),GE_INT};
_export _pislblank={(char *) &pislblank,sizeof(pislblank),GE_INT};


_export _pitseq={(char *) &pitseq,sizeof(pitseq),GE_INT};
_export _piait={(char *) &piait,sizeof(piait),GE_INT};
_export _pietr={(char *) &pietr,sizeof(pietr),GE_INT};


_export _picsifov={(char *) &picsifov,sizeof(picsifov),GE_INT};
_export _pirlcsi={(char *) &pirlcsi,sizeof(pirlcsi),GE_INT};
_export _piapcsi={(char *) &piapcsi,sizeof(piapcsi),GE_INT};
_export _pisicsi={(char *) &pisicsi,sizeof(pisicsi),GE_INT};
_export _piroigrx={(char *) &piroigrx,sizeof(piroigrx),GE_INT};



_export _piadvise={(char *) &piadvise,sizeof(piadvise),GE_INT};





















_export 

_piadvmin={(char *) &piadvmin,sizeof(piadvmin),GE_INT};
_export 

_piadvmax={(char *) &piadvmax,sizeof(piadvmax),GE_INT};


_export 
_piadvtime={(char *) &piadvtime,sizeof(piadvtime),GE_INT};


_export 

_piadvcard={(char *) &piadvcard,sizeof(piadvcard),GE_INT};



_export _pifilt4={(char *) &pifilt4,sizeof(pifilt4),GE_INT};
_export _pifilt5={(char *) &pifilt5,sizeof(pifilt5),GE_INT};
_export _pifilt6={(char *) &pifilt6,sizeof(pifilt6),GE_INT};
_export _pifilt7={(char *) &pifilt7,sizeof(pifilt7),GE_INT};
_export _pitfeextra={(char *) &pitfeextra,sizeof(pitfeextra),GE_INT};



_export _pipsar={(char *) &pipsar,sizeof(pipsar),GE_FLOAT};
_export _piasar={(char *) &piasar,sizeof(piasar),GE_FLOAT};


_export _pitr={(char *) &pitr,sizeof(pitr),GE_INT};
_export _pichop={(char *) &pichop,sizeof(pichop),GE_INT};
_export _pitsp1={(char *) &pitsp1,sizeof(pitsp1),GE_INT};
_export _pitsp2={(char *) &pitsp2,sizeof(pitsp2),GE_INT};
_export _picalmode={(char *) &picalmode,sizeof(picalmode),GE_INT};
_export _pislquant={(char *) &pislquant,sizeof(pislquant),GE_INT};
_export _pinex={(char *) &pinex,sizeof(pinex),GE_INT};




_export _piuset={(char *) &piuset,sizeof(piuset),GE_INT};

_export _pimphscrn={(char *) &pimphscrn,sizeof(pimphscrn),GE_INT};



_export _pifphasenub={(char *) &pifphasenub,sizeof(pifphasenub),GE_INT};
_export _pifphaseval2={(char *) &pifphaseval2,sizeof(pifphaseval2),GE_INT};
_export _pifphaseval3={(char *) &pifphaseval3,sizeof(pifphaseval3),GE_INT};
_export _pifphaseval4={(char *) &pifphaseval4,sizeof(pifphaseval4),GE_INT};
_export _pifphaseval5={(char *) &pifphaseval5,sizeof(pifphaseval5),GE_INT};
_export _pifphaseval6={(char *) &pifphaseval6,sizeof(pifphaseval6),GE_INT};

_export _pisldelnub={(char *) &pisldelnub,sizeof(pisldelnub),GE_INT};
_export _pisldelval3={(char *) &pisldelval3,sizeof(pisldelval3),GE_INT};
_export _pisldelval4={(char *) &pisldelval4,sizeof(pisldelval4),GE_INT};
_export _pisldelval5={(char *) &pisldelval5,sizeof(pisldelval5),GE_INT};
_export _pisldelval6={(char *) &pisldelval6,sizeof(pisldelval6),GE_INT};

_export _piacqnub={(char *) &piacqnub,sizeof(piacqnub),GE_INT};


_export _pisctim={(char *) &pisctim,sizeof(pisctim),GE_INT};

_export _pifanub={(char *) &pifanub,sizeof(pifanub),GE_INT};
_export _pifaval2={(char *) &pifaval2,sizeof(pifaval2),GE_INT};
_export _pifaval3={(char *) &pifaval3,sizeof(pifaval3),GE_INT};
_export _pifaval4={(char *) &pifaval4,sizeof(pifaval4),GE_INT};
_export _pifaval5={(char *) &pifaval5,sizeof(pifaval5),GE_INT};
_export _pifaval6={(char *) &pifaval6,sizeof(pifaval6),GE_INT};

_export _pisatnub={(char *) &pisatnub,sizeof(pisatnub),GE_INT};
_export _piccsatnub={(char *) &piccsatnub,sizeof(piccsatnub),GE_INT};

_export _pisupnub={(char *) &pisupnub,sizeof(pisupnub),GE_INT};

_export _pietlnub={(char *) &pietlnub,sizeof(pietlnub),GE_INT};
_export _pietlval2={(char *) &pietlval2,sizeof(pietlval2),GE_INT};
_export _pietlval3={(char *) &pietlval3,sizeof(pietlval3),GE_INT};
_export _pietlval4={(char *) &pietlval4,sizeof(pietlval4),GE_INT};
_export _pietlval5={(char *) &pietlval5,sizeof(pietlval5),GE_INT};
_export _pietlval6={(char *) &pietlval6,sizeof(pietlval6),GE_INT};

_export _piechnub={(char *) &piechnub,sizeof(piechnub),GE_INT};
_export _piechval1={(char *) &piechval1,sizeof(piechval1),GE_INT};
_export _piechval2={(char *) &piechval2,sizeof(piechval2),GE_INT};
_export _piechval3={(char *) &piechval3,sizeof(piechval3),GE_INT};
_export _piechval4={(char *) &piechval4,sizeof(piechval4),GE_INT};
_export _piechval5={(char *) &piechval5,sizeof(piechval5),GE_INT};

_export _pitetype={(char *) &pitetype,sizeof(pitetype),GE_INT};
_export _pite1nub={(char *) &pite1nub,sizeof(pite1nub),GE_INT};
_export _pite1val2={(char *) &pite1val2,sizeof(pite1val2),GE_INT};
_export _pite1val3={(char *) &pite1val3,sizeof(pite1val3),GE_INT};
_export _pite1val4={(char *) &pite1val4,sizeof(pite1val4),GE_INT};
_export _pite1val5={(char *) &pite1val5,sizeof(pite1val5),GE_INT};
_export _pite1val6={(char *) &pite1val6,sizeof(pite1val6),GE_INT};

_export _pite2nub={(char *) &pite2nub,sizeof(pite2nub),GE_INT};
_export _pite2val2={(char *) &pite2val2,sizeof(pite2val2),GE_INT};
_export _pite2val3={(char *) &pite2val3,sizeof(pite2val3),GE_INT};
_export _pite2val4={(char *) &pite2val4,sizeof(pite2val4),GE_INT};
_export _pite2val5={(char *) &pite2val5,sizeof(pite2val5),GE_INT};
_export _pite2val6={(char *) &pite2val6,sizeof(pite2val6),GE_INT};

_export _pitrnub={(char *) &pitrnub,sizeof(pitrnub),GE_INT};
_export _pitrval2={(char *) &pitrval2,sizeof(pitrval2),GE_INT};
_export _pitrval3={(char *) &pitrval3,sizeof(pitrval3),GE_INT};
_export _pitrval4={(char *) &pitrval4,sizeof(pitrval4),GE_INT};
_export _pitrval5={(char *) &pitrval5,sizeof(pitrval5),GE_INT};
_export _pitrval6={(char *) &pitrval6,sizeof(pitrval6),GE_INT};

_export _pititype={(char *) &pititype,sizeof(pititype),GE_INT};
_export _pitinub={(char *) &pitinub,sizeof(pitinub),GE_INT};
_export _pitidefval={(char *) &pitidefval,sizeof(pitidefval),GE_INT};
_export _pitival2={(char *) &pitival2,sizeof(pitival2),GE_INT};
_export _pitival3={(char *) &pitival3,sizeof(pitival3),GE_INT};
_export _pitival4={(char *) &pitival4,sizeof(pitival4),GE_INT};
_export _pitival5={(char *) &pitival5,sizeof(pitival5),GE_INT};
_export _pitival6={(char *) &pitival6,sizeof(pitival6),GE_INT};

_export _pirbwpage={(char *) &pirbwpage,sizeof(pirbwpage),GE_INT};
_export _pircbnub={(char *) &pircbnub,sizeof(pircbnub),GE_INT};
_export _pircbval2={(char *) &pircbval2,sizeof(pircbval2),GE_FLOAT};
_export _pircbval3={(char *) &pircbval3,sizeof(pircbval3),GE_FLOAT};
_export _pircbval4={(char *) &pircbval4,sizeof(pircbval4),GE_FLOAT};
_export _pircbval5={(char *) &pircbval5,sizeof(pircbval5),GE_FLOAT};
_export _pircbval6={(char *) &pircbval6,sizeof(pircbval6),GE_FLOAT};

_export _pipscoptnub={(char *) &pipscoptnub,sizeof(pipscoptnub),GE_INT};



_export _piflosup={(char *) &piflosup,sizeof(piflosup),GE_INT};

_export _piflanub={(char *) &piflanub,sizeof(piflanub),GE_INT};
_export _pivelnub={(char *) &pivelnub,sizeof(pivelnub),GE_INT};
_export _piprojnub={(char *) &piprojnub,sizeof(piprojnub),GE_INT};
_export _piaddinub={(char *) &piaddinub,sizeof(piaddinub),GE_INT};
_export _piflrcnub={(char *) &piflrcnub,sizeof(piflrcnub),GE_INT};


_export _piscran={(char *) &piscran,sizeof(piscran),GE_INT};

_export _pifovnub={(char *) &pifovnub,sizeof(pifovnub),GE_INT};
_export _pifovval2={(char *) &pifovval2,sizeof(pifovval2),GE_FLOAT};
_export _pifovval3={(char *) &pifovval3,sizeof(pifovval3),GE_FLOAT};
_export _pifovval4={(char *) &pifovval4,sizeof(pifovval4),GE_FLOAT};
_export _pifovval5={(char *) &pifovval5,sizeof(pifovval5),GE_FLOAT};
_export _pifovval6={(char *) &pifovval6,sizeof(pifovval6),GE_FLOAT};

_export _piphasfovnub={(char *) &piphasfovnub,sizeof(piphasfovnub),GE_INT};

_export _pifreqfovnub={(char *) &pifreqfovnub,sizeof(pifreqfovnub),GE_INT};

_export _pistnub={(char *) &pistnub,sizeof(pistnub),GE_INT};
_export _pistval2={(char *) &pistval2,sizeof(pistval2),GE_FLOAT};
_export _pistval3={(char *) &pistval3,sizeof(pistval3),GE_FLOAT};
_export _pistval4={(char *) &pistval4,sizeof(pistval4),GE_FLOAT};
_export _pistval5={(char *) &pistval5,sizeof(pistval5),GE_FLOAT};
_export _pistval6={(char *) &pistval6,sizeof(pistval6),GE_FLOAT};

_export _piisnub={(char *) &piisnub,sizeof(piisnub),GE_INT};
_export _piisil={(char *) &piisil,sizeof(piisil),GE_INT};
_export _piisval2={(char *) &piisval2,sizeof(piisval2),GE_FLOAT};
_export _piisval3={(char *) &piisval3,sizeof(piisval3),GE_FLOAT};
_export _piisval4={(char *) &piisval4,sizeof(piisval4),GE_FLOAT};
_export _piisval5={(char *) &piisval5,sizeof(piisval5),GE_FLOAT};
_export _piisval6={(char *) &piisval6,sizeof(piisval6),GE_FLOAT};

_export _pilocnub={(char *) &pilocnub,sizeof(pilocnub),GE_INT};
_export _pilocval2={(char *) &pilocval2,sizeof(pilocval2),GE_INT};
_export _pilocval3={(char *) &pilocval3,sizeof(pilocval3),GE_INT};
_export _pilocval4={(char *) &pilocval4,sizeof(pilocval4),GE_INT};
_export _pilocval5={(char *) &pilocval5,sizeof(pilocval5),GE_INT};
_export _pilocval6={(char *) &pilocval6,sizeof(pilocval6),GE_INT};


_export _piactim={(char *) &piactim,sizeof(piactim),GE_INT};

_export _piamnub={(char *) &piamnub,sizeof(piamnub),GE_INT};
_export _piamval1={(char *) piamval1,sizeof(piamval1),GE_STRUCT};
_export _piamval2={(char *) piamval2,sizeof(piamval2),GE_STRUCT};
_export _piamval3={(char *) piamval3,sizeof(piamval3),GE_STRUCT};
_export _piamval4={(char *) piamval4,sizeof(piamval4),GE_STRUCT};
_export _piamval5={(char *) piamval5,sizeof(piamval5),GE_STRUCT};
_export _piamval6={(char *) piamval6,sizeof(piamval6),GE_STRUCT};

_export _piyresnub={(char *) &piyresnub,sizeof(piyresnub),GE_INT};
_export _piyresval2={(char *) &piyresval2,sizeof(piyresval2),GE_INT};
_export _piyresval3={(char *) &piyresval3,sizeof(piyresval3),GE_INT};
_export _piyresval4={(char *) &piyresval4,sizeof(piyresval4),GE_INT};
_export _piyresval5={(char *) &piyresval5,sizeof(piyresval5),GE_INT};
_export _piyresval6={(char *) &piyresval6,sizeof(piyresval6),GE_INT};

_export _pixresnub={(char *) &pixresnub,sizeof(pixresnub),GE_INT};
_export _pixresval2={(char *) &pixresval2,sizeof(pixresval2),GE_INT};
_export _pixresval3={(char *) &pixresval3,sizeof(pixresval3),GE_INT};

_export _pixresval4={(char *) &pixresval4,sizeof(pixresval4),GE_INT};
_export _pixresval5={(char *) &pixresval5,sizeof(pixresval5),GE_INT};
_export _pixresval6={(char *) &pixresval6,sizeof(pixresval6),GE_INT};

_export _pinexnub={(char *) &pinexnub,sizeof(pinexnub),GE_INT};
_export _pinexval2={(char *) &pinexval2,sizeof(pinexval2),GE_FLOAT};
_export _pinexval3={(char *) &pinexval3,sizeof(pinexval3),GE_FLOAT};
_export _pinexval4={(char *) &pinexval4,sizeof(pinexval4),GE_FLOAT};
_export _pinexval5={(char *) &pinexval5,sizeof(pinexval5),GE_FLOAT};
_export _pinexval6={(char *) &pinexval6,sizeof(pinexval6),GE_FLOAT};

_export _pisctim1={(char *) &pisctim1,sizeof(pisctim1),GE_FLOAT};
_export _pisctim2={(char *) &pisctim2,sizeof(pisctim2),GE_FLOAT};
_export _pisctim3={(char *) &pisctim3,sizeof(pisctim3),GE_FLOAT};
_export _pisctim4={(char *) &pisctim4,sizeof(pisctim4),GE_FLOAT};
_export _pisctim5={(char *) &pisctim5,sizeof(pisctim5),GE_FLOAT};
_export _pisctim6={(char *) &pisctim6,sizeof(pisctim6),GE_FLOAT};

_export _pipautype={(char *) &pipautype,sizeof(pipautype),GE_INT};
_export _pipaunub={(char *) &pipaunub,sizeof(pipaunub),GE_INT};
_export _pipauval2={(char *) &pipauval2,sizeof(pipauval2),GE_INT};
_export _pipauval3={(char *) &pipauval3,sizeof(pipauval3),GE_INT};
_export _pipauval4={(char *) &pipauval4,sizeof(pipauval4),GE_INT};
_export _pipauval5={(char *) &pipauval5,sizeof(pipauval5),GE_INT};
_export _pipauval6={(char *) &pipauval6,sizeof(pipauval6),GE_INT};

_export _pircb2nub={(char *) &pircb2nub,sizeof(pircb2nub),GE_INT};
_export _pircb2val2={(char *) &pircb2val2,sizeof(pircb2val2),GE_FLOAT};
_export _pircb2val3={(char *) &pircb2val3,sizeof(pircb2val3),GE_FLOAT};
_export _pircb2val4={(char *) &pircb2val4,sizeof(pircb2val4),GE_FLOAT};
_export _pircb2val5={(char *) &pircb2val5,sizeof(pircb2val5),GE_FLOAT};
_export _pircb2val6={(char *) &pircb2val6,sizeof(pircb2val6),GE_FLOAT};



_export _pisetup={(char *) &pisetup,sizeof(pisetup),GE_INT};


_export _pihrepnub={(char *) &pihrepnub,sizeof(pihrepnub),GE_INT};
_export _pihrepval2={(char *) &pihrepval2,sizeof(pihrepval2),GE_INT};
_export _pihrepval3={(char *) &pihrepval3,sizeof(pihrepval3),GE_INT};
_export _pihrepval4={(char *) &pihrepval4,sizeof(pihrepval4),GE_INT};
_export _pihrepval5={(char *) &pihrepval5,sizeof(pihrepval5),GE_INT};
_export _pihrepval6={(char *) &pihrepval6,sizeof(pihrepval6),GE_INT};

_export _pite2type={(char *) &pite2type,sizeof(pite2type),GE_INT};


_export _pifsefcnub={(char *) &pifsefcnub,sizeof(pifsefcnub),GE_INT};
_export _pideffcaxis={(char *) &pideffcaxis,sizeof(pideffcaxis),GE_INT};


_export _pislqnub={(char *) &pislqnub,sizeof(pislqnub),GE_INT};
_export _pislqval2={(char *) &pislqval2,sizeof(pislqval2),GE_INT};
_export _pislqval3={(char *) &pislqval3,sizeof(pislqval3),GE_INT};
_export _pislqval4={(char *) &pislqval4,sizeof(pislqval4),GE_INT};
_export _pidefslq={(char *) &pidefslq,sizeof(pidefslq),GE_INT};
_export _pislqval5={(char *) &pislqval5,sizeof(pislqval5),GE_INT};


_export _pirampnub={(char *) &pirampnub,sizeof(pirampnub),GE_INT};
_export _pideframp={(char *) &pideframp,sizeof(pideframp),GE_INT};


_export _pipctovl={(char *) &pipctovl,sizeof(pipctovl),GE_INT};
_export _pidefovl={(char *) &pidefovl,sizeof(pidefovl),GE_INT};
_export _piovlnub={(char *) &piovlnub,sizeof(piovlnub),GE_INT};


_export _pitdel1nub={(char *) &pitdel1nub,sizeof(pitdel1nub),GE_INT};
_export _pitrigwinnub={(char *) &pitrigwinnub,sizeof(pitrigwinnub),GE_INT};
_export _pitseqnub={(char *) &pitseqnub,sizeof(pitseqnub),GE_INT};
_export _piphasenub={(char *) &piphasenub,sizeof(piphasenub),GE_INT};
_export _piphslnub={(char *) &piphslnub,sizeof(piphslnub),GE_INT};
_export _piviewseg={(char *) &piviewseg,sizeof(piviewseg),GE_INT};

_export _psd_filt_spec={(char *) psd_filt_spec,sizeof(psd_filt_spec),GE_STRUCT};

_export _pivascop={(char *) &pivascop,sizeof(pivascop),GE_INT};

_export _pimultigroup={(char *) &pimultigroup,sizeof(pimultigroup),GE_INT};
_export _pimultislab={(char *) &pimultislab,sizeof(pimultislab),GE_INT};


_export _pidefproj={(char *) &pidefproj,sizeof(pidefproj),GE_INT};
_export _pidefflax={(char *) &pidefflax,sizeof(pidefflax),GE_INT};
_export _pidefaddimg={(char *) &pidefaddimg,sizeof(pidefaddimg),GE_INT};
_export _pidefflrc={(char *) &pidefflrc,sizeof(pidefflrc),GE_INT};


_export _eg_sat_rot={(char *) eg_sat_rot,sizeof(eg_sat_rot),GE_STRUCT};

_export _pivpsdef={(char *) &pivpsdef,sizeof(pivpsdef),GE_INT};

_export _pidefrbw={(char *) &pidefrbw,sizeof(pidefrbw),GE_INT};


_export _pigradcoil={(char *) &pigradcoil,sizeof(pigradcoil),GE_INT};

_export _dfscale={(char *) &dfscale,sizeof(dfscale),GE_FLOAT};


_export _pipscdef={(char *) &pipscdef,sizeof(pipscdef),GE_INT};

_export _avminrttseq={(char *) &avminrttseq,sizeof(avminrttseq),GE_INT};

_export _pitetr={(char *) &pitetr,sizeof(pitetr),GE_INT};

_export _pirtrigwinnub={(char *) &pirtrigwinnub,sizeof(pirtrigwinnub),GE_INT};
_export _pirtwindefval={(char *) &pirtwindefval,sizeof(pirtwindefval),GE_INT};
_export _pirtwinval2={(char *) &pirtwinval2,sizeof(pirtwinval2),GE_INT};
_export _pirtwinval3={(char *) &pirtwinval3,sizeof(pirtwinval3),GE_INT};
_export _pirtwinval4={(char *) &pirtwinval4,sizeof(pirtwinval4),GE_INT};
_export _pirtwinval5={(char *) &pirtwinval5,sizeof(pirtwinval5),GE_INT};
_export _pirtwinval6={(char *) &pirtwinval6,sizeof(pirtwinval6),GE_INT};

_export _pirtseqnub={(char *) &pirtseqnub,sizeof(pirtseqnub),GE_INT};
_export _pirttseq={(char *) &pirttseq,sizeof(pirttseq),GE_INT};
_export _pirtait={(char *) &pirtait,sizeof(pirtait),GE_INT};
_export _pirtetr={(char *) &pirtetr,sizeof(pirtetr),GE_INT};

_export _pirtrepnub={(char *) &pirtrepnub,sizeof(pirtrepnub),GE_INT};
_export _pirtrepval2={(char *) &pirtrepval2,sizeof(pirtrepval2),GE_INT};
_export _pirtrepval3={(char *) &pirtrepval3,sizeof(pirtrepval3),GE_INT};
_export _pirtrepval4={(char *) &pirtrepval4,sizeof(pirtrepval4),GE_INT};
_export _pirtrepval5={(char *) &pirtrepval5,sizeof(pirtrepval5),GE_INT};
_export _pirtrepval6={(char *) &pirtrepval6,sizeof(pirtrepval6),GE_INT};

_export _pirtpointnub={(char *) &pirtpointnub,sizeof(pirtpointnub),GE_INT};
_export _pirtpointval2={(char *) &pirtpointval2,sizeof(pirtpointval2),GE_INT};
_export _pirtpointval3={(char *) &pirtpointval3,sizeof(pirtpointval3),GE_INT};
_export _pirtpointval4={(char *) &pirtpointval4,sizeof(pirtpointval4),GE_INT};
_export _pirtpointval5={(char *) &pirtpointval5,sizeof(pirtpointval5),GE_INT};
_export _pirtpointval6={(char *) &pirtpointval6,sizeof(pirtpointval6),GE_INT};

_export _pishotnub={(char *) &pishotnub,sizeof(pishotnub),GE_INT};
_export _pishotval2={(char *) &pishotval2,sizeof(pishotval2),GE_INT};
_export _pishotval3={(char *) &pishotval3,sizeof(pishotval3),GE_INT};
_export _pishotval4={(char *) &pishotval4,sizeof(pishotval4),GE_INT};
_export _pishotval5={(char *) &pishotval5,sizeof(pishotval5),GE_INT};
_export _pishotval6={(char *) &pishotval6,sizeof(pishotval6),GE_INT};




_export _piphasfovval2={(char *) &piphasfovval2,sizeof(piphasfovval2),GE_FLOAT};
_export _piphasfovval3={(char *) &piphasfovval3,sizeof(piphasfovval3),GE_FLOAT};
_export _piphasfovval4={(char *) &piphasfovval4,sizeof(piphasfovval4),GE_FLOAT};
_export _piphasfovval5={(char *) &piphasfovval5,sizeof(piphasfovval5),GE_FLOAT};
_export _piphasfovval6={(char *) &piphasfovval6,sizeof(piphasfovval6),GE_FLOAT};

_export _rec_mode={(char *) &rec_mode,sizeof(rec_mode),GE_INT};

_export _opnewgeo={(char *) &opnewgeo,sizeof(opnewgeo),GE_INT};




_export _simulation={(char *) &simulation,sizeof(simulation),GE_INT};



_export _cflinfrq={(char *) &cflinfrq,sizeof(cflinfrq),GE_FLOAT};
_export _cffield={(char *) &cffield,sizeof(cffield),GE_FLOAT};
_export _cfhpdl={(char *) &cfhpdl,sizeof(cfhpdl),GE_FLOAT};
_export _cfbpdl={(char *) &cfbpdl,sizeof(cfbpdl),GE_FLOAT};
_export _cfhpsl={(char *) &cfhpsl,sizeof(cfhpsl),GE_FLOAT};
_export _cfbpsl={(char *) &cfbpsl,sizeof(cfbpsl),GE_FLOAT};
_export _cfhpv={(char *) &cfhpv,sizeof(cfhpv),GE_FLOAT};
_export _cfbpv={(char *) &cfbpv,sizeof(cfbpv),GE_FLOAT};
_export _cfhqpc={(char *) &cfhqpc,sizeof(cfhqpc),GE_FLOAT};
_export _cfbqpc={(char *) &cfbqpc,sizeof(cfbqpc),GE_FLOAT};
_export _cfhllr={(char *) &cfhllr,sizeof(cfhllr),GE_FLOAT};
_export _cfbllr={(char *) &cfbllr,sizeof(cfbllr),GE_FLOAT};
_export _cfloss={(char *) &cfloss,sizeof(cfloss),GE_FLOAT};

_export _cfbwmin={(char *) &cfbwmin,sizeof(cfbwmin),GE_INT};
_export _cfbwmin1={(char *) &cfbwmin1,sizeof(cfbwmin1),GE_INT};
_export _cfmaxave={(char *) &cfmaxave,sizeof(cfmaxave),GE_FLOAT};
_export _cfmaxpeak={(char *) &cfmaxpeak,sizeof(cfmaxpeak),GE_FLOAT};
_export _cftpssize={(char *) &cftpssize,sizeof(cftpssize),GE_INT};
_export _cccal={(char *) &cccal,sizeof(cccal),GE_FLOAT};
_export _ccjcoil={(char *) &ccjcoil,sizeof(ccjcoil),GE_FLOAT};
_export _cfxfull={(char *) &cfxfull,sizeof(cfxfull),GE_INT};
_export _cfyfull={(char *) &cfyfull,sizeof(cfyfull),GE_INT};
_export _cfzfull={(char *) &cfzfull,sizeof(cfzfull),GE_INT};
_export _cfdbmax={(char *) &cfdbmax,sizeof(cfdbmax),GE_INT};
_export _cfbbmod={(char *) &cfbbmod,sizeof(cfbbmod),GE_INT};
_export _cftrnew={(char *) &cftrnew,sizeof(cftrnew),GE_INT};
_export _cfrecvst={(char *) &cfrecvst,sizeof(cfrecvst),GE_INT};
_export _cfrecvend={(char *) &cfrecvend,sizeof(cfrecvend),GE_INT};
_export _cfgradamp={(char *) &cfgradamp,sizeof(cfgradamp),GE_INT};
_export _cfhtdel={(char *) &cfhtdel,sizeof(cfhtdel),GE_INT};
_export _cfcftdel={(char *) &cfcftdel,sizeof(cfcftdel),GE_INT};
_export _cfcgain={(char *) &cfcgain,sizeof(cfcgain),GE_FLOAT};
_export _cfcoilatten={(char *) &cfcoilatten,sizeof(cfcoilatten),GE_INT};


_export _cfrfrapb={(char *) &cfrfrapb,sizeof(cfrfrapb),GE_INT};
_export _cfrfraph={(char *) &cfrfraph,sizeof(cfrfraph),GE_INT};
_export _cfrfmapb={(char *) &cfrfmapb,sizeof(cfrfmapb),GE_INT};
_export _cfrfmaph={(char *) &cfrfmaph,sizeof(cfrfmaph),GE_INT};
_export _cfrfmpeb={(char *) &cfrfmpeb,sizeof(cfrfmpeb),GE_FLOAT};
_export _cfrfmpeh={(char *) &cfrfmpeh,sizeof(cfrfmpeh),GE_FLOAT};
_export _cfrfmpwb={(char *) &cfrfmpwb,sizeof(cfrfmpwb),GE_INT};
_export _cfrfmpwh={(char *) &cfrfmpwh,sizeof(cfrfmpwh),GE_INT};
_export _cfrfmdcb={(char *) &cfrfmdcb,sizeof(cfrfmdcb),GE_FLOAT};
_export _cfrfmdch={(char *) &cfrfmdch,sizeof(cfrfmdch),GE_FLOAT};
_export _cfrfamptyp={(char *) &cfrfamptyp,sizeof(cfrfamptyp),GE_INT};
_export _cfpwrmontyp={(char *) &cfpwrmontyp,sizeof(cfpwrmontyp),GE_INT};
_export _cfpsdgraddly={(char *) &cfpsdgraddly,sizeof(cfpsdgraddly),GE_INT};
_export _cfpsdrfdly={(char *) &cfpsdrfdly,sizeof(cfpsdrfdly),GE_INT};
_export _cfxrdelay={(char *) &cfxrdelay,sizeof(cfxrdelay),GE_INT};
_export _cfyrdelay={(char *) &cfyrdelay,sizeof(cfyrdelay),GE_INT};
_export _cfzrdelay={(char *) &cfzrdelay,sizeof(cfzrdelay),GE_INT};

_export _piphasfovnub2={(char *) &piphasfovnub2,sizeof(piphasfovnub2),GE_INT};
_export _piswapfc={(char *) &piswapfc,sizeof(piswapfc),GE_INT};
_export _pidltime={(char *) &pidltime,sizeof(pidltime),GE_INT};

_export _piphasfovval1={(char *) &piphasfovval1,sizeof(piphasfovval1),GE_FLOAT};


_export _cfcoilshld={(char *) &cfcoilshld,sizeof(cfcoilshld),GE_INT};

_export _cfrfunblank={(char *) &cfrfunblank,sizeof(cfrfunblank),GE_INT};








_export _cfrmp2xfs={(char *) &cfrmp2xfs,sizeof(cfrmp2xfs),GE_INT};
_export _cffall2x0={(char *) &cffall2x0,sizeof(cffall2x0),GE_INT};
_export _cfxfs={(char *) &cfxfs,sizeof(cfxfs),GE_FLOAT};
_export _cfxfa={(char *) &cfxfa,sizeof(cfxfa),GE_FLOAT};
_export _cfxcc={(char *) &cfxcc,sizeof(cfxcc),GE_FLOAT};
_export _cfxbeta={(char *) &cfxbeta,sizeof(cfxbeta),GE_FLOAT};



_export _cfrmp2yfs={(char *) &cfrmp2yfs,sizeof(cfrmp2yfs),GE_INT};
_export _cffall2y0={(char *) &cffall2y0,sizeof(cffall2y0),GE_INT};
_export _cfyfs={(char *) &cfyfs,sizeof(cfyfs),GE_FLOAT};
_export _cfyfa={(char *) &cfyfa,sizeof(cfyfa),GE_FLOAT};
_export _cfycc={(char *) &cfycc,sizeof(cfycc),GE_FLOAT};
_export _cfybeta={(char *) &cfybeta,sizeof(cfybeta),GE_FLOAT};



_export _cfrmp2zfs={(char *) &cfrmp2zfs,sizeof(cfrmp2zfs),GE_INT};
_export _cffall2z0={(char *) &cffall2z0,sizeof(cffall2z0),GE_INT};
_export _cfzfs={(char *) &cfzfs,sizeof(cfzfs),GE_FLOAT};
_export _cfzfa={(char *) &cfzfa,sizeof(cfzfa),GE_FLOAT};
_export _cfzcc={(char *) &cfzcc,sizeof(cfzcc),GE_FLOAT};
_export _cfzbeta={(char *) &cfzbeta,sizeof(cfzbeta),GE_FLOAT};

_export _cffrecvst={(char *) &cffrecvst,sizeof(cffrecvst),GE_INT};
_export _cffrecvend={(char *) &cffrecvend,sizeof(cffrecvend),GE_INT};
_export _cffrecvnum={(char *) &cffrecvnum,sizeof(cffrecvnum),GE_INT};

_export _cfxgram={(char *) &cfxgram,sizeof(cfxgram),GE_INT};
_export _cfygram={(char *) &cfygram,sizeof(cfygram),GE_INT};
_export _cfzgram={(char *) &cfzgram,sizeof(cfzgram),GE_INT};
_export _cfxasm={(char *) &cfxasm,sizeof(cfxasm),GE_INT};
_export _cfyasm={(char *) &cfyasm,sizeof(cfyasm),GE_INT};
_export _cfzasm={(char *) &cfzasm,sizeof(cfzasm),GE_INT};
_export _cfxgasm={(char *) &cfxgasm,sizeof(cfxgasm),GE_INT};
_export _cfygasm={(char *) &cfygasm,sizeof(cfygasm),GE_INT};
_export _cfzgasm={(char *) &cfzgasm,sizeof(cfzgasm),GE_INT};
_export _cfxseries={(char *) &cfxseries,sizeof(cfxseries),GE_INT};
_export _cfyseries={(char *) &cfyseries,sizeof(cfyseries),GE_INT};
_export _cfzseries={(char *) &cfzseries,sizeof(cfzseries),GE_INT};
_export _cfxnumpower={(char *) &cfxnumpower,sizeof(cfxnumpower),GE_INT};
_export _cfynumpower={(char *) &cfynumpower,sizeof(cfynumpower),GE_INT};
_export _cfznumpower={(char *) &cfznumpower,sizeof(cfznumpower),GE_INT};

_export _cftuning={(char *) &cftuning,sizeof(cftuning),GE_INT};

_export _cfrealtime={(char *) &cfrealtime,sizeof(cfrealtime),GE_INT};

_export _cfcompress={(char *) &cfcompress,sizeof(cfcompress),GE_INT};


_export _cfdbdtts={(char *) &cfdbdtts,sizeof(cfdbdtts),GE_FLOAT};
_export _cfdbdtper={(char *) &cfdbdtper,sizeof(cfdbdtper),GE_FLOAT};
_export _pidbdtts={(char *) &pidbdtts,sizeof(pidbdtts),GE_FLOAT};
_export _pidbdtper={(char *) &pidbdtper,sizeof(pidbdtper),GE_FLOAT};

_export _cfgcoiltype={(char *) &cfgcoiltype,sizeof(cfgcoiltype),GE_INT};

_export _cfsrmode={(char *) &cfsrmode,sizeof(cfsrmode),GE_INT};

_export _cfgpeakirms={(char *) &cfgpeakirms,sizeof(cfgpeakirms),GE_FLOAT};
_export _cfgcontirms={(char *) &cfgcontirms,sizeof(cfgcontirms),GE_FLOAT};
_export _cfgburstime={(char *) &cfgburstime,sizeof(cfgburstime),GE_FLOAT};

_export _cfxirms={(char *) &cfxirms,sizeof(cfxirms),GE_FLOAT};
_export _cfyirms={(char *) &cfyirms,sizeof(cfyirms),GE_FLOAT};
_export _cfzirms={(char *) &cfzirms,sizeof(cfzirms),GE_FLOAT};

_export _cfxipeak={(char *) &cfxipeak,sizeof(cfxipeak),GE_FLOAT};
_export _cfyipeak={(char *) &cfyipeak,sizeof(cfyipeak),GE_FLOAT};
_export _cfzipeak={(char *) &cfzipeak,sizeof(cfzipeak),GE_FLOAT};

_export _cfxamptran={(char *) &cfxamptran,sizeof(cfxamptran),GE_FLOAT};
_export _cfyamptran={(char *) &cfyamptran,sizeof(cfyamptran),GE_FLOAT};
_export _cfzamptran={(char *) &cfzamptran,sizeof(cfzamptran),GE_FLOAT};

_export _cfxiavrgabs={(char *) &cfxiavrgabs,sizeof(cfxiavrgabs),GE_FLOAT};
_export _cfyiavrgabs={(char *) &cfyiavrgabs,sizeof(cfyiavrgabs),GE_FLOAT};
_export _cfziavrgabs={(char *) &cfziavrgabs,sizeof(cfziavrgabs),GE_FLOAT};

_export _cfxirmspos={(char *) &cfxirmspos,sizeof(cfxirmspos),GE_FLOAT};
_export _cfyirmspos={(char *) &cfyirmspos,sizeof(cfyirmspos),GE_FLOAT};
_export _cfzirmspos={(char *) &cfzirmspos,sizeof(cfzirmspos),GE_FLOAT};

_export _cfxirmsneg={(char *) &cfxirmsneg,sizeof(cfxirmsneg),GE_FLOAT};
_export _cfyirmsneg={(char *) &cfyirmsneg,sizeof(cfyirmsneg),GE_FLOAT};
_export _cfzirmsneg={(char *) &cfzirmsneg,sizeof(cfzirmsneg),GE_FLOAT};

_export _cfxpwmdc={(char *) &cfxpwmdc,sizeof(cfxpwmdc),GE_FLOAT};
_export _cfypwmdc={(char *) &cfypwmdc,sizeof(cfypwmdc),GE_FLOAT};
_export _cfzpwmdc={(char *) &cfzpwmdc,sizeof(cfzpwmdc),GE_FLOAT};


_export _cfrmp2xfsfw={(char *) &cfrmp2xfsfw,sizeof(cfrmp2xfsfw),GE_INT};
_export _cfrmp2yfsfw={(char *) &cfrmp2yfsfw,sizeof(cfrmp2yfsfw),GE_INT};
_export _cfrmp2zfsfw={(char *) &cfrmp2zfsfw,sizeof(cfrmp2zfsfw),GE_INT};
_export _cffall2x0fw={(char *) &cffall2x0fw,sizeof(cffall2x0fw),GE_INT};
_export _cffall2y0fw={(char *) &cffall2y0fw,sizeof(cffall2y0fw),GE_INT};
_export _cffall2z0fw={(char *) &cffall2z0fw,sizeof(cffall2z0fw),GE_INT};


_export _cfmaxb1={(char *) &cfmaxb1,sizeof(cfmaxb1),GE_FLOAT};
_export _cfmaxb1sqrd={(char *) &cfmaxb1sqrd,sizeof(cfmaxb1sqrd),GE_FLOAT};
_export _cfmaxb1rms={(char *) &cfmaxb1rms,sizeof(cfmaxb1rms),GE_FLOAT};



_export _cfdbdtdx={(char *) &cfdbdtdx,sizeof(cfdbdtdx),GE_FLOAT};
_export _cfdbdtdy={(char *) &cfdbdtdy,sizeof(cfdbdtdy),GE_FLOAT};
_export _cfdbdtdz={(char *) &cfdbdtdz,sizeof(cfdbdtdz),GE_FLOAT};

_export _sigrammode={(char *) &sigrammode,sizeof(sigrammode),GE_INT};









_export _cfsrmodeconv={(char *) &cfsrmodeconv,sizeof(cfsrmodeconv),GE_FLOAT};
_export _cfsrmodeact={(char *) &cfsrmodeact,sizeof(cfsrmodeact),GE_FLOAT};

_export _avmaxtdel1={(char *) &avmaxtdel1,sizeof(avmaxtdel1),GE_INT};
_export _avminphases={(char *) &avminphases,sizeof(avminphases),GE_INT};
_export _avminetl={(char *) &avminetl,sizeof(avminetl),GE_INT};
_export _avmaxetl={(char *) &avmaxetl,sizeof(avmaxetl),GE_INT};
_export _avminyres={(char *) &avminyres,sizeof(avminyres),GE_INT};
_export _avminslicecnt={(char *) &avminslicecnt,sizeof(avminslicecnt),GE_INT};
_export _avmaxslicecnt={(char *) &avmaxslicecnt,sizeof(avmaxslicecnt),GE_INT};
_export _avmaxtseq={(char *) &avmaxtseq,sizeof(avmaxtseq),GE_INT};
_export _avminxres={(char *) &avminxres,sizeof(avminxres),GE_INT};
_export _avminnshots={(char *) &avminnshots,sizeof(avminnshots),GE_INT};
_export _avmaxnshots={(char *) &avmaxnshots,sizeof(avmaxnshots),GE_INT};
_export _avmaxphasefov={(char *) &avmaxphasefov,sizeof(avmaxphasefov),GE_FLOAT};
_export _avminphasefov={(char *) &avminphasefov,sizeof(avminphasefov),GE_FLOAT};
_export _avminslthick={(char *) &avminslthick,sizeof(avminslthick),GE_FLOAT};
_export _avmaxslthick={(char *) &avmaxslthick,sizeof(avmaxslthick),GE_FLOAT};
_export _avminnex={(char *) &avminnex,sizeof(avminnex),GE_FLOAT};
_export _avmaxnex={(char *) &avmaxnex,sizeof(avmaxnex),GE_FLOAT};
_export _avminflip={(char *) &avminflip,sizeof(avminflip),GE_FLOAT};
_export _avmaxflip={(char *) &avmaxflip,sizeof(avmaxflip),GE_FLOAT};
_export _avminslspace={(char *) &avminslspace,sizeof(avminslspace),GE_FLOAT};
_export _avmaxslspace={(char *) &avmaxslspace,sizeof(avmaxslspace),GE_FLOAT};

_export _cfmaxb1rmshead={(char *) &cfmaxb1rmshead,sizeof(cfmaxb1rmshead),GE_FLOAT};




_export _pidifpage={(char *) &pidifpage,sizeof(pidifpage),GE_INT};

_export _pidifaxnub={(char *) &pidifaxnub,sizeof(pidifaxnub),GE_INT};
_export _pidifaxval1={(char *) pidifaxval1,sizeof(pidifaxval1),GE_STRUCT};
_export _pidifaxval2={(char *) pidifaxval2,sizeof(pidifaxval2),GE_STRUCT};
_export _pidifaxval3={(char *) pidifaxval3,sizeof(pidifaxval3),GE_STRUCT};
_export _pidifaxval4={(char *) pidifaxval4,sizeof(pidifaxval4),GE_STRUCT};
_export _pidifaxval5={(char *) pidifaxval5,sizeof(pidifaxval5),GE_STRUCT};

_export _pidefbval={(char *) &pidefbval,sizeof(pidefbval),GE_INT};
_export _pibvnub={(char *) &pibvnub,sizeof(pibvnub),GE_INT};
_export _pibval2={(char *) &pibval2,sizeof(pibval2),GE_INT};
_export _pibval3={(char *) &pibval3,sizeof(pibval3),GE_INT};
_export _pibval4={(char *) &pibval4,sizeof(pibval4),GE_INT};

_export _pidifrecnub={(char *) &pidifrecnub,sizeof(pidifrecnub),GE_INT};

_export _pidifrecval1={(char *) pidifrecval1,sizeof(pidifrecval1),GE_STRUCT};
_export _pidfirecval2={(char *) pidfirecval2,sizeof(pidfirecval2),GE_STRUCT};
_export _pidfirecval3={(char *) pidfirecval3,sizeof(pidfirecval3),GE_STRUCT};
_export _pidfirecval4={(char *) pidfirecval4,sizeof(pidfirecval4),GE_STRUCT};
_export _pidfirecval5={(char *) pidfirecval5,sizeof(pidfirecval5),GE_STRUCT};




_export _pimonitor={(char *) &pimonitor,sizeof(pimonitor),GE_INT};


_export _pimonfovnub={(char *) &pimonfovnub,sizeof(pimonfovnub),GE_INT};
_export _pimonfovval2={(char *) &pimonfovval2,sizeof(pimonfovval2),GE_FLOAT};
_export _pimonfovval3={(char *) &pimonfovval3,sizeof(pimonfovval3),GE_FLOAT};
_export _pimonfovval4={(char *) &pimonfovval4,sizeof(pimonfovval4),GE_FLOAT};
_export _pidfmonfov={(char *) &pidfmonfov,sizeof(pidfmonfov),GE_FLOAT};


_export _pimonthicknub={(char *) &pimonthicknub,sizeof(pimonthicknub),GE_INT};
_export _pimonthickval2={(char *) &pimonthickval2,sizeof(pimonthickval2),GE_FLOAT};
_export _pimonthickval3={(char *) &pimonthickval3,sizeof(pimonthickval3),GE_FLOAT};
_export _pimonthickval4={(char *) &pimonthickval4,sizeof(pimonthickval4),GE_FLOAT};
_export _pidfmonthick={(char *) &pidfmonthick,sizeof(pidfmonthick),GE_FLOAT};


_export _mon_loc={(char *) &mon_loc,sizeof(mon_loc),GE_STRUCT};






_export _pizmult={(char *) &pizmult,sizeof(pizmult),GE_INT};
_export _piccsat_obl={(char *) &piccsat_obl,sizeof(piccsat_obl),GE_INT};


_export _pifcinenub={(char *) &pifcinenub,sizeof(pifcinenub),GE_INT};
_export _pifcinedefval={(char *) &pifcinedefval,sizeof(pifcinedefval),GE_INT};
_export _pifcineval2={(char *) &pifcineval2,sizeof(pifcineval2),GE_INT};
_export _pifcineval3={(char *) &pifcineval3,sizeof(pifcineval3),GE_INT};
_export _pifcineval4={(char *) &pifcineval4,sizeof(pifcineval4),GE_INT};


_export _pitagging={(char *) &pitagging,sizeof(pitagging),GE_INT};
_export _pitagspcdefval={(char *) &pitagspcdefval,sizeof(pitagspcdefval),GE_INT};
_export _pitagspcval2={(char *) &pitagspcval2,sizeof(pitagspcval2),GE_INT};
_export _pitagspcval3={(char *) &pitagspcval3,sizeof(pitagspcval3),GE_INT};
_export _pitagspcval4={(char *) &pitagspcval4,sizeof(pitagspcval4),GE_INT};


_export _pibsptinub={(char *) &pibsptinub,sizeof(pibsptinub),GE_INT};
_export _pibsptidefval={(char *) &pibsptidefval,sizeof(pibsptidefval),GE_INT};
_export _pibsptival2={(char *) &pibsptival2,sizeof(pibsptival2),GE_INT};
_export _pibsptival3={(char *) &pibsptival3,sizeof(pibsptival3),GE_INT};
_export _pibsptival4={(char *) &pibsptival4,sizeof(pibsptival4),GE_INT};
_export _pibsptival5={(char *) &pibsptival5,sizeof(pibsptival5),GE_INT};
_export _pibsptival6={(char *) &pibsptival6,sizeof(pibsptival6),GE_INT};



_export _cfxmgrampow={(char *) &cfxmgrampow,sizeof(cfxmgrampow),GE_FLOAT};
_export _cfymgrampow={(char *) &cfymgrampow,sizeof(cfymgrampow),GE_FLOAT};
_export _cfzmgrampow={(char *) &cfzmgrampow,sizeof(cfzmgrampow),GE_FLOAT};
_export _cfsdlim={(char *) &cfsdlim,sizeof(cfsdlim),GE_FLOAT};
_export _cfxrsat={(char *) &cfxrsat,sizeof(cfxrsat),GE_FLOAT};
_export _cfyrsat={(char *) &cfyrsat,sizeof(cfyrsat),GE_FLOAT};
_export _cfzrsat={(char *) &cfzrsat,sizeof(cfzrsat),GE_FLOAT};
_export _cfxvsat={(char *) &cfxvsat,sizeof(cfxvsat),GE_FLOAT};
_export _cfyvsat={(char *) &cfyvsat,sizeof(cfyvsat),GE_FLOAT};
_export _cfzvsat={(char *) &cfzvsat,sizeof(cfzvsat),GE_FLOAT};
_export _cfgpmpow={(char *) &cfgpmpow,sizeof(cfgpmpow),GE_FLOAT};
_export _cfmgps={(char *) &cfmgps,sizeof(cfmgps),GE_FLOAT};
_export _cfvhr={(char *) &cfvhr,sizeof(cfvhr),GE_FLOAT};
_export _cfrcoil={(char *) &cfrcoil,sizeof(cfrcoil),GE_FLOAT};
_export _cflcoil={(char *) &cflcoil,sizeof(cflcoil),GE_FLOAT};
_export _cfraccoil={(char *) &cfraccoil,sizeof(cfraccoil),GE_FLOAT};
_export _cfpmgs={(char *) &cfpmgs,sizeof(cfpmgs),GE_FLOAT};
_export _cfrhr={(char *) &cfrhr,sizeof(cfrhr),GE_FLOAT};
_export _cfxvpwm={(char *) &cfxvpwm,sizeof(cfxvpwm),GE_FLOAT};
_export _cfyvpwm={(char *) &cfyvpwm,sizeof(cfyvpwm),GE_FLOAT};
_export _cfzvpwm={(char *) &cfzvpwm,sizeof(cfzvpwm),GE_FLOAT};
_export _cfcerdbw1={(char *) &cfcerdbw1,sizeof(cfcerdbw1),GE_FLOAT};
_export _cfcerdbw2={(char *) &cfcerdbw2,sizeof(cfcerdbw2),GE_FLOAT};
_export _cfcerdbw3={(char *) &cfcerdbw3,sizeof(cfcerdbw3),GE_FLOAT};
_export _cfcerdbw4={(char *) &cfcerdbw4,sizeof(cfcerdbw4),GE_FLOAT};


_export _cffastprescan={(char *) &cffastprescan,sizeof(cffastprescan),GE_INT};


_export _pimultistation={(char *) &pimultistation,sizeof(pimultistation),GE_INT};
_export _piautostep={(char *) &piautostep,sizeof(piautostep),GE_INT};
_export _pisioverlap={(char *) &pisioverlap,sizeof(pisioverlap),GE_INT};


_export _csi_grid_on={(char *) &csi_grid_on,sizeof(csi_grid_on),GE_INT};
_export _pispecprescan={(char *) &pispecprescan,sizeof(pispecprescan),GE_INT};
_export _picsimode={(char *) &picsimode,sizeof(picsimode),GE_INT};
_export _rhrlfov={(char *) &rhrlfov,sizeof(rhrlfov),GE_INT};
_export _rhapfov={(char *) &rhapfov,sizeof(rhapfov),GE_INT};
_export _rhsifov={(char *) &rhsifov,sizeof(rhsifov),GE_INT};













_export _cfcerdtype={(char *) &cfcerdtype,sizeof(cfcerdtype),GE_INT};


_export _cfpicture={(char *) &cfpicture,sizeof(cfpicture),GE_INT};


#endif /* h_epic_exportstr_h */

