/*
 *  FastCINE.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_FastCINE_runtime_h
#define h_FastCINE_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 955457808;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_fcineim},
	{GE_INT, (char *)&_fcinent},
	{GE_INT, (char *)&_fcine_option_key_status},
};
_cvname _namearray[] = {
	{"fcine_option_key_status",2},
	{"fcineim",0},
	{"fcinent",1},
};
_rspdataptr _rsparray[] = {
{0,0,0}};
int _ncvs = 3;
int _nrsps = 0;

#endif /* h_FastCINE_runtime_h */

