/*
 *  Hard180.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_Hard180_runtime_h
#define h_Hard180_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 939340054;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_HARD180_SLOT},
	{GE_INT, (char *)&_pos_hard180},
	{GE_FLOAT, (char *)&_flip_hard180},
	{GE_INT, (char *)&_res_hard180},
	{GE_FLOAT, (char *)&_a_hard180},
	{GE_INT, (char *)&_ia_hard180},
	{GE_INT, (char *)&_pw_hard180},
};
_cvname _namearray[] = {
	{"HARD180_SLOT",0},
	{"a_hard180",4},
	{"flip_hard180",2},
	{"ia_hard180",5},
	{"pos_hard180",1},
	{"pw_hard180",6},
	{"res_hard180",3},
};
_rspdataptr _rsparray[] = {
{0,0,0}};
int _ncvs = 7;
int _nrsps = 0;

#endif /* h_Hard180_runtime_h */

