/*
 *  Mpl.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_Mpl_runtime_h
#define h_Mpl_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 953056178;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_dummy_temp},
	{GE_INT, (char *)&_slq_per_sat},
	{GE_INT, (char *)&_slq_per_spsat},
	{GE_INT, (char *)&_slq_per_cssat},
	{GE_INT, (char *)&_test_flag},
	{GE_INT, (char *)&_maxsatcount},
	{GE_INT, (char *)&_satcount},
	{GE_INT, (char *)&_satinterval},
	{GE_FLOAT, (char *)&_avesat_per_slq},
	{GE_INT, (char *)&_NUMRFSAT},
};
_cvname _namearray[] = {
	{"NUMRFSAT",9},
	{"avesat_per_slq",8},
	{"dummy_temp",0},
	{"maxsatcount",5},
	{"satcount",6},
	{"satinterval",7},
	{"slq_per_cssat",3},
	{"slq_per_sat",1},
	{"slq_per_spsat",2},
	{"test_flag",4},
};
_rspdataptr _rsparray[] = {
{0,0,0}};
int _ncvs = 10;
int _nrsps = 0;

#endif /* h_Mpl_runtime_h */

