/*
 *  RespgateFC.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_RespgateFC_runtime_h
#define h_RespgateFC_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 936910429;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
	{GE_INT, (char *)&_rsamp_time},
	{GE_INT, (char *)&_max_resp_wait},
	{GE_INT, (char *)&_debug_rg},
	{GE_INT, (char *)&_oprtpoint0},
};
_cvname _namearray[] = {
	{"debug_rg",2},
	{"max_resp_wait",1},
	{"oprtpoint0",3},
	{"rsamp_time",0},
};
_rspdataptr _rsparray[] = {
	{"resp_phase",GE_SHORT,0},
	{"rtrig_maxct",GE_INT,0},
	{"rtrig_val_act_st",GE_INT,0},
	{"rtrig_val_end",GE_INT,0},
	{"rtrig_val_st",GE_INT,0},
};
int _ncvs = 4;
int _nrsps = 5;

#endif /* h_RespgateFC_runtime_h */

