/*
 *  Vascular.runtime.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : May 19 2000
 *  Time : 11:30:59
 */

#ifndef h_Vascular_runtime_h
#define h_Vascular_runtime_h

char _header_revision[] = "1.0";
char _header_release[] = "8.3";
long _header_source_rev= 921876806;
short _header_fixed[] = {1};
short _header_product[] = {1};

_cvdataptr _cvarray[] = {
{0, 0}};
_cvname _namearray[] = {
{0,0}
};
_rspdataptr _rsparray[] = {
{0,0,0}};
int _ncvs = 0;
int _nrsps = 0;

#endif /* h_Vascular_runtime_h */

